BEGIN;

CREATE TABLE IF NOT EXISTS schema_migration_contracts (
  migration_name TEXT PRIMARY KEY,
  contract_version INTEGER NOT NULL CHECK (contract_version > 0),
  contract_fingerprint TEXT NOT NULL
    CHECK (contract_fingerprint ~ '^[0-9a-f]{64}$'),
  installed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (length(trim(migration_name)) > 0)
);

-- Every unresolved new listing points at one schema-owned placeholder. Literal
-- extracted labels live only in the non-authoritative input observation table.
CREATE TABLE IF NOT EXISTS aircraft_sale_listing_pending_compatibility_placeholder (
  singleton_id INTEGER PRIMARY KEY CHECK (singleton_id = 1),
  aircraft_manufacturer_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_manufacturers(id) ON DELETE RESTRICT,
  aircraft_model_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_models(id) ON DELETE RESTRICT,
  aircraft_model_variant_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_model_variants(id) ON DELETE RESTRICT
);

-- Parsed/manual fields are retrieval hints, never quoted source evidence.
CREATE TABLE IF NOT EXISTS aircraft_listing_identity_input_observations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_sale_listing_id BIGINT
    REFERENCES aircraft_sale_listings(id) ON DELETE SET NULL,
  source_url TEXT,
  observed_make TEXT NOT NULL,
  observed_family TEXT NOT NULL,
  observed_designation TEXT NOT NULL,
  model_year INTEGER NOT NULL CHECK (model_year BETWEEN 1900 AND 2200),
  serial_number TEXT,
  registration_number TEXT,
  input_json TEXT NOT NULL,
  observation_sha256 TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (length(trim(observed_make)) > 0),
  CHECK (length(trim(observed_family)) > 0),
  CHECK (length(trim(observed_designation)) > 0),
  CHECK (length(trim(input_json)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_aircraft_listing_identity_input_listing
  ON aircraft_listing_identity_input_observations (aircraft_sale_listing_id);

CREATE OR REPLACE FUNCTION preserve_aircraft_listing_identity_input_observation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP = 'UPDATE'
    AND OLD.aircraft_sale_listing_id IS NOT NULL
    AND NEW.aircraft_sale_listing_id IS NULL
    AND NOT EXISTS (
      SELECT 1 FROM aircraft_sale_listings listing
      WHERE listing.id = OLD.aircraft_sale_listing_id
    )
    AND NEW.id IS NOT DISTINCT FROM OLD.id
    AND NEW.source_url IS NOT DISTINCT FROM OLD.source_url
    AND NEW.observed_make IS NOT DISTINCT FROM OLD.observed_make
    AND NEW.observed_family IS NOT DISTINCT FROM OLD.observed_family
    AND NEW.observed_designation IS NOT DISTINCT FROM OLD.observed_designation
    AND NEW.model_year IS NOT DISTINCT FROM OLD.model_year
    AND NEW.serial_number IS NOT DISTINCT FROM OLD.serial_number
    AND NEW.registration_number IS NOT DISTINCT FROM OLD.registration_number
    AND NEW.input_json IS NOT DISTINCT FROM OLD.input_json
    AND NEW.observation_sha256 IS NOT DISTINCT FROM OLD.observation_sha256
    AND NEW.created_at IS NOT DISTINCT FROM OLD.created_at THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION 'aircraft listing identity input observations are append-only';
END;
$function$;

DROP TRIGGER IF EXISTS aircraft_listing_identity_input_append_only_update
  ON aircraft_listing_identity_input_observations;
CREATE TRIGGER aircraft_listing_identity_input_append_only_update
BEFORE UPDATE ON aircraft_listing_identity_input_observations
FOR EACH ROW
EXECUTE FUNCTION preserve_aircraft_listing_identity_input_observation();

DROP TRIGGER IF EXISTS aircraft_listing_identity_input_append_only_delete
  ON aircraft_listing_identity_input_observations;
CREATE TRIGGER aircraft_listing_identity_input_append_only_delete
BEFORE DELETE ON aircraft_listing_identity_input_observations
FOR EACH ROW
EXECUTE FUNCTION preserve_aircraft_listing_identity_input_observation();

-- Hold catalog/listing writers while the reserved placeholder is checked and
-- seeded. This makes collision rejection deterministic under concurrency.
LOCK TABLE aircraft_manufacturers, aircraft_models, aircraft_model_variants,
  aircraft_sale_listings IN SHARE ROW EXCLUSIVE MODE;

DO $guard$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM aircraft_sale_listing_pending_compatibility_placeholder
    WHERE singleton_id = 1
  ) AND (
    EXISTS (
      SELECT 1 FROM aircraft_manufacturers
      WHERE id = -1 OR normalized_name = '__aircost_pending_faa_make__'
    )
    OR EXISTS (
      SELECT 1 FROM aircraft_models
      WHERE id = -1 OR normalized_name = '__aircost_pending_faa_family__'
    )
    OR EXISTS (
      SELECT 1 FROM aircraft_model_variants
      WHERE id = -1 OR normalized_name = '__aircost_pending_faa_identity__'
    )
  ) THEN
    RAISE EXCEPTION 'pending aircraft compatibility reserved keys already exist without schema ownership';
  END IF;
END;
$guard$;

INSERT INTO aircraft_manufacturers (id, name, normalized_name)
VALUES (-1, 'Pending FAA curation', '__aircost_pending_faa_make__')
ON CONFLICT (normalized_name) DO NOTHING;

INSERT INTO aircraft_models (
  id, aircraft_manufacturer_id, name, normalized_name
)
SELECT -1, id, 'Pending FAA curation', '__aircost_pending_faa_family__'
FROM aircraft_manufacturers
WHERE normalized_name = '__aircost_pending_faa_make__'
ON CONFLICT (aircraft_manufacturer_id, normalized_name) DO NOTHING;

INSERT INTO aircraft_model_variants (
  id, aircraft_model_id, name, normalized_name
)
SELECT -1, id, 'Pending FAA curation', '__aircost_pending_faa_identity__'
FROM aircraft_models
WHERE normalized_name = '__aircost_pending_faa_family__'
  AND aircraft_manufacturer_id = (
    SELECT id FROM aircraft_manufacturers
    WHERE normalized_name = '__aircost_pending_faa_make__'
  )
ON CONFLICT (aircraft_model_id, normalized_name) DO NOTHING;

INSERT INTO aircraft_sale_listing_pending_compatibility_placeholder (
  singleton_id, aircraft_manufacturer_id, aircraft_model_id,
  aircraft_model_variant_id
)
SELECT 1, manufacturer.id, model.id, variant.id
FROM aircraft_manufacturers manufacturer
JOIN aircraft_models model
  ON model.aircraft_manufacturer_id = manufacturer.id
JOIN aircraft_model_variants variant
  ON variant.aircraft_model_id = model.id
WHERE manufacturer.name = 'Pending FAA curation'
  AND manufacturer.normalized_name = '__aircost_pending_faa_make__'
  AND model.name = 'Pending FAA curation'
  AND model.normalized_name = '__aircost_pending_faa_family__'
  AND variant.name = 'Pending FAA curation'
  AND variant.normalized_name = '__aircost_pending_faa_identity__'
ON CONFLICT (singleton_id) DO NOTHING;

DO $guard$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM aircraft_sale_listing_pending_compatibility_placeholder placeholder
    JOIN aircraft_manufacturers manufacturer
      ON manufacturer.id = placeholder.aircraft_manufacturer_id
    JOIN aircraft_models model
      ON model.id = placeholder.aircraft_model_id
     AND model.aircraft_manufacturer_id = manufacturer.id
    JOIN aircraft_model_variants variant
      ON variant.id = placeholder.aircraft_model_variant_id
     AND variant.aircraft_model_id = model.id
    WHERE placeholder.singleton_id = 1
      AND manufacturer.id = -1
      AND manufacturer.name = 'Pending FAA curation'
      AND manufacturer.normalized_name = '__aircost_pending_faa_make__'
      AND model.id = -1
      AND model.name = 'Pending FAA curation'
      AND model.normalized_name = '__aircost_pending_faa_family__'
      AND variant.id = -1
      AND variant.name = 'Pending FAA curation'
      AND variant.normalized_name = '__aircost_pending_faa_identity__'
  ) THEN
    RAISE EXCEPTION 'pending aircraft compatibility placeholder is missing or does not own the reserved hierarchy';
  END IF;
END;
$guard$;

-- The sole bridge from canonical aircraft identity to the valuation hierarchy.
-- Provenance is copied from the live immutable assignment at creation.
CREATE TABLE IF NOT EXISTS aircraft_valuation_compatibility_projections (
  aircraft_model_variant_id BIGINT PRIMARY KEY
    REFERENCES aircraft_model_variants(id) ON DELETE RESTRICT,
  aircraft_make_id BIGINT NOT NULL,
  aircraft_model_family_id BIGINT NOT NULL,
  aircraft_designation_id BIGINT NOT NULL,
  aircraft_generation_id BIGINT,
  aircraft_factory_package_id BIGINT,
  created_from_aircraft_sale_listing_id BIGINT NOT NULL,
  created_from_identity_assignment_id BIGINT NOT NULL,
  identity_decision_id BIGINT NOT NULL
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  identity_evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  faa_registry_snapshot_id BIGINT NOT NULL
    REFERENCES faa_registry_snapshots(id) ON DELETE RESTRICT,
  faa_n_number TEXT NOT NULL,
  faa_source_record_sha256 TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (aircraft_model_family_id, aircraft_make_id)
    REFERENCES aircraft_model_families(id, aircraft_make_id) ON DELETE RESTRICT,
  FOREIGN KEY (aircraft_designation_id, aircraft_model_family_id)
    REFERENCES aircraft_designations(id, aircraft_model_family_id) ON DELETE RESTRICT,
  FOREIGN KEY (aircraft_generation_id, aircraft_model_family_id)
    REFERENCES aircraft_generations(id, aircraft_model_family_id) ON DELETE RESTRICT,
  FOREIGN KEY (aircraft_factory_package_id, aircraft_model_family_id)
    REFERENCES aircraft_factory_packages(id, aircraft_model_family_id) ON DELETE RESTRICT,
  FOREIGN KEY (faa_registry_snapshot_id, faa_n_number)
    REFERENCES faa_registry_aircraft(snapshot_id, n_number) ON DELETE RESTRICT,
  FOREIGN KEY (faa_registry_snapshot_id, faa_source_record_sha256)
    REFERENCES faa_registry_aircraft(snapshot_id, source_record_sha256) ON DELETE RESTRICT,
  CHECK (aircraft_make_id > 0),
  CHECK (aircraft_model_family_id > 0),
  CHECK (aircraft_designation_id > 0),
  CHECK (aircraft_generation_id IS NULL OR aircraft_generation_id > 0),
  CHECK (aircraft_factory_package_id IS NULL OR aircraft_factory_package_id > 0),
  CHECK (created_from_aircraft_sale_listing_id > 0),
  CHECK (created_from_identity_assignment_id > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_aircraft_valuation_projection_identity
  ON aircraft_valuation_compatibility_projections (
    aircraft_make_id, aircraft_model_family_id, aircraft_designation_id,
    coalesce(aircraft_generation_id, 0::BIGINT),
    coalesce(aircraft_factory_package_id, 0::BIGINT)
  );

CREATE OR REPLACE FUNCTION preserve_pending_aircraft_compatibility_placeholder()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  RAISE EXCEPTION 'pending aircraft compatibility placeholder is immutable';
END;
$function$;

DROP TRIGGER IF EXISTS pending_aircraft_placeholder_immutable_update
  ON aircraft_sale_listing_pending_compatibility_placeholder;
CREATE TRIGGER pending_aircraft_placeholder_immutable_update
BEFORE UPDATE ON aircraft_sale_listing_pending_compatibility_placeholder
FOR EACH ROW
EXECUTE FUNCTION preserve_pending_aircraft_compatibility_placeholder();

DROP TRIGGER IF EXISTS pending_aircraft_placeholder_immutable_delete
  ON aircraft_sale_listing_pending_compatibility_placeholder;
CREATE TRIGGER pending_aircraft_placeholder_immutable_delete
BEFORE DELETE ON aircraft_sale_listing_pending_compatibility_placeholder
FOR EACH ROW
EXECUTE FUNCTION preserve_pending_aircraft_compatibility_placeholder();

CREATE OR REPLACE FUNCTION preserve_pending_aircraft_compatibility_catalog_row()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  protected_id BIGINT;
BEGIN
  IF TG_TABLE_NAME = 'aircraft_manufacturers' THEN
    SELECT aircraft_manufacturer_id INTO protected_id
    FROM aircraft_sale_listing_pending_compatibility_placeholder
    WHERE singleton_id = 1;
  ELSIF TG_TABLE_NAME = 'aircraft_models' THEN
    SELECT aircraft_model_id INTO protected_id
    FROM aircraft_sale_listing_pending_compatibility_placeholder
    WHERE singleton_id = 1;
  ELSE
    SELECT aircraft_model_variant_id INTO protected_id
    FROM aircraft_sale_listing_pending_compatibility_placeholder
    WHERE singleton_id = 1;
  END IF;
  IF OLD.id = protected_id THEN
    RAISE EXCEPTION 'pending aircraft compatibility catalog hierarchy is immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS pending_aircraft_placeholder_manufacturer_immutable_update
  ON aircraft_manufacturers;
CREATE TRIGGER pending_aircraft_placeholder_manufacturer_immutable_update
BEFORE UPDATE ON aircraft_manufacturers
FOR EACH ROW
EXECUTE FUNCTION preserve_pending_aircraft_compatibility_catalog_row();
DROP TRIGGER IF EXISTS pending_aircraft_placeholder_manufacturer_immutable_delete
  ON aircraft_manufacturers;
CREATE TRIGGER pending_aircraft_placeholder_manufacturer_immutable_delete
BEFORE DELETE ON aircraft_manufacturers
FOR EACH ROW
EXECUTE FUNCTION preserve_pending_aircraft_compatibility_catalog_row();
DROP TRIGGER IF EXISTS pending_aircraft_placeholder_model_immutable_update
  ON aircraft_models;
CREATE TRIGGER pending_aircraft_placeholder_model_immutable_update
BEFORE UPDATE ON aircraft_models
FOR EACH ROW
EXECUTE FUNCTION preserve_pending_aircraft_compatibility_catalog_row();
DROP TRIGGER IF EXISTS pending_aircraft_placeholder_model_immutable_delete
  ON aircraft_models;
CREATE TRIGGER pending_aircraft_placeholder_model_immutable_delete
BEFORE DELETE ON aircraft_models
FOR EACH ROW
EXECUTE FUNCTION preserve_pending_aircraft_compatibility_catalog_row();
DROP TRIGGER IF EXISTS pending_aircraft_placeholder_variant_immutable_update
  ON aircraft_model_variants;
CREATE TRIGGER pending_aircraft_placeholder_variant_immutable_update
BEFORE UPDATE ON aircraft_model_variants
FOR EACH ROW
EXECUTE FUNCTION preserve_pending_aircraft_compatibility_catalog_row();
DROP TRIGGER IF EXISTS pending_aircraft_placeholder_variant_immutable_delete
  ON aircraft_model_variants;
CREATE TRIGGER pending_aircraft_placeholder_variant_immutable_delete
BEFORE DELETE ON aircraft_model_variants
FOR EACH ROW
EXECUTE FUNCTION preserve_pending_aircraft_compatibility_catalog_row();

CREATE OR REPLACE FUNCTION require_aircraft_projection_or_placeholder_on_listing_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM aircraft_sale_listing_pending_compatibility_placeholder placeholder
    WHERE placeholder.singleton_id = 1
      AND placeholder.aircraft_model_variant_id =
          NEW.aircraft_model_variant_id
  ) AND NOT EXISTS (
    SELECT 1
    FROM aircraft_valuation_compatibility_projections projection
    WHERE projection.aircraft_model_variant_id =
          NEW.aircraft_model_variant_id
  ) THEN
    RAISE EXCEPTION 'new listing must use the pending aircraft placeholder or an existing canonical projection';
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS listing_insert_requires_aircraft_projection_or_placeholder
  ON aircraft_sale_listings;
CREATE TRIGGER listing_insert_requires_aircraft_projection_or_placeholder
BEFORE INSERT ON aircraft_sale_listings
FOR EACH ROW
EXECUTE FUNCTION require_aircraft_projection_or_placeholder_on_listing_insert();

-- A transition is a short-lived command and cannot survive its INSERT.
CREATE TABLE IF NOT EXISTS aircraft_valuation_projection_transitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_sale_listing_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_sale_listings(id) ON DELETE CASCADE,
  identity_assignment_id BIGINT NOT NULL,
  transition_kind TEXT NOT NULL CHECK (
    transition_kind IN ('initial', 'current_repair', 'successor')
  ),
  selected_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (identity_assignment_id, aircraft_sale_listing_id)
    REFERENCES aircraft_sale_listing_identity_assignments(
      id, aircraft_sale_listing_id
    ) ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION validate_aircraft_valuation_projection_transition()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  -- Serialize reserved-key creation and lock the listing whose pointer moves.
  LOCK TABLE aircraft_manufacturers, aircraft_models,
    aircraft_model_variants, aircraft_valuation_compatibility_projections
    IN SHARE ROW EXCLUSIVE MODE;
  PERFORM 1
  FROM aircraft_sale_listings listing
  WHERE listing.id = NEW.aircraft_sale_listing_id
  FOR UPDATE;

  IF NOT EXISTS (
    SELECT 1
    FROM aircraft_sale_listings listing
    JOIN aircraft_sale_listing_identity_assignments assignment
      ON assignment.id = NEW.identity_assignment_id
     AND assignment.aircraft_sale_listing_id = listing.id
    JOIN aircraft_makes make ON make.id = assignment.aircraft_make_id
    JOIN aircraft_model_families family
      ON family.id = assignment.aircraft_model_family_id
     AND family.aircraft_make_id = make.id
    JOIN aircraft_designations designation
      ON designation.id = assignment.aircraft_designation_id
     AND designation.aircraft_model_family_id = family.id
    JOIN faa_registry_snapshots snapshot
      ON snapshot.id = assignment.faa_registry_snapshot_id
    WHERE listing.id = NEW.aircraft_sale_listing_id
      AND listing.ingestion_state <> 'ready'
      AND assignment.aircraft_make_id > 0
      AND assignment.aircraft_model_family_id > 0
      AND assignment.aircraft_designation_id > 0
      AND (
        assignment.aircraft_generation_id IS NULL
        OR assignment.aircraft_generation_id > 0
      )
      AND (
        assignment.aircraft_factory_package_id IS NULL
        OR assignment.aircraft_factory_package_id > 0
      )
      AND snapshot.id = (
        SELECT id FROM faa_registry_snapshots
        ORDER BY snapshot_date DESC, id DESC LIMIT 1
      )
      AND (
        (NEW.transition_kind = 'initial'
          AND assignment.supersedes_assignment_id IS NULL
          AND NOT EXISTS (
            SELECT 1
            FROM aircraft_sale_listing_current_identity_assignments current_assignment
            WHERE current_assignment.aircraft_sale_listing_id = listing.id
          ))
        OR (NEW.transition_kind = 'current_repair'
          AND EXISTS (
            SELECT 1
            FROM aircraft_sale_listing_current_identity_assignments current_assignment
            WHERE current_assignment.aircraft_sale_listing_id = listing.id
              AND current_assignment.identity_assignment_id = assignment.id
          ))
        OR (NEW.transition_kind = 'successor'
          AND EXISTS (
            SELECT 1
            FROM aircraft_sale_listing_current_identity_assignments current_assignment
            WHERE current_assignment.aircraft_sale_listing_id = listing.id
              AND current_assignment.identity_assignment_id =
                    assignment.supersedes_assignment_id
          ))
      )
      AND (
        EXISTS (
          SELECT 1
          FROM aircraft_valuation_compatibility_projections projection
          WHERE projection.aircraft_make_id = assignment.aircraft_make_id
            AND projection.aircraft_model_family_id =
                  assignment.aircraft_model_family_id
            AND projection.aircraft_designation_id =
                  assignment.aircraft_designation_id
            AND projection.aircraft_generation_id IS NOT DISTINCT FROM
                  assignment.aircraft_generation_id
            AND projection.aircraft_factory_package_id IS NOT DISTINCT FROM
                  assignment.aircraft_factory_package_id
        )
        OR (
          (
            NOT EXISTS (
              SELECT 1 FROM aircraft_manufacturers
              WHERE normalized_name =
                '__aircost_projection_make_' || make.id::TEXT || '__'
            )
            OR EXISTS (
              SELECT 1
              FROM aircraft_valuation_compatibility_projections projection
              JOIN aircraft_model_variants projected_variant
                ON projected_variant.id =
                   projection.aircraft_model_variant_id
              JOIN aircraft_models projected_model
                ON projected_model.id = projected_variant.aircraft_model_id
              JOIN aircraft_manufacturers projected_manufacturer
                ON projected_manufacturer.id =
                   projected_model.aircraft_manufacturer_id
              WHERE projection.aircraft_make_id = make.id
                AND projected_manufacturer.name = make.name
                AND projected_manufacturer.normalized_name =
                    '__aircost_projection_make_' || make.id::TEXT || '__'
            )
          )
          AND (
            NOT EXISTS (
              SELECT 1 FROM aircraft_models
              WHERE normalized_name =
                '__aircost_projection_family_' || family.id::TEXT || '__'
            )
            OR EXISTS (
              SELECT 1
              FROM aircraft_valuation_compatibility_projections projection
              JOIN aircraft_model_variants projected_variant
                ON projected_variant.id =
                   projection.aircraft_model_variant_id
              JOIN aircraft_models projected_model
                ON projected_model.id = projected_variant.aircraft_model_id
              WHERE projection.aircraft_model_family_id = family.id
                AND projected_model.name = family.name
                AND projected_model.normalized_name =
                    '__aircost_projection_family_' || family.id::TEXT || '__'
            )
          )
          AND NOT EXISTS (
            SELECT 1 FROM aircraft_model_variants
            WHERE normalized_name =
              '__aircost_projection_identity_'
              || designation.id::TEXT || '_'
              || coalesce(assignment.aircraft_generation_id, 0)::TEXT || '_'
              || coalesce(assignment.aircraft_factory_package_id, 0)::TEXT
              || '__'
          )
        )
      )
  ) THEN
    RAISE EXCEPTION 'aircraft projection command requires a current FAA assignment and either an exact projection or collision-free reserved keys';
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS aircraft_valuation_transition_validate_insert
  ON aircraft_valuation_projection_transitions;
CREATE TRIGGER aircraft_valuation_transition_validate_insert
BEFORE INSERT ON aircraft_valuation_projection_transitions
FOR EACH ROW
EXECUTE FUNCTION validate_aircraft_valuation_projection_transition();

CREATE OR REPLACE FUNCTION preserve_aircraft_valuation_projection_transition()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  RAISE EXCEPTION 'aircraft projection transitions are immutable';
END;
$function$;

DROP TRIGGER IF EXISTS aircraft_valuation_transition_immutable_update
  ON aircraft_valuation_projection_transitions;
CREATE TRIGGER aircraft_valuation_transition_immutable_update
BEFORE UPDATE ON aircraft_valuation_projection_transitions
FOR EACH ROW
EXECUTE FUNCTION preserve_aircraft_valuation_projection_transition();

CREATE OR REPLACE FUNCTION validate_aircraft_valuation_compatibility_projection()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM aircraft_valuation_projection_transitions transition
    JOIN aircraft_sale_listing_identity_assignments assignment
      ON assignment.id = transition.identity_assignment_id
     AND assignment.aircraft_sale_listing_id =
         transition.aircraft_sale_listing_id
    JOIN aircraft_makes make ON make.id = assignment.aircraft_make_id
    JOIN aircraft_model_families family
      ON family.id = assignment.aircraft_model_family_id
     AND family.aircraft_make_id = make.id
    JOIN aircraft_designations designation
      ON designation.id = assignment.aircraft_designation_id
     AND designation.aircraft_model_family_id = family.id
    LEFT JOIN aircraft_generations generation
      ON generation.id = assignment.aircraft_generation_id
     AND generation.aircraft_model_family_id = family.id
    LEFT JOIN aircraft_factory_packages package
      ON package.id = assignment.aircraft_factory_package_id
     AND package.aircraft_model_family_id = family.id
    JOIN aircraft_model_variants legacy_variant
      ON legacy_variant.id = NEW.aircraft_model_variant_id
    JOIN aircraft_models legacy_model
      ON legacy_model.id = legacy_variant.aircraft_model_id
    JOIN aircraft_manufacturers legacy_manufacturer
      ON legacy_manufacturer.id = legacy_model.aircraft_manufacturer_id
    WHERE assignment.aircraft_make_id = NEW.aircraft_make_id
      AND assignment.aircraft_model_family_id = NEW.aircraft_model_family_id
      AND assignment.aircraft_designation_id = NEW.aircraft_designation_id
      AND assignment.aircraft_generation_id IS NOT DISTINCT FROM
          NEW.aircraft_generation_id
      AND assignment.aircraft_factory_package_id IS NOT DISTINCT FROM
          NEW.aircraft_factory_package_id
      AND assignment.aircraft_sale_listing_id =
          NEW.created_from_aircraft_sale_listing_id
      AND assignment.id = NEW.created_from_identity_assignment_id
      AND assignment.identity_decision_id = NEW.identity_decision_id
      AND assignment.identity_evidence_claim_id =
          NEW.identity_evidence_claim_id
      AND assignment.faa_registry_snapshot_id = NEW.faa_registry_snapshot_id
      AND assignment.faa_n_number = NEW.faa_n_number
      AND assignment.faa_source_record_sha256 =
          NEW.faa_source_record_sha256
      AND legacy_manufacturer.name = make.name
      AND legacy_manufacturer.normalized_name =
          '__aircost_projection_make_' || make.id::TEXT || '__'
      AND legacy_model.name = family.name
      AND legacy_model.normalized_name =
          '__aircost_projection_family_' || family.id::TEXT || '__'
      AND legacy_variant.name =
        designation.official_designation
        || CASE WHEN generation.id IS NULL
             THEN '' ELSE ' / ' || generation.name END
        || CASE WHEN package.id IS NULL
             THEN '' ELSE ' / ' || package.name END
      AND legacy_variant.normalized_name =
        '__aircost_projection_identity_'
        || designation.id::TEXT || '_'
        || coalesce(generation.id, 0)::TEXT || '_'
        || coalesce(package.id, 0)::TEXT || '__'
      AND (
        assignment.aircraft_generation_id IS NULL
        OR EXISTS (
          SELECT 1
          FROM aircraft_generation_designations applicability
          WHERE applicability.aircraft_generation_id =
                assignment.aircraft_generation_id
            AND applicability.aircraft_designation_id =
                assignment.aircraft_designation_id
        )
      )
      AND (
        assignment.aircraft_factory_package_id IS NULL
        OR EXISTS (
          SELECT 1
          FROM aircraft_package_applicability applicability
          WHERE applicability.aircraft_factory_package_id =
                assignment.aircraft_factory_package_id
            AND applicability.aircraft_designation_id =
                assignment.aircraft_designation_id
            AND (
              applicability.aircraft_generation_id IS NULL
              OR applicability.aircraft_generation_id IS NOT DISTINCT FROM
                 assignment.aircraft_generation_id
            )
        )
      )
      AND NOT EXISTS (
        SELECT 1 FROM aircraft_sale_listings child
        WHERE child.aircraft_model_variant_id = legacy_variant.id
      )
      AND NOT EXISTS (
        SELECT 1 FROM rental_aircraft_offerings child
        WHERE child.aircraft_model_variant_id = legacy_variant.id
      )
      AND NOT EXISTS (
        SELECT 1 FROM aircraft_model_spec_versions child
        WHERE child.aircraft_model_variant_id = legacy_variant.id
      )
      AND NOT EXISTS (
        SELECT 1 FROM aircraft_model_variant_price_points child
        WHERE child.aircraft_model_variant_id = legacy_variant.id
      )
      AND NOT EXISTS (
        SELECT 1 FROM aircraft_model_variant_default_avionics child
        WHERE child.aircraft_model_variant_id = legacy_variant.id
      )
  ) THEN
    RAISE EXCEPTION 'aircraft compatibility projection requires the active command, exact copied assignment provenance, and its fresh reserved hierarchy';
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS aircraft_valuation_projection_validate_insert
  ON aircraft_valuation_compatibility_projections;
CREATE TRIGGER aircraft_valuation_projection_validate_insert
BEFORE INSERT ON aircraft_valuation_compatibility_projections
FOR EACH ROW
EXECUTE FUNCTION validate_aircraft_valuation_compatibility_projection();

CREATE OR REPLACE FUNCTION execute_aircraft_valuation_projection_transition()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  affected_rows BIGINT;
BEGIN
  INSERT INTO aircraft_manufacturers (name, normalized_name)
  SELECT
    make.name,
    '__aircost_projection_make_' || make.id::TEXT || '__'
  FROM aircraft_sale_listing_identity_assignments assignment
  JOIN aircraft_makes make ON make.id = assignment.aircraft_make_id
  WHERE assignment.id = NEW.identity_assignment_id
    AND assignment.aircraft_sale_listing_id =
        NEW.aircraft_sale_listing_id
    AND NOT EXISTS (
      SELECT 1 FROM aircraft_manufacturers existing
      WHERE existing.normalized_name =
          '__aircost_projection_make_' || make.id::TEXT || '__'
    );

  INSERT INTO aircraft_models (
    aircraft_manufacturer_id, name, normalized_name
  )
  SELECT
    legacy_manufacturer.id,
    family.name,
    '__aircost_projection_family_' || family.id::TEXT || '__'
  FROM aircraft_sale_listing_identity_assignments assignment
  JOIN aircraft_model_families family
    ON family.id = assignment.aircraft_model_family_id
  JOIN aircraft_manufacturers legacy_manufacturer
    ON legacy_manufacturer.normalized_name =
       '__aircost_projection_make_'
       || assignment.aircraft_make_id::TEXT || '__'
  WHERE assignment.id = NEW.identity_assignment_id
    AND assignment.aircraft_sale_listing_id =
        NEW.aircraft_sale_listing_id
    AND NOT EXISTS (
      SELECT 1 FROM aircraft_models existing
      WHERE existing.normalized_name =
          '__aircost_projection_family_' || family.id::TEXT || '__'
    );

  INSERT INTO aircraft_model_variants (
    aircraft_model_id, name, normalized_name
  )
  SELECT
    legacy_model.id,
    designation.official_designation
      || CASE WHEN generation.id IS NULL
           THEN '' ELSE ' / ' || generation.name END
      || CASE WHEN package.id IS NULL
           THEN '' ELSE ' / ' || package.name END,
    '__aircost_projection_identity_'
      || designation.id::TEXT || '_'
      || coalesce(generation.id, 0)::TEXT || '_'
      || coalesce(package.id, 0)::TEXT || '__'
  FROM aircraft_sale_listing_identity_assignments assignment
  JOIN aircraft_designations designation
    ON designation.id = assignment.aircraft_designation_id
  LEFT JOIN aircraft_generations generation
    ON generation.id = assignment.aircraft_generation_id
  LEFT JOIN aircraft_factory_packages package
    ON package.id = assignment.aircraft_factory_package_id
  JOIN aircraft_models legacy_model
    ON legacy_model.normalized_name =
       '__aircost_projection_family_'
       || assignment.aircraft_model_family_id::TEXT || '__'
  WHERE assignment.id = NEW.identity_assignment_id
    AND assignment.aircraft_sale_listing_id =
        NEW.aircraft_sale_listing_id
    AND NOT EXISTS (
      SELECT 1 FROM aircraft_model_variants existing
      WHERE existing.normalized_name =
        '__aircost_projection_identity_'
        || designation.id::TEXT || '_'
        || coalesce(generation.id, 0)::TEXT || '_'
        || coalesce(package.id, 0)::TEXT || '__'
    );

  INSERT INTO aircraft_valuation_compatibility_projections (
    aircraft_model_variant_id,
    aircraft_make_id,
    aircraft_model_family_id,
    aircraft_designation_id,
    aircraft_generation_id,
    aircraft_factory_package_id,
    created_from_aircraft_sale_listing_id,
    created_from_identity_assignment_id,
    identity_decision_id,
    identity_evidence_claim_id,
    faa_registry_snapshot_id,
    faa_n_number,
    faa_source_record_sha256
  )
  SELECT
    legacy_variant.id,
    assignment.aircraft_make_id,
    assignment.aircraft_model_family_id,
    assignment.aircraft_designation_id,
    assignment.aircraft_generation_id,
    assignment.aircraft_factory_package_id,
    assignment.aircraft_sale_listing_id,
    assignment.id,
    assignment.identity_decision_id,
    assignment.identity_evidence_claim_id,
    assignment.faa_registry_snapshot_id,
    assignment.faa_n_number,
    assignment.faa_source_record_sha256
  FROM aircraft_sale_listing_identity_assignments assignment
  JOIN aircraft_model_variants legacy_variant
    ON legacy_variant.normalized_name =
       '__aircost_projection_identity_'
       || assignment.aircraft_designation_id::TEXT || '_'
       || coalesce(assignment.aircraft_generation_id, 0)::TEXT || '_'
       || coalesce(assignment.aircraft_factory_package_id, 0)::TEXT || '__'
  WHERE assignment.id = NEW.identity_assignment_id
    AND assignment.aircraft_sale_listing_id =
        NEW.aircraft_sale_listing_id
    AND NOT EXISTS (
      SELECT 1
      FROM aircraft_valuation_compatibility_projections projection
      WHERE projection.aircraft_make_id = assignment.aircraft_make_id
        AND projection.aircraft_model_family_id =
            assignment.aircraft_model_family_id
        AND projection.aircraft_designation_id =
            assignment.aircraft_designation_id
        AND projection.aircraft_generation_id IS NOT DISTINCT FROM
            assignment.aircraft_generation_id
        AND projection.aircraft_factory_package_id IS NOT DISTINCT FROM
            assignment.aircraft_factory_package_id
    );

  UPDATE aircraft_sale_listings
  SET aircraft_model_variant_id = (
        SELECT projection.aircraft_model_variant_id
        FROM aircraft_valuation_compatibility_projections projection
        JOIN aircraft_sale_listing_identity_assignments assignment
          ON assignment.id = NEW.identity_assignment_id
         AND assignment.aircraft_sale_listing_id =
             NEW.aircraft_sale_listing_id
         AND projection.aircraft_make_id = assignment.aircraft_make_id
         AND projection.aircraft_model_family_id =
             assignment.aircraft_model_family_id
         AND projection.aircraft_designation_id =
             assignment.aircraft_designation_id
         AND projection.aircraft_generation_id IS NOT DISTINCT FROM
             assignment.aircraft_generation_id
         AND projection.aircraft_factory_package_id IS NOT DISTINCT FROM
             assignment.aircraft_factory_package_id
      ),
      updated_at = CURRENT_TIMESTAMP
  WHERE id = NEW.aircraft_sale_listing_id;
  GET DIAGNOSTICS affected_rows = ROW_COUNT;
  IF affected_rows <> 1 THEN
    RAISE EXCEPTION 'aircraft projection transition did not repoint exactly one listing';
  END IF;

  IF NEW.transition_kind = 'initial' THEN
    INSERT INTO aircraft_sale_listing_current_identity_assignments (
      aircraft_sale_listing_id, identity_assignment_id, selected_at
    ) VALUES (
      NEW.aircraft_sale_listing_id, NEW.identity_assignment_id, NEW.selected_at
    );
  ELSIF NEW.transition_kind = 'successor' THEN
    UPDATE aircraft_sale_listing_current_identity_assignments
    SET identity_assignment_id = NEW.identity_assignment_id,
        selected_at = NEW.selected_at
    WHERE aircraft_sale_listing_id = NEW.aircraft_sale_listing_id
      AND identity_assignment_id = (
        SELECT supersedes_assignment_id
        FROM aircraft_sale_listing_identity_assignments
        WHERE id = NEW.identity_assignment_id
          AND aircraft_sale_listing_id = NEW.aircraft_sale_listing_id
      );
    GET DIAGNOSTICS affected_rows = ROW_COUNT;
    IF affected_rows <> 1 THEN
      RAISE EXCEPTION 'aircraft projection successor did not advance exactly one current pointer';
    END IF;
  END IF;

  DELETE FROM aircraft_valuation_projection_transitions
  WHERE id = NEW.id;
  GET DIAGNOSTICS affected_rows = ROW_COUNT;
  IF affected_rows <> 1 THEN
    RAISE EXCEPTION 'aircraft projection command did not consume itself';
  END IF;
  RETURN NULL;
END;
$function$;

DROP TRIGGER IF EXISTS aircraft_valuation_transition_execute
  ON aircraft_valuation_projection_transitions;
CREATE TRIGGER aircraft_valuation_transition_execute
AFTER INSERT ON aircraft_valuation_projection_transitions
FOR EACH ROW
EXECUTE FUNCTION execute_aircraft_valuation_projection_transition();

CREATE OR REPLACE FUNCTION preserve_aircraft_valuation_compatibility_projection()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  RAISE EXCEPTION 'aircraft compatibility projections are immutable';
END;
$function$;

DROP TRIGGER IF EXISTS aircraft_valuation_projection_immutable_update
  ON aircraft_valuation_compatibility_projections;
CREATE TRIGGER aircraft_valuation_projection_immutable_update
BEFORE UPDATE ON aircraft_valuation_compatibility_projections
FOR EACH ROW
EXECUTE FUNCTION preserve_aircraft_valuation_compatibility_projection();
DROP TRIGGER IF EXISTS aircraft_valuation_projection_immutable_delete
  ON aircraft_valuation_compatibility_projections;
CREATE TRIGGER aircraft_valuation_projection_immutable_delete
BEFORE DELETE ON aircraft_valuation_compatibility_projections
FOR EACH ROW
EXECUTE FUNCTION preserve_aircraft_valuation_compatibility_projection();

CREATE OR REPLACE FUNCTION preserve_projected_aircraft_catalog_row()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  is_projected BOOLEAN;
BEGIN
  IF TG_TABLE_NAME = 'aircraft_model_variants' THEN
    SELECT EXISTS (
      SELECT 1
      FROM aircraft_valuation_compatibility_projections projection
      WHERE projection.aircraft_model_variant_id = OLD.id
    ) INTO is_projected;
  ELSIF TG_TABLE_NAME = 'aircraft_models' THEN
    SELECT EXISTS (
      SELECT 1
      FROM aircraft_model_variants variant
      JOIN aircraft_valuation_compatibility_projections projection
        ON projection.aircraft_model_variant_id = variant.id
      WHERE variant.aircraft_model_id = OLD.id
    ) INTO is_projected;
  ELSE
    SELECT EXISTS (
      SELECT 1
      FROM aircraft_models model
      JOIN aircraft_model_variants variant
        ON variant.aircraft_model_id = model.id
      JOIN aircraft_valuation_compatibility_projections projection
        ON projection.aircraft_model_variant_id = variant.id
      WHERE model.aircraft_manufacturer_id = OLD.id
    ) INTO is_projected;
  END IF;
  IF is_projected THEN
    RAISE EXCEPTION 'projected aircraft compatibility catalog rows are immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS projected_aircraft_variant_immutable_update
  ON aircraft_model_variants;
CREATE TRIGGER projected_aircraft_variant_immutable_update
BEFORE UPDATE ON aircraft_model_variants
FOR EACH ROW EXECUTE FUNCTION preserve_projected_aircraft_catalog_row();
DROP TRIGGER IF EXISTS projected_aircraft_variant_immutable_delete
  ON aircraft_model_variants;
CREATE TRIGGER projected_aircraft_variant_immutable_delete
BEFORE DELETE ON aircraft_model_variants
FOR EACH ROW EXECUTE FUNCTION preserve_projected_aircraft_catalog_row();
DROP TRIGGER IF EXISTS projected_aircraft_model_immutable_update
  ON aircraft_models;
CREATE TRIGGER projected_aircraft_model_immutable_update
BEFORE UPDATE ON aircraft_models
FOR EACH ROW EXECUTE FUNCTION preserve_projected_aircraft_catalog_row();
DROP TRIGGER IF EXISTS projected_aircraft_model_immutable_delete
  ON aircraft_models;
CREATE TRIGGER projected_aircraft_model_immutable_delete
BEFORE DELETE ON aircraft_models
FOR EACH ROW EXECUTE FUNCTION preserve_projected_aircraft_catalog_row();
DROP TRIGGER IF EXISTS projected_aircraft_manufacturer_immutable_update
  ON aircraft_manufacturers;
CREATE TRIGGER projected_aircraft_manufacturer_immutable_update
BEFORE UPDATE ON aircraft_manufacturers
FOR EACH ROW EXECUTE FUNCTION preserve_projected_aircraft_catalog_row();
DROP TRIGGER IF EXISTS projected_aircraft_manufacturer_immutable_delete
  ON aircraft_manufacturers;
CREATE TRIGGER projected_aircraft_manufacturer_immutable_delete
BEFORE DELETE ON aircraft_manufacturers
FOR EACH ROW EXECUTE FUNCTION preserve_projected_aircraft_catalog_row();

CREATE OR REPLACE FUNCTION preserve_compatibility_projected_aircraft_entity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
DECLARE
  projection_exists BOOLEAN;
BEGIN
  EXECUTE format(
    'SELECT EXISTS (
       SELECT 1
       FROM aircraft_valuation_compatibility_projections
       WHERE %I = $1
     )',
    TG_ARGV[0]
  ) INTO projection_exists USING OLD.id;
  IF projection_exists THEN
    RAISE EXCEPTION 'compatibility-projected canonical aircraft hierarchy rows are immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS compatibility_projected_make_immutable_update
  ON aircraft_makes;
CREATE TRIGGER compatibility_projected_make_immutable_update
BEFORE UPDATE ON aircraft_makes
FOR EACH ROW
EXECUTE FUNCTION preserve_compatibility_projected_aircraft_entity('aircraft_make_id');
DROP TRIGGER IF EXISTS compatibility_projected_make_immutable_delete
  ON aircraft_makes;
CREATE TRIGGER compatibility_projected_make_immutable_delete
BEFORE DELETE ON aircraft_makes
FOR EACH ROW
EXECUTE FUNCTION preserve_compatibility_projected_aircraft_entity('aircraft_make_id');
DROP TRIGGER IF EXISTS compatibility_projected_family_immutable_update
  ON aircraft_model_families;
CREATE TRIGGER compatibility_projected_family_immutable_update
BEFORE UPDATE ON aircraft_model_families
FOR EACH ROW
EXECUTE FUNCTION preserve_compatibility_projected_aircraft_entity('aircraft_model_family_id');
DROP TRIGGER IF EXISTS compatibility_projected_family_immutable_delete
  ON aircraft_model_families;
CREATE TRIGGER compatibility_projected_family_immutable_delete
BEFORE DELETE ON aircraft_model_families
FOR EACH ROW
EXECUTE FUNCTION preserve_compatibility_projected_aircraft_entity('aircraft_model_family_id');
DROP TRIGGER IF EXISTS compatibility_projected_designation_immutable_update
  ON aircraft_designations;
CREATE TRIGGER compatibility_projected_designation_immutable_update
BEFORE UPDATE ON aircraft_designations
FOR EACH ROW
EXECUTE FUNCTION preserve_compatibility_projected_aircraft_entity('aircraft_designation_id');
DROP TRIGGER IF EXISTS compatibility_projected_designation_immutable_delete
  ON aircraft_designations;
CREATE TRIGGER compatibility_projected_designation_immutable_delete
BEFORE DELETE ON aircraft_designations
FOR EACH ROW
EXECUTE FUNCTION preserve_compatibility_projected_aircraft_entity('aircraft_designation_id');
DROP TRIGGER IF EXISTS compatibility_projected_generation_immutable_update
  ON aircraft_generations;
CREATE TRIGGER compatibility_projected_generation_immutable_update
BEFORE UPDATE ON aircraft_generations
FOR EACH ROW
EXECUTE FUNCTION preserve_compatibility_projected_aircraft_entity('aircraft_generation_id');
DROP TRIGGER IF EXISTS compatibility_projected_generation_immutable_delete
  ON aircraft_generations;
CREATE TRIGGER compatibility_projected_generation_immutable_delete
BEFORE DELETE ON aircraft_generations
FOR EACH ROW
EXECUTE FUNCTION preserve_compatibility_projected_aircraft_entity('aircraft_generation_id');
DROP TRIGGER IF EXISTS compatibility_projected_package_immutable_update
  ON aircraft_factory_packages;
CREATE TRIGGER compatibility_projected_package_immutable_update
BEFORE UPDATE ON aircraft_factory_packages
FOR EACH ROW
EXECUTE FUNCTION preserve_compatibility_projected_aircraft_entity('aircraft_factory_package_id');
DROP TRIGGER IF EXISTS compatibility_projected_package_immutable_delete
  ON aircraft_factory_packages;
CREATE TRIGGER compatibility_projected_package_immutable_delete
BEFORE DELETE ON aircraft_factory_packages
FOR EACH ROW
EXECUTE FUNCTION preserve_compatibility_projected_aircraft_entity('aircraft_factory_package_id');

CREATE OR REPLACE FUNCTION preserve_compatibility_projected_aircraft_applicability()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_TABLE_NAME = 'aircraft_generation_designations'
    AND EXISTS (
      SELECT 1
      FROM aircraft_valuation_compatibility_projections projection
      WHERE projection.aircraft_generation_id =
            OLD.aircraft_generation_id
        AND projection.aircraft_designation_id =
            OLD.aircraft_designation_id
    ) THEN
    RAISE EXCEPTION 'compatibility-projected generation applicability is immutable';
  END IF;
  IF TG_TABLE_NAME = 'aircraft_package_applicability'
    AND EXISTS (
      SELECT 1
      FROM aircraft_valuation_compatibility_projections projection
      WHERE projection.aircraft_factory_package_id =
            OLD.aircraft_factory_package_id
        AND projection.aircraft_designation_id =
            OLD.aircraft_designation_id
        AND (
          OLD.aircraft_generation_id IS NULL
          OR projection.aircraft_generation_id =
             OLD.aircraft_generation_id
        )
    ) THEN
    RAISE EXCEPTION 'compatibility-projected package applicability is immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS compatibility_projected_generation_link_immutable_update
  ON aircraft_generation_designations;
CREATE TRIGGER compatibility_projected_generation_link_immutable_update
BEFORE UPDATE ON aircraft_generation_designations
FOR EACH ROW
EXECUTE FUNCTION preserve_compatibility_projected_aircraft_applicability();
DROP TRIGGER IF EXISTS compatibility_projected_generation_link_immutable_delete
  ON aircraft_generation_designations;
CREATE TRIGGER compatibility_projected_generation_link_immutable_delete
BEFORE DELETE ON aircraft_generation_designations
FOR EACH ROW
EXECUTE FUNCTION preserve_compatibility_projected_aircraft_applicability();
DROP TRIGGER IF EXISTS compatibility_projected_package_link_immutable_update
  ON aircraft_package_applicability;
CREATE TRIGGER compatibility_projected_package_link_immutable_update
BEFORE UPDATE ON aircraft_package_applicability
FOR EACH ROW
EXECUTE FUNCTION preserve_compatibility_projected_aircraft_applicability();
DROP TRIGGER IF EXISTS compatibility_projected_package_link_immutable_delete
  ON aircraft_package_applicability;
CREATE TRIGGER compatibility_projected_package_link_immutable_delete
BEFORE DELETE ON aircraft_package_applicability
FOR EACH ROW
EXECUTE FUNCTION preserve_compatibility_projected_aircraft_applicability();

CREATE OR REPLACE FUNCTION require_guarded_listing_aircraft_projection_transition()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.aircraft_model_variant_id IS DISTINCT FROM
     OLD.aircraft_model_variant_id
    AND NOT EXISTS (
      SELECT 1
      FROM aircraft_valuation_projection_transitions transition
      JOIN aircraft_sale_listing_identity_assignments assignment
        ON assignment.id = transition.identity_assignment_id
       AND assignment.aircraft_sale_listing_id =
           transition.aircraft_sale_listing_id
      JOIN aircraft_valuation_compatibility_projections projection
        ON projection.aircraft_make_id = assignment.aircraft_make_id
       AND projection.aircraft_model_family_id =
           assignment.aircraft_model_family_id
       AND projection.aircraft_designation_id =
           assignment.aircraft_designation_id
       AND projection.aircraft_generation_id IS NOT DISTINCT FROM
           assignment.aircraft_generation_id
       AND projection.aircraft_factory_package_id IS NOT DISTINCT FROM
           assignment.aircraft_factory_package_id
      WHERE transition.aircraft_sale_listing_id = NEW.id
        AND projection.aircraft_model_variant_id =
            NEW.aircraft_model_variant_id
    ) THEN
    RAISE EXCEPTION 'listing aircraft compatibility FK may change only through an exact guarded transition';
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS listing_aircraft_projection_transition_update
  ON aircraft_sale_listings;
CREATE TRIGGER listing_aircraft_projection_transition_update
BEFORE UPDATE OF aircraft_model_variant_id ON aircraft_sale_listings
FOR EACH ROW
EXECUTE FUNCTION require_guarded_listing_aircraft_projection_transition();

CREATE OR REPLACE FUNCTION require_exact_projection_for_current_aircraft_identity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM aircraft_sale_listings listing
    JOIN aircraft_valuation_projection_transitions transition
      ON transition.aircraft_sale_listing_id = listing.id
     AND transition.identity_assignment_id = NEW.identity_assignment_id
    JOIN aircraft_sale_listing_identity_assignments assignment
      ON assignment.id = NEW.identity_assignment_id
     AND assignment.aircraft_sale_listing_id =
         NEW.aircraft_sale_listing_id
    JOIN aircraft_valuation_compatibility_projections projection
      ON projection.aircraft_model_variant_id =
         listing.aircraft_model_variant_id
     AND projection.aircraft_make_id = assignment.aircraft_make_id
     AND projection.aircraft_model_family_id =
         assignment.aircraft_model_family_id
     AND projection.aircraft_designation_id =
         assignment.aircraft_designation_id
     AND projection.aircraft_generation_id IS NOT DISTINCT FROM
         assignment.aircraft_generation_id
     AND projection.aircraft_factory_package_id IS NOT DISTINCT FROM
         assignment.aircraft_factory_package_id
    WHERE listing.id = NEW.aircraft_sale_listing_id
  ) THEN
    RAISE EXCEPTION 'current aircraft identity requires the exact guarded listing projection';
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS listing_current_identity_projection_insert
  ON aircraft_sale_listing_current_identity_assignments;
CREATE TRIGGER listing_current_identity_projection_insert
BEFORE INSERT ON aircraft_sale_listing_current_identity_assignments
FOR EACH ROW
EXECUTE FUNCTION require_exact_projection_for_current_aircraft_identity();
DROP TRIGGER IF EXISTS listing_current_identity_projection_update
  ON aircraft_sale_listing_current_identity_assignments;
CREATE TRIGGER listing_current_identity_projection_update
BEFORE UPDATE OF identity_assignment_id
ON aircraft_sale_listing_current_identity_assignments
FOR EACH ROW
EXECUTE FUNCTION require_exact_projection_for_current_aircraft_identity();

CREATE OR REPLACE FUNCTION validate_aircraft_valuation_projection_transition_delete()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM aircraft_sale_listings listing
    JOIN aircraft_sale_listing_current_identity_assignments current_assignment
      ON current_assignment.aircraft_sale_listing_id = listing.id
     AND current_assignment.identity_assignment_id =
         OLD.identity_assignment_id
    JOIN aircraft_sale_listing_identity_assignments assignment
      ON assignment.id = current_assignment.identity_assignment_id
     AND assignment.aircraft_sale_listing_id = listing.id
    JOIN aircraft_valuation_compatibility_projections projection
      ON projection.aircraft_model_variant_id =
         listing.aircraft_model_variant_id
     AND projection.aircraft_make_id = assignment.aircraft_make_id
     AND projection.aircraft_model_family_id =
         assignment.aircraft_model_family_id
     AND projection.aircraft_designation_id =
         assignment.aircraft_designation_id
     AND projection.aircraft_generation_id IS NOT DISTINCT FROM
         assignment.aircraft_generation_id
     AND projection.aircraft_factory_package_id IS NOT DISTINCT FROM
         assignment.aircraft_factory_package_id
    WHERE listing.id = OLD.aircraft_sale_listing_id
  ) THEN
    RAISE EXCEPTION 'aircraft projection transition cannot close before exact pointer and listing projection';
  END IF;
  RETURN OLD;
END;
$function$;

DROP TRIGGER IF EXISTS aircraft_valuation_transition_validate_delete
  ON aircraft_valuation_projection_transitions;
CREATE TRIGGER aircraft_valuation_transition_validate_delete
BEFORE DELETE ON aircraft_valuation_projection_transitions
FOR EACH ROW
EXECUTE FUNCTION validate_aircraft_valuation_projection_transition_delete();

CREATE OR REPLACE VIEW aircraft_sale_listing_exact_compatibility_projections AS
SELECT
  listing.id AS listing_id,
  current_assignment.identity_assignment_id,
  listing.aircraft_model_variant_id,
  assignment.aircraft_make_id,
  assignment.aircraft_model_family_id,
  assignment.aircraft_designation_id,
  assignment.aircraft_generation_id,
  assignment.aircraft_factory_package_id
FROM aircraft_sale_listings listing
JOIN aircraft_sale_listing_current_identity_assignments current_assignment
  ON current_assignment.aircraft_sale_listing_id = listing.id
JOIN aircraft_sale_listing_identity_assignments assignment
  ON assignment.id = current_assignment.identity_assignment_id
 AND assignment.aircraft_sale_listing_id = listing.id
JOIN aircraft_valuation_compatibility_projections projection
  ON projection.aircraft_model_variant_id =
     listing.aircraft_model_variant_id
 AND projection.aircraft_make_id = assignment.aircraft_make_id
 AND projection.aircraft_model_family_id =
     assignment.aircraft_model_family_id
 AND projection.aircraft_designation_id =
     assignment.aircraft_designation_id
 AND projection.aircraft_generation_id IS NOT DISTINCT FROM
     assignment.aircraft_generation_id
 AND projection.aircraft_factory_package_id IS NOT DISTINCT FROM
     assignment.aircraft_factory_package_id;

-- Existing rows are not adopted or assigned mechanically. They remain as
-- evidence but cannot be valuation-ready without an exact curated projection.
UPDATE aircraft_sale_listings
SET ingestion_state = 'quarantined',
    ingestion_error =
      'aircraft compatibility projection migration: ready listing has no exact canonical projection',
    ingestion_completed_at = NULL,
    is_verified = FALSE,
    updated_at = CURRENT_TIMESTAMP
WHERE ingestion_state = 'ready'
  AND NOT EXISTS (
    SELECT 1
    FROM aircraft_sale_listing_exact_compatibility_projections exact_projection
    WHERE exact_projection.listing_id = aircraft_sale_listings.id
  );

CREATE OR REPLACE FUNCTION require_ready_listing_aircraft_projection()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.ingestion_state <> 'ready' THEN
    RETURN NEW;
  END IF;
  IF TG_OP = 'INSERT' THEN
    IF NOT EXISTS (
      SELECT 1
      FROM aircraft_sale_listing_exact_compatibility_projections exact_projection
      WHERE exact_projection.listing_id = NEW.id
        AND exact_projection.aircraft_model_variant_id =
            NEW.aircraft_model_variant_id
    ) THEN
      RAISE EXCEPTION 'ready listing must first persist its exact canonical aircraft compatibility projection';
    END IF;
  ELSIF NOT EXISTS (
    SELECT 1
    FROM aircraft_sale_listing_current_identity_assignments current_assignment
    JOIN aircraft_sale_listing_identity_assignments assignment
      ON assignment.id = current_assignment.identity_assignment_id
     AND assignment.aircraft_sale_listing_id =
         current_assignment.aircraft_sale_listing_id
    JOIN aircraft_valuation_compatibility_projections projection
      ON projection.aircraft_model_variant_id =
         NEW.aircraft_model_variant_id
     AND projection.aircraft_make_id = assignment.aircraft_make_id
     AND projection.aircraft_model_family_id =
         assignment.aircraft_model_family_id
     AND projection.aircraft_designation_id =
         assignment.aircraft_designation_id
     AND projection.aircraft_generation_id IS NOT DISTINCT FROM
         assignment.aircraft_generation_id
     AND projection.aircraft_factory_package_id IS NOT DISTINCT FROM
         assignment.aircraft_factory_package_id
    WHERE current_assignment.aircraft_sale_listing_id = NEW.id
  ) THEN
    RAISE EXCEPTION 'ready listing requires its exact canonical aircraft compatibility projection';
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS listing_ready_requires_aircraft_projection
  ON aircraft_sale_listings;
CREATE TRIGGER listing_ready_requires_aircraft_projection
BEFORE UPDATE OF ingestion_state, aircraft_model_variant_id
ON aircraft_sale_listings
FOR EACH ROW
EXECUTE FUNCTION require_ready_listing_aircraft_projection();

DROP TRIGGER IF EXISTS listing_ready_insert_requires_aircraft_projection
  ON aircraft_sale_listings;
CREATE TRIGGER listing_ready_insert_requires_aircraft_projection
BEFORE INSERT ON aircraft_sale_listings
FOR EACH ROW
EXECUTE FUNCTION require_ready_listing_aircraft_projection();

CREATE OR REPLACE FUNCTION reject_ready_pending_aircraft_placeholder()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.ingestion_state = 'ready'
    AND EXISTS (
      SELECT 1
      FROM aircraft_sale_listing_pending_compatibility_placeholder placeholder
      WHERE placeholder.singleton_id = 1
        AND placeholder.aircraft_model_variant_id =
            NEW.aircraft_model_variant_id
    ) THEN
    RAISE EXCEPTION 'pending aircraft compatibility placeholder cannot become ready';
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS listing_ready_rejects_pending_aircraft_placeholder
  ON aircraft_sale_listings;
CREATE TRIGGER listing_ready_rejects_pending_aircraft_placeholder
BEFORE UPDATE OF ingestion_state, aircraft_model_variant_id
ON aircraft_sale_listings
FOR EACH ROW
EXECUTE FUNCTION reject_ready_pending_aircraft_placeholder();

CREATE OR REPLACE FUNCTION prevent_projected_aircraft_evidence_variant_move()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.aircraft_model_variant_id IS DISTINCT FROM
     OLD.aircraft_model_variant_id
    AND (
      EXISTS (
        SELECT 1
        FROM aircraft_valuation_compatibility_projections projection
        WHERE projection.aircraft_model_variant_id =
            OLD.aircraft_model_variant_id
      )
      OR EXISTS (
        SELECT 1
        FROM aircraft_valuation_compatibility_projections projection
        WHERE projection.aircraft_model_variant_id =
            NEW.aircraft_model_variant_id
      )
    ) THEN
    IF TG_TABLE_NAME = 'aircraft_model_spec_versions' THEN
      RAISE EXCEPTION 'aircraft spec evidence cannot move into or out of a projected variant';
    ELSIF TG_TABLE_NAME = 'aircraft_model_variant_price_points' THEN
      RAISE EXCEPTION 'aircraft price evidence cannot move into or out of a projected variant';
    ELSE
      RAISE EXCEPTION 'default avionics evidence cannot move into or out of a projected variant';
    END IF;
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS projected_aircraft_spec_variant_move
  ON aircraft_model_spec_versions;
CREATE TRIGGER projected_aircraft_spec_variant_move
BEFORE UPDATE OF aircraft_model_variant_id ON aircraft_model_spec_versions
FOR EACH ROW
EXECUTE FUNCTION prevent_projected_aircraft_evidence_variant_move();
DROP TRIGGER IF EXISTS projected_aircraft_price_variant_move
  ON aircraft_model_variant_price_points;
CREATE TRIGGER projected_aircraft_price_variant_move
BEFORE UPDATE OF aircraft_model_variant_id
ON aircraft_model_variant_price_points
FOR EACH ROW
EXECUTE FUNCTION prevent_projected_aircraft_evidence_variant_move();
DROP TRIGGER IF EXISTS projected_aircraft_default_avionics_variant_move
  ON aircraft_model_variant_default_avionics;
CREATE TRIGGER projected_aircraft_default_avionics_variant_move
BEFORE UPDATE OF aircraft_model_variant_id
ON aircraft_model_variant_default_avionics
FOR EACH ROW
EXECUTE FUNCTION prevent_projected_aircraft_evidence_variant_move();

INSERT INTO schema_migration_contracts (
  migration_name, contract_version, contract_fingerprint, installed_at
) VALUES (
  '20260726_listing_aircraft_compatibility_projection',
  2,
  '0a182d5972d62be3d906395df8d08b741bc3e23d713badf7596b360048aa45ba',
  CURRENT_TIMESTAMP
)
ON CONFLICT (migration_name) DO UPDATE SET
  contract_version = EXCLUDED.contract_version,
  contract_fingerprint = EXCLUDED.contract_fingerprint,
  installed_at = EXCLUDED.installed_at;

COMMIT;
