-- Clean aircraft identity and reference-configuration catalog.
--
-- This additive migration creates the shadow/canonical target model without
-- copying or approving any legacy aircraft/configuration data. Apply to a
-- backup first.

BEGIN;

CREATE TABLE curation_evidence_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_url TEXT NOT NULL,
  resolved_url TEXT,
  source_title TEXT NOT NULL,
  publisher TEXT,
  source_domain TEXT NOT NULL,
  source_tier TEXT NOT NULL CHECK (source_tier IN (
    'manufacturer_primary', 'regulator_primary', 'recognized_secondary',
    'marketplace_observation'
  )),
  content_sha256 TEXT,
  retrieved_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (source_url, content_sha256)
);

CREATE INDEX idx_curation_evidence_sources_domain
  ON curation_evidence_sources (source_domain, source_tier);

CREATE TABLE curation_evidence_claims (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evidence_source_id BIGINT NOT NULL
    REFERENCES curation_evidence_sources(id) ON DELETE RESTRICT,
  claim_kind TEXT NOT NULL CHECK (claim_kind IN (
    'identity', 'alias', 'applicability', 'standard_equipment', 'price',
    'specification', 'package_composition', 'other'
  )),
  subject_text TEXT NOT NULL,
  predicate_text TEXT NOT NULL,
  object_text TEXT NOT NULL,
  quoted_evidence TEXT NOT NULL,
  citation_start BIGINT,
  citation_end BIGINT,
  validation_status TEXT NOT NULL DEFAULT 'captured'
    CHECK (validation_status IN ('captured', 'validated', 'rejected')),
  validated_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (length(trim(quoted_evidence)) > 0),
  CHECK (
    (citation_start IS NULL AND citation_end IS NULL)
    OR (
      citation_start IS NOT NULL AND citation_start >= 0
      AND citation_end IS NOT NULL AND citation_end > citation_start
    )
  ),
  CHECK (
    validation_status <> 'validated'
    OR validated_at IS NOT NULL
  )
);

CREATE INDEX idx_curation_evidence_claims_source
  ON curation_evidence_claims (evidence_source_id, claim_kind);

CREATE OR REPLACE FUNCTION preserve_curation_evidence_source()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'curation evidence sources are immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER curation_evidence_sources_immutable
BEFORE UPDATE OR DELETE ON curation_evidence_sources
FOR EACH ROW EXECUTE FUNCTION preserve_curation_evidence_source();

CREATE OR REPLACE FUNCTION validate_curation_evidence_claim_once()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'curation evidence claims are immutable';
  END IF;
  IF OLD.validation_status <> 'captured'
     OR NEW.validation_status NOT IN ('validated', 'rejected')
     OR NEW.evidence_source_id IS DISTINCT FROM OLD.evidence_source_id
     OR NEW.claim_kind IS DISTINCT FROM OLD.claim_kind
     OR NEW.subject_text IS DISTINCT FROM OLD.subject_text
     OR NEW.predicate_text IS DISTINCT FROM OLD.predicate_text
     OR NEW.object_text IS DISTINCT FROM OLD.object_text
     OR NEW.quoted_evidence IS DISTINCT FROM OLD.quoted_evidence
     OR NEW.citation_start IS DISTINCT FROM OLD.citation_start
     OR NEW.citation_end IS DISTINCT FROM OLD.citation_end THEN
    RAISE EXCEPTION 'curation evidence claims are append-only and validate once';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER curation_evidence_claims_immutable
BEFORE UPDATE OR DELETE ON curation_evidence_claims
FOR EACH ROW EXECUTE FUNCTION validate_curation_evidence_claim_once();

CREATE TABLE aircraft_curation_interaction_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL DEFAULT 'gemini',
  api_family TEXT NOT NULL CHECK (api_family IN ('interactions', 'generate_content')),
  api_version TEXT NOT NULL,
  model TEXT NOT NULL,
  purpose TEXT NOT NULL CHECK (purpose IN (
    'identity_evidence', 'identity_adjudication', 'profile_evidence',
    'profile_adjudication', 'collision_review', 'correction'
  )),
  provider_interaction_id TEXT,
  previous_interaction_id TEXT,
  prompt_version TEXT NOT NULL,
  schema_version TEXT NOT NULL,
  candidate_catalog_revision TEXT,
  store_requested BOOLEAN NOT NULL DEFAULT FALSE,
  request_json TEXT NOT NULL,
  response_json TEXT,
  run_status TEXT NOT NULL CHECK (run_status IN (
    'pending', 'completed', 'failed', 'cancelled', 'incomplete',
    'requires_action', 'budget_exceeded'
  )),
  input_tokens BIGINT CHECK (input_tokens IS NULL OR input_tokens >= 0),
  output_tokens BIGINT CHECK (output_tokens IS NULL OR output_tokens >= 0),
  search_query_count BIGINT NOT NULL DEFAULT 0 CHECK (search_query_count >= 0),
  latency_ms BIGINT CHECK (latency_ms IS NULL OR latency_ms >= 0),
  error_text TEXT,
  started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TEXT,
  UNIQUE (provider, provider_interaction_id),
  CHECK (run_status <> 'completed' OR completed_at IS NOT NULL)
);

CREATE INDEX idx_aircraft_curation_runs_status
  ON aircraft_curation_interaction_runs (purpose, run_status, started_at);

CREATE TABLE aircraft_identity_observations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_sale_listing_id BIGINT
    REFERENCES aircraft_sale_listings(id) ON DELETE SET NULL,
  source_url TEXT,
  observed_make TEXT,
  observed_family TEXT,
  observed_designation TEXT,
  observed_generation TEXT,
  observed_package TEXT,
  model_year BIGINT CHECK (model_year IS NULL OR model_year BETWEEN 1900 AND 2200),
  serial_number TEXT,
  registration_number TEXT,
  market_code TEXT,
  exact_source_evidence TEXT NOT NULL,
  observation_sha256 TEXT NOT NULL UNIQUE,
  legacy_hint_json TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (length(trim(exact_source_evidence)) > 0)
);

CREATE INDEX idx_aircraft_identity_observations_listing
  ON aircraft_identity_observations (aircraft_sale_listing_id);

CREATE TABLE aircraft_identity_resolution_cases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_id BIGINT NOT NULL
    REFERENCES aircraft_identity_observations(id) ON DELETE CASCADE,
  resolution_scope TEXT NOT NULL CHECK (resolution_scope IN (
    'make', 'family', 'designation', 'generation', 'package',
    'engine_model', 'propeller_model',
    'reference_configuration', 'reference_profile'
  )),
  job_fingerprint TEXT NOT NULL UNIQUE,
  catalog_revision TEXT NOT NULL,
  case_status TEXT NOT NULL DEFAULT 'open'
    CHECK (case_status IN ('open', 'adjudicating', 'resolved', 'blocked')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_aircraft_identity_cases_observation
  ON aircraft_identity_resolution_cases (observation_id, resolution_scope);

CREATE TABLE aircraft_identity_resolution_candidates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resolution_case_id BIGINT NOT NULL
    REFERENCES aircraft_identity_resolution_cases(id) ON DELETE CASCADE,
  candidate_kind TEXT NOT NULL CHECK (candidate_kind IN (
    'make', 'family', 'designation', 'generation', 'package',
    'engine_model', 'propeller_model',
    'reference_configuration', 'new_entity'
  )),
  candidate_entity_id BIGINT,
  rank BIGINT NOT NULL CHECK (rank >= 1),
  retrieval_method TEXT NOT NULL,
  retrieval_score DOUBLE PRECISION,
  candidate_snapshot_json TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (resolution_case_id, candidate_kind, rank),
  CHECK (
    (candidate_kind = 'new_entity' AND candidate_entity_id IS NULL)
    OR (candidate_kind <> 'new_entity' AND candidate_entity_id IS NOT NULL)
  )
);

CREATE TABLE aircraft_identity_decisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resolution_case_id BIGINT NOT NULL
    REFERENCES aircraft_identity_resolution_cases(id) ON DELETE RESTRICT,
  interaction_run_id BIGINT
    REFERENCES aircraft_curation_interaction_runs(id) ON DELETE RESTRICT,
  entity_kind TEXT NOT NULL CHECK (entity_kind IN (
    'make', 'family', 'designation', 'alias', 'identifier', 'generation',
    'generation_designation', 'package', 'package_applicability',
    'engine_model', 'propeller_model',
    'reference_configuration', 'serial_scheme', 'feature_definition',
    'reference_profile'
  )),
  decision_action TEXT NOT NULL CHECK (decision_action IN (
    'match_existing', 'approve_new', 'ambiguous', 'not_an_entity', 'reject'
  )),
  decision_status TEXT NOT NULL CHECK (decision_status IN (
    'approved', 'rejected', 'ambiguous'
  )),
  selected_entity_id BIGINT,
  decision_payload_json TEXT NOT NULL,
  deterministic_validation_json TEXT NOT NULL,
  deterministic_validation_passed BOOLEAN NOT NULL,
  rationale TEXT NOT NULL,
  decided_by_user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
  decided_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (
    (decision_status = 'approved'
      AND decision_action IN ('match_existing', 'approve_new')
      AND deterministic_validation_passed)
    OR (decision_status = 'rejected'
      AND decision_action IN ('not_an_entity', 'reject'))
    OR (decision_status = 'ambiguous' AND decision_action = 'ambiguous')
  ),
  CHECK (
    (decision_action = 'match_existing' AND selected_entity_id IS NOT NULL)
    OR (decision_action <> 'match_existing' AND selected_entity_id IS NULL)
  )
);

CREATE INDEX idx_aircraft_identity_decisions_case
  ON aircraft_identity_decisions (resolution_case_id, decision_status);

CREATE TABLE aircraft_identity_decision_claims (
  decision_id BIGINT NOT NULL
    REFERENCES aircraft_identity_decisions(id) ON DELETE CASCADE,
  evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  evidence_role TEXT NOT NULL CHECK (evidence_role IN (
    'identity', 'difference', 'applicability', 'standard_equipment',
    'price', 'specification'
  )),
  PRIMARY KEY (decision_id, evidence_claim_id, evidence_role)
);

CREATE TABLE aircraft_reference_profile_proposals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resolution_case_id BIGINT NOT NULL
    REFERENCES aircraft_identity_resolution_cases(id) ON DELETE CASCADE,
  interaction_run_id BIGINT
    REFERENCES aircraft_curation_interaction_runs(id) ON DELETE RESTRICT,
  proposed_identity_json TEXT NOT NULL,
  proposed_profile_json TEXT NOT NULL,
  deterministic_validation_json TEXT NOT NULL,
  validation_status TEXT NOT NULL CHECK (validation_status IN (
    'pending', 'valid', 'invalid', 'needs_review'
  )),
  catalog_revision TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Engine and propeller identities used by reference profiles live in a clean,
-- approved-by-construction catalog. The contaminated legacy model tables are
-- deliberately not copied into this trust boundary.
CREATE TABLE aircraft_engine_catalog_models (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manufacturer_name TEXT NOT NULL,
  normalized_manufacturer_name TEXT NOT NULL,
  model_name TEXT NOT NULL,
  normalized_model_name TEXT NOT NULL,
  identifier_authority TEXT NOT NULL,
  normalized_identifier_authority TEXT NOT NULL,
  identifier_kind TEXT NOT NULL CHECK (identifier_kind IN (
    'manufacturer_model_code', 'regulator_model_designation',
    'manufacturer_part_number'
  )),
  authoritative_identifier TEXT NOT NULL,
  normalized_authoritative_identifier TEXT NOT NULL,
  catalog_status TEXT NOT NULL DEFAULT 'approved'
    CHECK (catalog_status = 'approved'),
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  identity_evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (length(trim(manufacturer_name)) > 0),
  CHECK (length(trim(normalized_manufacturer_name)) > 0),
  CHECK (length(trim(model_name)) > 0),
  CHECK (length(trim(normalized_model_name)) > 0),
  CHECK (length(trim(identifier_authority)) > 0),
  CHECK (length(trim(normalized_identifier_authority)) > 0),
  CHECK (length(trim(authoritative_identifier)) > 0),
  CHECK (length(trim(normalized_authoritative_identifier)) > 0),
  UNIQUE (normalized_manufacturer_name, normalized_model_name),
  UNIQUE (
    normalized_identifier_authority, identifier_kind,
    normalized_authoritative_identifier
  )
);

CREATE TABLE aircraft_propeller_catalog_models (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manufacturer_name TEXT NOT NULL,
  normalized_manufacturer_name TEXT NOT NULL,
  model_name TEXT NOT NULL,
  normalized_model_name TEXT NOT NULL,
  identifier_authority TEXT NOT NULL,
  normalized_identifier_authority TEXT NOT NULL,
  identifier_kind TEXT NOT NULL CHECK (identifier_kind IN (
    'manufacturer_model_code', 'regulator_model_designation',
    'manufacturer_part_number'
  )),
  authoritative_identifier TEXT NOT NULL,
  normalized_authoritative_identifier TEXT NOT NULL,
  catalog_status TEXT NOT NULL DEFAULT 'approved'
    CHECK (catalog_status = 'approved'),
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  identity_evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (length(trim(manufacturer_name)) > 0),
  CHECK (length(trim(normalized_manufacturer_name)) > 0),
  CHECK (length(trim(model_name)) > 0),
  CHECK (length(trim(normalized_model_name)) > 0),
  CHECK (length(trim(identifier_authority)) > 0),
  CHECK (length(trim(normalized_identifier_authority)) > 0),
  CHECK (length(trim(authoritative_identifier)) > 0),
  CHECK (length(trim(normalized_authoritative_identifier)) > 0),
  UNIQUE (normalized_manufacturer_name, normalized_model_name),
  UNIQUE (
    normalized_identifier_authority, identifier_kind,
    normalized_authoritative_identifier
  )
);

CREATE TABLE aircraft_markets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  parent_market_id BIGINT REFERENCES aircraft_markets(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (length(trim(code)) > 0),
  CHECK (parent_market_id IS NULL OR parent_market_id <> id)
);

INSERT INTO aircraft_markets (code, name)
VALUES ('GLOBAL', 'Global')
ON CONFLICT (code) DO NOTHING;

CREATE TABLE aircraft_makes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL UNIQUE,
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (length(trim(name)) > 0),
  CHECK (length(trim(normalized_name)) > 0)
);

CREATE TABLE aircraft_model_families (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_make_id BIGINT NOT NULL REFERENCES aircraft_makes(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_make_id, normalized_name),
  UNIQUE (id, aircraft_make_id),
  CHECK (length(trim(name)) > 0),
  CHECK (length(trim(normalized_name)) > 0)
);

CREATE TABLE aircraft_designations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_model_family_id BIGINT NOT NULL
    REFERENCES aircraft_model_families(id) ON DELETE RESTRICT,
  official_designation TEXT NOT NULL,
  normalized_official_designation TEXT NOT NULL,
  display_name TEXT NOT NULL,
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_model_family_id, normalized_official_designation),
  UNIQUE (id, aircraft_model_family_id),
  CHECK (length(trim(official_designation)) > 0),
  CHECK (length(trim(normalized_official_designation)) > 0),
  CHECK (length(trim(display_name)) > 0)
);

CREATE TABLE aircraft_make_aliases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_make_id BIGINT NOT NULL REFERENCES aircraft_makes(id) ON DELETE CASCADE,
  alias TEXT NOT NULL,
  normalized_alias TEXT NOT NULL,
  valid_from_model_year BIGINT,
  valid_to_model_year BIGINT,
  aircraft_market_id BIGINT REFERENCES aircraft_markets(id) ON DELETE RESTRICT,
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_make_id, normalized_alias, aircraft_market_id),
  CHECK (valid_from_model_year IS NULL OR valid_from_model_year BETWEEN 1900 AND 2200),
  CHECK (valid_to_model_year IS NULL OR valid_to_model_year BETWEEN 1900 AND 2200),
  CHECK (
    valid_from_model_year IS NULL OR valid_to_model_year IS NULL
    OR valid_to_model_year >= valid_from_model_year
  )
);

CREATE TABLE aircraft_family_aliases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_model_family_id BIGINT NOT NULL
    REFERENCES aircraft_model_families(id) ON DELETE CASCADE,
  alias TEXT NOT NULL,
  normalized_alias TEXT NOT NULL,
  valid_from_model_year BIGINT,
  valid_to_model_year BIGINT,
  aircraft_market_id BIGINT REFERENCES aircraft_markets(id) ON DELETE RESTRICT,
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_model_family_id, normalized_alias, aircraft_market_id),
  CHECK (
    valid_from_model_year IS NULL OR valid_to_model_year IS NULL
    OR valid_to_model_year >= valid_from_model_year
  )
);

CREATE TABLE aircraft_designation_aliases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_designation_id BIGINT NOT NULL
    REFERENCES aircraft_designations(id) ON DELETE CASCADE,
  alias TEXT NOT NULL,
  normalized_alias TEXT NOT NULL,
  valid_from_model_year BIGINT,
  valid_to_model_year BIGINT,
  aircraft_market_id BIGINT REFERENCES aircraft_markets(id) ON DELETE RESTRICT,
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_designation_id, normalized_alias, aircraft_market_id),
  CHECK (
    valid_from_model_year IS NULL OR valid_to_model_year IS NULL
    OR valid_to_model_year >= valid_from_model_year
  )
);

CREATE TABLE aircraft_designation_identifiers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_designation_id BIGINT NOT NULL
    REFERENCES aircraft_designations(id) ON DELETE CASCADE,
  authority TEXT NOT NULL,
  identifier_kind TEXT NOT NULL CHECK (identifier_kind IN (
    'manufacturer_model_code', 'type_certificate_model',
    'type_certificate_number', 'icao_type_designator', 'other_authoritative'
  )),
  identifier_value TEXT NOT NULL,
  normalized_identifier_value TEXT NOT NULL,
  valid_from_model_year BIGINT,
  valid_to_model_year BIGINT,
  aircraft_market_id BIGINT REFERENCES aircraft_markets(id) ON DELETE RESTRICT,
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (
    aircraft_designation_id, authority, identifier_kind,
    normalized_identifier_value, aircraft_market_id
  ),
  CHECK (length(trim(authority)) > 0),
  CHECK (length(trim(normalized_identifier_value)) > 0),
  CHECK (
    valid_from_model_year IS NULL OR valid_to_model_year IS NULL
    OR valid_to_model_year >= valid_from_model_year
  )
);

CREATE UNIQUE INDEX idx_aircraft_make_aliases_scope
  ON aircraft_make_aliases (
    aircraft_make_id, normalized_alias, COALESCE(aircraft_market_id, 0)
  );
CREATE UNIQUE INDEX idx_aircraft_family_aliases_scope
  ON aircraft_family_aliases (
    aircraft_model_family_id, normalized_alias, COALESCE(aircraft_market_id, 0)
  );
CREATE UNIQUE INDEX idx_aircraft_designation_aliases_scope
  ON aircraft_designation_aliases (
    aircraft_designation_id, normalized_alias, COALESCE(aircraft_market_id, 0)
  );
CREATE UNIQUE INDEX idx_aircraft_designation_identifiers_scope
  ON aircraft_designation_identifiers (
    aircraft_designation_id, authority, identifier_kind,
    normalized_identifier_value, COALESCE(aircraft_market_id, 0)
  );

CREATE TABLE aircraft_generations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_model_family_id BIGINT NOT NULL
    REFERENCES aircraft_model_families(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  ordinal BIGINT CHECK (ordinal IS NULL OR ordinal >= 0),
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_model_family_id, normalized_name),
  UNIQUE (id, aircraft_model_family_id)
);

CREATE TABLE aircraft_generation_designations (
  aircraft_generation_id BIGINT NOT NULL
    REFERENCES aircraft_generations(id) ON DELETE CASCADE,
  aircraft_designation_id BIGINT NOT NULL
    REFERENCES aircraft_designations(id) ON DELETE CASCADE,
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (aircraft_generation_id, aircraft_designation_id)
);

CREATE TABLE aircraft_factory_packages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_model_family_id BIGINT NOT NULL
    REFERENCES aircraft_model_families(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  package_kind TEXT NOT NULL CHECK (package_kind IN (
    'trim_tier', 'option_bundle', 'special_edition'
  )),
  exclusivity_group TEXT,
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_model_family_id, normalized_name),
  UNIQUE (id, aircraft_model_family_id),
  CHECK (package_kind <> 'trim_tier' OR length(trim(exclusivity_group)) > 0)
);

CREATE TABLE aircraft_package_applicability (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_factory_package_id BIGINT NOT NULL
    REFERENCES aircraft_factory_packages(id) ON DELETE CASCADE,
  aircraft_designation_id BIGINT NOT NULL
    REFERENCES aircraft_designations(id) ON DELETE CASCADE,
  aircraft_generation_id BIGINT
    REFERENCES aircraft_generations(id) ON DELETE CASCADE,
  valid_from_model_year BIGINT,
  valid_to_model_year BIGINT,
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (
    aircraft_factory_package_id, aircraft_designation_id,
    aircraft_generation_id, valid_from_model_year, valid_to_model_year
  ),
  CHECK (
    valid_from_model_year IS NULL OR valid_to_model_year IS NULL
    OR valid_to_model_year >= valid_from_model_year
  )
);

CREATE UNIQUE INDEX idx_aircraft_package_applicability_scope
  ON aircraft_package_applicability (
    aircraft_factory_package_id, aircraft_designation_id,
    COALESCE(aircraft_generation_id, 0),
    COALESCE(valid_from_model_year, 0), COALESCE(valid_to_model_year, 0)
  );

CREATE TABLE aircraft_reference_configurations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_model_family_id BIGINT NOT NULL,
  aircraft_designation_id BIGINT NOT NULL,
  aircraft_generation_id BIGINT,
  tier_package_id BIGINT,
  configuration_kind TEXT NOT NULL CHECK (configuration_kind IN ('base', 'tier')),
  display_name TEXT NOT NULL,
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (aircraft_designation_id, aircraft_model_family_id)
    REFERENCES aircraft_designations(id, aircraft_model_family_id) ON DELETE RESTRICT,
  FOREIGN KEY (aircraft_generation_id, aircraft_model_family_id)
    REFERENCES aircraft_generations(id, aircraft_model_family_id) ON DELETE RESTRICT,
  FOREIGN KEY (tier_package_id, aircraft_model_family_id)
    REFERENCES aircraft_factory_packages(id, aircraft_model_family_id) ON DELETE RESTRICT,
  CHECK (
    (configuration_kind = 'base' AND tier_package_id IS NULL)
    OR (configuration_kind = 'tier' AND tier_package_id IS NOT NULL)
  )
);

CREATE UNIQUE INDEX idx_aircraft_reference_config_base_no_generation
  ON aircraft_reference_configurations (aircraft_designation_id)
  WHERE configuration_kind = 'base' AND aircraft_generation_id IS NULL;
CREATE UNIQUE INDEX idx_aircraft_reference_config_base_generation
  ON aircraft_reference_configurations (aircraft_designation_id, aircraft_generation_id)
  WHERE configuration_kind = 'base' AND aircraft_generation_id IS NOT NULL;
CREATE UNIQUE INDEX idx_aircraft_reference_config_tier_no_generation
  ON aircraft_reference_configurations (aircraft_designation_id, tier_package_id)
  WHERE configuration_kind = 'tier' AND aircraft_generation_id IS NULL;
CREATE UNIQUE INDEX idx_aircraft_reference_config_tier_generation
  ON aircraft_reference_configurations (
    aircraft_designation_id, aircraft_generation_id, tier_package_id
  )
  WHERE configuration_kind = 'tier' AND aircraft_generation_id IS NOT NULL;

CREATE TABLE aircraft_serial_number_schemes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_make_id BIGINT NOT NULL REFERENCES aircraft_makes(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  normalization_version TEXT NOT NULL,
  validation_pattern TEXT NOT NULL,
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_make_id, name, normalization_version)
);

CREATE TABLE aircraft_reference_configuration_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_reference_configuration_id BIGINT NOT NULL
    REFERENCES aircraft_reference_configurations(id) ON DELETE RESTRICT,
  model_year BIGINT NOT NULL CHECK (model_year BETWEEN 1900 AND 2200),
  revision BIGINT NOT NULL CHECK (revision >= 1),
  supersedes_version_id BIGINT
    REFERENCES aircraft_reference_configuration_versions(id) ON DELETE RESTRICT,
  publication_state TEXT NOT NULL DEFAULT 'building'
    CHECK (publication_state IN ('building', 'published', 'superseded')),
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  published_at TEXT,
  superseded_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_reference_configuration_id, model_year, revision),
  UNIQUE (supersedes_version_id),
  CHECK (supersedes_version_id IS NULL OR supersedes_version_id <> id),
  CHECK (
    (publication_state = 'building' AND published_at IS NULL AND superseded_at IS NULL)
    OR (publication_state = 'published' AND published_at IS NOT NULL AND superseded_at IS NULL)
    OR (publication_state = 'superseded' AND published_at IS NOT NULL AND superseded_at IS NOT NULL)
  )
);

CREATE INDEX idx_aircraft_reference_versions_lookup
  ON aircraft_reference_configuration_versions (
    aircraft_reference_configuration_id, model_year, publication_state, revision
  );

CREATE TABLE aircraft_reference_applicability_scopes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_reference_configuration_version_id BIGINT NOT NULL
    REFERENCES aircraft_reference_configuration_versions(id) ON DELETE CASCADE,
  aircraft_market_id BIGINT NOT NULL REFERENCES aircraft_markets(id) ON DELETE RESTRICT,
  applies_to_all_serials BOOLEAN NOT NULL DEFAULT TRUE,
  aircraft_serial_number_scheme_id BIGINT
    REFERENCES aircraft_serial_number_schemes(id) ON DELETE RESTRICT,
  serial_prefix TEXT,
  serial_from_display TEXT,
  serial_to_display TEXT,
  serial_from_sort_key TEXT,
  serial_to_sort_key TEXT,
  evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (
    (applies_to_all_serials
      AND aircraft_serial_number_scheme_id IS NULL
      AND serial_prefix IS NULL
      AND serial_from_display IS NULL AND serial_to_display IS NULL
      AND serial_from_sort_key IS NULL AND serial_to_sort_key IS NULL)
    OR
    (NOT applies_to_all_serials
      AND aircraft_serial_number_scheme_id IS NOT NULL
      AND serial_from_display IS NOT NULL AND serial_to_display IS NOT NULL
      AND serial_from_sort_key IS NOT NULL AND serial_to_sort_key IS NOT NULL
      AND serial_from_sort_key <= serial_to_sort_key)
  ),
  UNIQUE (
    aircraft_reference_configuration_version_id, aircraft_market_id,
    aircraft_serial_number_scheme_id, serial_prefix,
    serial_from_sort_key, serial_to_sort_key
  )
);

CREATE INDEX idx_aircraft_reference_scope_market
  ON aircraft_reference_applicability_scopes (
    aircraft_market_id, aircraft_serial_number_scheme_id,
    serial_from_sort_key, serial_to_sort_key
  );

CREATE TABLE aircraft_reference_prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_reference_configuration_version_id BIGINT NOT NULL
    REFERENCES aircraft_reference_configuration_versions(id) ON DELETE CASCADE,
  price_kind TEXT NOT NULL CHECK (price_kind IN (
    'base_msrp', 'equipped_msrp', 'tier_increment', 'other_factory_price'
  )),
  amount DOUBLE PRECISION NOT NULL CHECK (amount > 0),
  currency TEXT NOT NULL CHECK (length(currency) = 3 AND currency = upper(currency)),
  price_reference_year BIGINT NOT NULL CHECK (price_reference_year BETWEEN 1900 AND 2200),
  evidence_kind TEXT NOT NULL CHECK (evidence_kind IN (
    'direct_model_year', 'direct_other_year', 'interpolated', 'inferred'
  )),
  evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_reference_configuration_version_id, price_kind, currency)
);

CREATE TABLE aircraft_reference_avionics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_reference_configuration_version_id BIGINT NOT NULL
    REFERENCES aircraft_reference_configuration_versions(id) ON DELETE CASCADE,
  avionics_model_id BIGINT NOT NULL REFERENCES avionics_models(id) ON DELETE RESTRICT,
  quantity BIGINT NOT NULL CHECK (quantity > 0),
  equipment_role TEXT NOT NULL CHECK (equipment_role IN ('standard', 'included_in_tier')),
  evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_reference_configuration_version_id, avionics_model_id)
);

CREATE TABLE aircraft_reference_engines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_reference_configuration_version_id BIGINT NOT NULL
    REFERENCES aircraft_reference_configuration_versions(id) ON DELETE CASCADE,
  aircraft_engine_catalog_model_id BIGINT NOT NULL
    REFERENCES aircraft_engine_catalog_models(id) ON DELETE RESTRICT,
  quantity BIGINT NOT NULL CHECK (quantity > 0),
  equipment_role TEXT NOT NULL CHECK (equipment_role IN ('standard', 'included_in_tier')),
  evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (
    aircraft_reference_configuration_version_id,
    aircraft_engine_catalog_model_id
  )
);

CREATE TABLE aircraft_reference_propellers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_reference_configuration_version_id BIGINT NOT NULL
    REFERENCES aircraft_reference_configuration_versions(id) ON DELETE CASCADE,
  aircraft_propeller_catalog_model_id BIGINT NOT NULL
    REFERENCES aircraft_propeller_catalog_models(id) ON DELETE RESTRICT,
  quantity BIGINT NOT NULL CHECK (quantity > 0),
  equipment_role TEXT NOT NULL CHECK (equipment_role IN ('standard', 'included_in_tier')),
  evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (
    aircraft_reference_configuration_version_id,
    aircraft_propeller_catalog_model_id
  )
);

CREATE TABLE aircraft_feature_definitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_key TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  value_type TEXT NOT NULL CHECK (value_type IN ('boolean', 'number', 'text')),
  canonical_unit TEXT,
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK ((value_type = 'number') OR canonical_unit IS NULL)
);

CREATE TABLE aircraft_reference_features (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_reference_configuration_version_id BIGINT NOT NULL
    REFERENCES aircraft_reference_configuration_versions(id) ON DELETE CASCADE,
  aircraft_feature_definition_id BIGINT NOT NULL
    REFERENCES aircraft_feature_definitions(id) ON DELETE RESTRICT,
  boolean_value BOOLEAN,
  number_value DOUBLE PRECISION,
  text_value TEXT,
  evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (
    aircraft_reference_configuration_version_id,
    aircraft_feature_definition_id
  ),
  CHECK (
    num_nonnulls(boolean_value, number_value, text_value) = 1
  )
);

-- Every canonical aircraft identity/configuration row must be backed by one
-- approved decision. Identity-defining facts additionally require a validated
-- manufacturer or regulator claim.
CREATE OR REPLACE FUNCTION require_aircraft_catalog_approval()
RETURNS TRIGGER AS $$
DECLARE
  expected_kind TEXT;
  require_claim BOOLEAN := TRUE;
  require_primary BOOLEAN := FALSE;
BEGIN
  CASE TG_TABLE_NAME
    WHEN 'aircraft_engine_catalog_models' THEN expected_kind := 'engine_model'; require_primary := TRUE;
    WHEN 'aircraft_propeller_catalog_models' THEN expected_kind := 'propeller_model'; require_primary := TRUE;
    WHEN 'aircraft_makes' THEN expected_kind := 'make'; require_primary := TRUE;
    WHEN 'aircraft_model_families' THEN expected_kind := 'family'; require_primary := TRUE;
    WHEN 'aircraft_designations' THEN expected_kind := 'designation'; require_primary := TRUE;
    WHEN 'aircraft_make_aliases' THEN expected_kind := 'alias';
    WHEN 'aircraft_family_aliases' THEN expected_kind := 'alias';
    WHEN 'aircraft_designation_aliases' THEN expected_kind := 'alias';
    WHEN 'aircraft_designation_identifiers' THEN expected_kind := 'identifier'; require_primary := TRUE;
    WHEN 'aircraft_generations' THEN expected_kind := 'generation'; require_primary := TRUE;
    WHEN 'aircraft_generation_designations' THEN expected_kind := 'generation_designation'; require_claim := FALSE;
    WHEN 'aircraft_factory_packages' THEN expected_kind := 'package'; require_primary := TRUE;
    WHEN 'aircraft_package_applicability' THEN expected_kind := 'package_applicability'; require_claim := FALSE;
    WHEN 'aircraft_reference_configurations' THEN expected_kind := 'reference_configuration'; require_primary := TRUE;
    WHEN 'aircraft_serial_number_schemes' THEN expected_kind := 'serial_scheme';
    WHEN 'aircraft_feature_definitions' THEN expected_kind := 'feature_definition'; require_claim := FALSE;
    WHEN 'aircraft_reference_configuration_versions' THEN expected_kind := 'reference_profile'; require_primary := TRUE;
    ELSE RAISE EXCEPTION 'unsupported canonical aircraft table %', TG_TABLE_NAME;
  END CASE;

  IF NOT EXISTS (
    SELECT 1
    FROM aircraft_identity_decisions decision
    WHERE decision.id = NEW.approval_decision_id
      AND decision.decision_status = 'approved'
      AND decision.decision_action = 'approve_new'
      AND decision.entity_kind = expected_kind
  ) THEN
    RAISE EXCEPTION '% requires an approved % decision', TG_TABLE_NAME, expected_kind;
  END IF;

  IF require_claim AND NOT EXISTS (
    SELECT 1
    FROM aircraft_identity_decision_claims decision_claim
    JOIN curation_evidence_claims claim
      ON claim.id = decision_claim.evidence_claim_id
    JOIN curation_evidence_sources source
      ON source.id = claim.evidence_source_id
    WHERE decision_claim.decision_id = NEW.approval_decision_id
      AND claim.validation_status = 'validated'
      AND (
        NOT require_primary
        OR source.source_tier IN ('manufacturer_primary', 'regulator_primary')
      )
  ) THEN
    RAISE EXCEPTION '% requires validated evidence for its approved decision', TG_TABLE_NAME;
  END IF;

  IF TG_TABLE_NAME IN (
    'aircraft_engine_catalog_models', 'aircraft_propeller_catalog_models'
  ) AND NOT EXISTS (
    SELECT 1
    FROM aircraft_identity_decision_claims decision_claim
    JOIN curation_evidence_claims claim
      ON claim.id = decision_claim.evidence_claim_id
    JOIN curation_evidence_sources source
      ON source.id = claim.evidence_source_id
    WHERE decision_claim.decision_id = NEW.approval_decision_id
      AND decision_claim.evidence_claim_id = NEW.identity_evidence_claim_id
      AND decision_claim.evidence_role IN ('identity', 'specification')
      AND claim.claim_kind IN ('identity', 'specification')
      AND claim.validation_status = 'validated'
      AND source.source_tier IN ('manufacturer_primary', 'regulator_primary')
  ) THEN
    RAISE EXCEPTION '% requires its exact primary-source identifier claim', TG_TABLE_NAME;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER aircraft_engine_catalog_models_require_approval
BEFORE INSERT ON aircraft_engine_catalog_models
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();
CREATE TRIGGER aircraft_propeller_catalog_models_require_approval
BEFORE INSERT ON aircraft_propeller_catalog_models
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();

CREATE TRIGGER aircraft_makes_require_approval
BEFORE INSERT ON aircraft_makes
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();
CREATE TRIGGER aircraft_families_require_approval
BEFORE INSERT ON aircraft_model_families
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();
CREATE TRIGGER aircraft_designations_require_approval
BEFORE INSERT ON aircraft_designations
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();
CREATE TRIGGER aircraft_make_aliases_require_approval
BEFORE INSERT ON aircraft_make_aliases
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();
CREATE TRIGGER aircraft_family_aliases_require_approval
BEFORE INSERT ON aircraft_family_aliases
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();
CREATE TRIGGER aircraft_designation_aliases_require_approval
BEFORE INSERT ON aircraft_designation_aliases
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();
CREATE TRIGGER aircraft_identifiers_require_approval
BEFORE INSERT ON aircraft_designation_identifiers
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();
CREATE TRIGGER aircraft_generations_require_approval
BEFORE INSERT ON aircraft_generations
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();
CREATE TRIGGER aircraft_generation_designations_require_approval
BEFORE INSERT ON aircraft_generation_designations
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();
CREATE TRIGGER aircraft_packages_require_approval
BEFORE INSERT ON aircraft_factory_packages
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();
CREATE TRIGGER aircraft_package_applicability_require_approval
BEFORE INSERT ON aircraft_package_applicability
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();
CREATE TRIGGER aircraft_reference_configurations_require_approval
BEFORE INSERT ON aircraft_reference_configurations
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();
CREATE TRIGGER aircraft_serial_schemes_require_approval
BEFORE INSERT ON aircraft_serial_number_schemes
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();
CREATE TRIGGER aircraft_feature_definitions_require_approval
BEFORE INSERT ON aircraft_feature_definitions
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();
CREATE TRIGGER aircraft_reference_versions_require_approval
BEFORE INSERT ON aircraft_reference_configuration_versions
FOR EACH ROW EXECUTE FUNCTION require_aircraft_catalog_approval();

CREATE OR REPLACE FUNCTION preserve_approved_component_catalog_model()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'approved component catalog models are immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER aircraft_engine_catalog_models_immutable
BEFORE UPDATE OR DELETE ON aircraft_engine_catalog_models
FOR EACH ROW EXECUTE FUNCTION preserve_approved_component_catalog_model();
CREATE TRIGGER aircraft_propeller_catalog_models_immutable
BEFORE UPDATE OR DELETE ON aircraft_propeller_catalog_models
FOR EACH ROW EXECUTE FUNCTION preserve_approved_component_catalog_model();

CREATE OR REPLACE FUNCTION validate_aircraft_catalog_relationship()
RETURNS TRIGGER AS $$
DECLARE
  designation_family_id BIGINT;
  generation_family_id BIGINT;
  package_family_id BIGINT;
BEGIN
  IF TG_TABLE_NAME = 'aircraft_generation_designations' THEN
    SELECT aircraft_model_family_id INTO generation_family_id
    FROM aircraft_generations WHERE id = NEW.aircraft_generation_id;
    SELECT aircraft_model_family_id INTO designation_family_id
    FROM aircraft_designations WHERE id = NEW.aircraft_designation_id;
    IF generation_family_id IS DISTINCT FROM designation_family_id THEN
      RAISE EXCEPTION 'generation and designation must belong to one family';
    END IF;
  ELSIF TG_TABLE_NAME = 'aircraft_package_applicability' THEN
    SELECT aircraft_model_family_id INTO package_family_id
    FROM aircraft_factory_packages WHERE id = NEW.aircraft_factory_package_id;
    SELECT aircraft_model_family_id INTO designation_family_id
    FROM aircraft_designations WHERE id = NEW.aircraft_designation_id;
    IF NEW.aircraft_generation_id IS NOT NULL THEN
      SELECT aircraft_model_family_id INTO generation_family_id
      FROM aircraft_generations WHERE id = NEW.aircraft_generation_id;
    END IF;
    IF package_family_id IS DISTINCT FROM designation_family_id
       OR (NEW.aircraft_generation_id IS NOT NULL
           AND generation_family_id IS DISTINCT FROM designation_family_id) THEN
      RAISE EXCEPTION 'package applicability dimensions must belong to one family';
    END IF;
  ELSIF TG_TABLE_NAME = 'aircraft_reference_configurations' THEN
    IF NEW.aircraft_generation_id IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM aircraft_generation_designations link
      WHERE link.aircraft_generation_id = NEW.aircraft_generation_id
        AND link.aircraft_designation_id = NEW.aircraft_designation_id
    ) THEN
      RAISE EXCEPTION 'reference configuration generation is not applicable to designation';
    END IF;
    IF NEW.tier_package_id IS NOT NULL AND NOT EXISTS (
      SELECT 1
      FROM aircraft_factory_packages package
      JOIN aircraft_package_applicability applicability
        ON applicability.aircraft_factory_package_id = package.id
      WHERE package.id = NEW.tier_package_id
        AND package.package_kind = 'trim_tier'
        AND applicability.aircraft_designation_id = NEW.aircraft_designation_id
        AND (
          applicability.aircraft_generation_id IS NULL
          OR applicability.aircraft_generation_id = NEW.aircraft_generation_id
        )
    ) THEN
      RAISE EXCEPTION 'reference configuration tier is not applicable to designation/generation';
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER aircraft_generation_designations_relationship
BEFORE INSERT ON aircraft_generation_designations
FOR EACH ROW EXECUTE FUNCTION validate_aircraft_catalog_relationship();
CREATE TRIGGER aircraft_package_applicability_relationship
BEFORE INSERT ON aircraft_package_applicability
FOR EACH ROW EXECUTE FUNCTION validate_aircraft_catalog_relationship();
CREATE TRIGGER aircraft_reference_configurations_relationship
BEFORE INSERT ON aircraft_reference_configurations
FOR EACH ROW EXECUTE FUNCTION validate_aircraft_catalog_relationship();

CREATE OR REPLACE FUNCTION validate_aircraft_reference_version_insert()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.publication_state <> 'building' THEN
    RAISE EXCEPTION 'reference profile versions must be assembled in building state';
  END IF;
  IF NEW.supersedes_version_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM aircraft_reference_configuration_versions previous
    WHERE previous.id = NEW.supersedes_version_id
      AND previous.aircraft_reference_configuration_id = NEW.aircraft_reference_configuration_id
      AND previous.model_year = NEW.model_year
      AND previous.publication_state = 'published'
  ) THEN
    RAISE EXCEPTION 'reference profile predecessor must be a published version of the same configuration/year';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER aircraft_reference_versions_validate_insert
BEFORE INSERT ON aircraft_reference_configuration_versions
FOR EACH ROW EXECUTE FUNCTION validate_aircraft_reference_version_insert();

CREATE OR REPLACE FUNCTION validate_aircraft_reference_child_insert()
RETURNS TRIGGER AS $$
DECLARE
  parent_state TEXT;
  parent_model_year BIGINT;
  expected_value_type TEXT;
BEGIN
  SELECT publication_state, model_year INTO parent_state, parent_model_year
  FROM aircraft_reference_configuration_versions
  WHERE id = NEW.aircraft_reference_configuration_version_id;
  IF parent_state IS DISTINCT FROM 'building' THEN
    RAISE EXCEPTION 'reference profile children require a building version';
  END IF;

  IF TG_TABLE_NAME = 'aircraft_reference_prices'
     AND NEW.evidence_kind = 'direct_model_year'
     AND NEW.price_reference_year <> parent_model_year THEN
    RAISE EXCEPTION 'direct model-year price must use the profile model year';
  ELSIF TG_TABLE_NAME = 'aircraft_reference_avionics' AND NOT EXISTS (
    SELECT 1 FROM avionics_models model
    WHERE model.id = NEW.avionics_model_id AND model.catalog_status = 'approved'
  ) THEN
    RAISE EXCEPTION 'reference avionics requires an approved catalog product';
  ELSIF TG_TABLE_NAME = 'aircraft_reference_engines' AND NOT EXISTS (
    SELECT 1 FROM aircraft_engine_catalog_models model
    WHERE model.id = NEW.aircraft_engine_catalog_model_id
      AND model.catalog_status = 'approved'
  ) THEN
    RAISE EXCEPTION 'reference engine requires an approved catalog model';
  ELSIF TG_TABLE_NAME = 'aircraft_reference_propellers' AND NOT EXISTS (
    SELECT 1 FROM aircraft_propeller_catalog_models model
    WHERE model.id = NEW.aircraft_propeller_catalog_model_id
      AND model.catalog_status = 'approved'
  ) THEN
    RAISE EXCEPTION 'reference propeller requires an approved catalog model';
  ELSIF TG_TABLE_NAME = 'aircraft_reference_features' THEN
    SELECT value_type INTO expected_value_type
    FROM aircraft_feature_definitions
    WHERE id = NEW.aircraft_feature_definition_id;
    IF (expected_value_type = 'boolean' AND NEW.boolean_value IS NULL)
       OR (expected_value_type = 'number' AND NEW.number_value IS NULL)
       OR (expected_value_type = 'text' AND NEW.text_value IS NULL)
       OR expected_value_type IS NULL THEN
      RAISE EXCEPTION 'reference feature value does not match its definition';
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER aircraft_reference_scope_building_insert
BEFORE INSERT ON aircraft_reference_applicability_scopes
FOR EACH ROW EXECUTE FUNCTION validate_aircraft_reference_child_insert();
CREATE TRIGGER aircraft_reference_price_building_insert
BEFORE INSERT ON aircraft_reference_prices
FOR EACH ROW EXECUTE FUNCTION validate_aircraft_reference_child_insert();
CREATE TRIGGER aircraft_reference_avionics_building_insert
BEFORE INSERT ON aircraft_reference_avionics
FOR EACH ROW EXECUTE FUNCTION validate_aircraft_reference_child_insert();
CREATE TRIGGER aircraft_reference_engines_building_insert
BEFORE INSERT ON aircraft_reference_engines
FOR EACH ROW EXECUTE FUNCTION validate_aircraft_reference_child_insert();
CREATE TRIGGER aircraft_reference_propellers_building_insert
BEFORE INSERT ON aircraft_reference_propellers
FOR EACH ROW EXECUTE FUNCTION validate_aircraft_reference_child_insert();
CREATE TRIGGER aircraft_reference_features_building_insert
BEFORE INSERT ON aircraft_reference_features
FOR EACH ROW EXECUTE FUNCTION validate_aircraft_reference_child_insert();

CREATE OR REPLACE FUNCTION prevent_aircraft_reference_fact_mutation()
RETURNS TRIGGER AS $$
DECLARE
  parent_id BIGINT;
  parent_state TEXT;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    RAISE EXCEPTION 'reference profile facts are immutable; publish a replacement version';
  END IF;
  parent_id := OLD.aircraft_reference_configuration_version_id;
  SELECT publication_state INTO parent_state
  FROM aircraft_reference_configuration_versions WHERE id = parent_id;
  IF parent_state IS DISTINCT FROM 'building' THEN
    RAISE EXCEPTION 'published reference profile facts are immutable';
  END IF;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER aircraft_reference_scope_immutable
BEFORE UPDATE OR DELETE ON aircraft_reference_applicability_scopes
FOR EACH ROW EXECUTE FUNCTION prevent_aircraft_reference_fact_mutation();
CREATE TRIGGER aircraft_reference_price_immutable
BEFORE UPDATE OR DELETE ON aircraft_reference_prices
FOR EACH ROW EXECUTE FUNCTION prevent_aircraft_reference_fact_mutation();
CREATE TRIGGER aircraft_reference_avionics_immutable
BEFORE UPDATE OR DELETE ON aircraft_reference_avionics
FOR EACH ROW EXECUTE FUNCTION prevent_aircraft_reference_fact_mutation();
CREATE TRIGGER aircraft_reference_engines_immutable
BEFORE UPDATE OR DELETE ON aircraft_reference_engines
FOR EACH ROW EXECUTE FUNCTION prevent_aircraft_reference_fact_mutation();
CREATE TRIGGER aircraft_reference_propellers_immutable
BEFORE UPDATE OR DELETE ON aircraft_reference_propellers
FOR EACH ROW EXECUTE FUNCTION prevent_aircraft_reference_fact_mutation();
CREATE TRIGGER aircraft_reference_features_immutable
BEFORE UPDATE OR DELETE ON aircraft_reference_features
FOR EACH ROW EXECUTE FUNCTION prevent_aircraft_reference_fact_mutation();

CREATE OR REPLACE FUNCTION validate_aircraft_reference_version_update()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.publication_state IN ('published', 'superseded') THEN
    IF NOT (
      OLD.publication_state = 'published'
      AND NEW.publication_state = 'superseded'
      AND NEW.superseded_at IS NOT NULL
      AND NEW.id = OLD.id
      AND NEW.aircraft_reference_configuration_id = OLD.aircraft_reference_configuration_id
      AND NEW.model_year = OLD.model_year
      AND NEW.revision = OLD.revision
      AND NEW.approval_decision_id = OLD.approval_decision_id
      AND NEW.published_at = OLD.published_at
      AND NEW.supersedes_version_id IS NOT DISTINCT FROM OLD.supersedes_version_id
    ) THEN
      RAISE EXCEPTION 'published reference profile versions are immutable';
    END IF;
    RETURN NEW;
  END IF;

  IF NEW.publication_state = 'published' THEN
    IF OLD.publication_state <> 'building' OR NEW.published_at IS NULL THEN
      RAISE EXCEPTION 'only a building profile with published_at can be published';
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM aircraft_reference_applicability_scopes scope
      WHERE scope.aircraft_reference_configuration_version_id = NEW.id
    ) THEN
      RAISE EXCEPTION 'published reference profile requires applicability';
    END IF;
    IF NOT EXISTS (
      SELECT 1
      FROM aircraft_reference_prices price
      JOIN curation_evidence_claims claim ON claim.id = price.evidence_claim_id
      JOIN curation_evidence_sources source ON source.id = claim.evidence_source_id
      WHERE price.aircraft_reference_configuration_version_id = NEW.id
        AND price.price_kind IN ('base_msrp', 'equipped_msrp')
        AND price.evidence_kind = 'direct_model_year'
        AND price.price_reference_year = NEW.model_year
        AND claim.validation_status = 'validated'
        AND source.source_tier IN ('manufacturer_primary', 'regulator_primary')
    ) THEN
      RAISE EXCEPTION 'published profile requires direct exact-year primary price evidence';
    END IF;
    IF EXISTS (
      SELECT 1
      FROM aircraft_reference_engines engine
      LEFT JOIN aircraft_engine_catalog_models model
        ON model.id = engine.aircraft_engine_catalog_model_id
       AND model.catalog_status = 'approved'
      WHERE engine.aircraft_reference_configuration_version_id = NEW.id
        AND model.id IS NULL
    ) THEN
      RAISE EXCEPTION 'published profile requires approved engine catalog models';
    END IF;
    IF EXISTS (
      SELECT 1
      FROM aircraft_reference_propellers propeller
      LEFT JOIN aircraft_propeller_catalog_models model
        ON model.id = propeller.aircraft_propeller_catalog_model_id
       AND model.catalog_status = 'approved'
      WHERE propeller.aircraft_reference_configuration_version_id = NEW.id
        AND model.id IS NULL
    ) THEN
      RAISE EXCEPTION 'published profile requires approved propeller catalog models';
    END IF;
    IF EXISTS (
      SELECT 1
      FROM (
        SELECT evidence_claim_id FROM aircraft_reference_applicability_scopes
        WHERE aircraft_reference_configuration_version_id = NEW.id
        UNION ALL
        SELECT evidence_claim_id FROM aircraft_reference_prices
        WHERE aircraft_reference_configuration_version_id = NEW.id
        UNION ALL
        SELECT evidence_claim_id FROM aircraft_reference_avionics
        WHERE aircraft_reference_configuration_version_id = NEW.id
        UNION ALL
        SELECT evidence_claim_id FROM aircraft_reference_engines
        WHERE aircraft_reference_configuration_version_id = NEW.id
        UNION ALL
        SELECT evidence_claim_id FROM aircraft_reference_propellers
        WHERE aircraft_reference_configuration_version_id = NEW.id
        UNION ALL
        SELECT evidence_claim_id FROM aircraft_reference_features
        WHERE aircraft_reference_configuration_version_id = NEW.id
      ) fact
      JOIN curation_evidence_claims claim ON claim.id = fact.evidence_claim_id
      JOIN curation_evidence_sources source ON source.id = claim.evidence_source_id
      WHERE claim.validation_status <> 'validated'
         OR source.source_tier NOT IN ('manufacturer_primary', 'regulator_primary')
    ) THEN
      RAISE EXCEPTION 'published reference profile facts require validated primary evidence';
    END IF;
    IF EXISTS (
      SELECT 1
      FROM aircraft_reference_applicability_scopes left_scope
      JOIN aircraft_reference_applicability_scopes right_scope
        ON right_scope.aircraft_reference_configuration_version_id = left_scope.aircraft_reference_configuration_version_id
       AND right_scope.id > left_scope.id
       AND right_scope.aircraft_market_id = left_scope.aircraft_market_id
      WHERE left_scope.aircraft_reference_configuration_version_id = NEW.id
        AND (
          left_scope.applies_to_all_serials OR right_scope.applies_to_all_serials
          OR (
            left_scope.aircraft_serial_number_scheme_id = right_scope.aircraft_serial_number_scheme_id
            AND COALESCE(left_scope.serial_prefix, '') = COALESCE(right_scope.serial_prefix, '')
            AND left_scope.serial_from_sort_key <= right_scope.serial_to_sort_key
            AND right_scope.serial_from_sort_key <= left_scope.serial_to_sort_key
          )
        )
    ) THEN
      RAISE EXCEPTION 'reference profile contains overlapping applicability scopes';
    END IF;
    IF EXISTS (
      SELECT 1
      FROM aircraft_reference_applicability_scopes candidate
      JOIN aircraft_reference_applicability_scopes existing
        ON existing.aircraft_market_id = candidate.aircraft_market_id
      JOIN aircraft_reference_configuration_versions existing_version
        ON existing_version.id = existing.aircraft_reference_configuration_version_id
      WHERE candidate.aircraft_reference_configuration_version_id = NEW.id
        AND existing_version.id <> NEW.id
        AND existing_version.aircraft_reference_configuration_id = NEW.aircraft_reference_configuration_id
        AND existing_version.model_year = NEW.model_year
        AND existing_version.publication_state = 'published'
        AND (
          candidate.applies_to_all_serials OR existing.applies_to_all_serials
          OR (
            candidate.aircraft_serial_number_scheme_id = existing.aircraft_serial_number_scheme_id
            AND COALESCE(candidate.serial_prefix, '') = COALESCE(existing.serial_prefix, '')
            AND candidate.serial_from_sort_key <= existing.serial_to_sort_key
            AND existing.serial_from_sort_key <= candidate.serial_to_sort_key
          )
        )
    ) THEN
      RAISE EXCEPTION 'reference profile applicability overlaps an existing published version';
    END IF;
  ELSIF NEW.publication_state <> 'building' THEN
    RAISE EXCEPTION 'invalid building profile state transition';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER aircraft_reference_versions_validate_update
BEFORE UPDATE ON aircraft_reference_configuration_versions
FOR EACH ROW EXECUTE FUNCTION validate_aircraft_reference_version_update();

-- Privacy-minimized, target-scoped FAA releasable-registry snapshots. Only
-- requested current MASTER rows and their reachable ACFTREF/ENGINE rows are
-- retained; registrant, address, other-name, Mode-S, and unrelated rows are not.
CREATE TABLE faa_registry_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evidence_source_id BIGINT NOT NULL
    REFERENCES curation_evidence_sources(id) ON DELETE RESTRICT,
  snapshot_date TEXT NOT NULL,
  source_url TEXT NOT NULL,
  archive_sha256 TEXT NOT NULL,
  source_manifest_sha256 TEXT NOT NULL,
  target_set_sha256 TEXT NOT NULL,
  master_member_name TEXT NOT NULL CHECK (master_member_name = 'MASTER.txt'),
  master_member_sha256 TEXT NOT NULL,
  aircraft_member_name TEXT NOT NULL CHECK (aircraft_member_name = 'ACFTREF.txt'),
  aircraft_member_sha256 TEXT NOT NULL,
  engine_member_name TEXT NOT NULL CHECK (engine_member_name = 'ENGINE.txt'),
  engine_member_sha256 TEXT NOT NULL,
  imported_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (archive_sha256, target_set_sha256),
  CHECK (snapshot_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'),
  CHECK (source_url ~ '^https://([^. /]+[.])*faa[.]gov/'),
  CHECK (archive_sha256 ~ '^[0-9a-f]{64}$'),
  CHECK (source_manifest_sha256 ~ '^[0-9a-f]{64}$'),
  CHECK (target_set_sha256 ~ '^[0-9a-f]{64}$'),
  CHECK (master_member_sha256 ~ '^[0-9a-f]{64}$'),
  CHECK (aircraft_member_sha256 ~ '^[0-9a-f]{64}$'),
  CHECK (engine_member_sha256 ~ '^[0-9a-f]{64}$')
);

CREATE INDEX idx_faa_registry_snapshots_current
  ON faa_registry_snapshots (snapshot_date DESC, id DESC);

CREATE TABLE faa_registry_aircraft (
  snapshot_id BIGINT NOT NULL REFERENCES faa_registry_snapshots(id) ON DELETE RESTRICT,
  n_number TEXT NOT NULL,
  manufacturer_serial_raw TEXT,
  manufacturer_serial_key TEXT,
  aircraft_code TEXT NOT NULL,
  engine_code TEXT,
  year_manufactured BIGINT,
  source_record_sha256 TEXT NOT NULL,
  PRIMARY KEY (snapshot_id, n_number),
  UNIQUE (snapshot_id, source_record_sha256),
  CHECK (left(n_number, 1) = 'N' AND length(n_number) BETWEEN 2 AND 6),
  CHECK (manufacturer_serial_raw IS NULL OR length(trim(manufacturer_serial_raw)) > 0),
  CHECK (manufacturer_serial_key IS NULL OR length(manufacturer_serial_key) > 0),
  CHECK (length(trim(aircraft_code)) > 0),
  CHECK (engine_code IS NULL OR length(trim(engine_code)) > 0),
  CHECK (year_manufactured IS NULL OR year_manufactured BETWEEN 1900 AND 2200),
  CHECK (source_record_sha256 ~ '^[0-9a-f]{64}$')
);

CREATE INDEX idx_faa_registry_aircraft_code
  ON faa_registry_aircraft (snapshot_id, aircraft_code);
CREATE INDEX idx_faa_registry_engine_code
  ON faa_registry_aircraft (snapshot_id, engine_code);

CREATE TABLE faa_registry_aircraft_references (
  snapshot_id BIGINT NOT NULL REFERENCES faa_registry_snapshots(id) ON DELETE RESTRICT,
  aircraft_code TEXT NOT NULL,
  manufacturer_name TEXT,
  model_name TEXT,
  aircraft_type_code TEXT,
  engine_type_code TEXT,
  category_code TEXT,
  certification_indicator_code TEXT,
  engine_count BIGINT CHECK (engine_count IS NULL OR engine_count >= 0),
  seat_count BIGINT CHECK (seat_count IS NULL OR seat_count >= 0),
  weight_class_code TEXT,
  cruise_speed_mph BIGINT CHECK (cruise_speed_mph IS NULL OR cruise_speed_mph >= 0),
  type_certificate_data_sheet TEXT,
  type_certificate_holder TEXT,
  PRIMARY KEY (snapshot_id, aircraft_code),
  CHECK (length(trim(aircraft_code)) > 0)
);

CREATE TABLE faa_registry_engine_references (
  snapshot_id BIGINT NOT NULL REFERENCES faa_registry_snapshots(id) ON DELETE RESTRICT,
  engine_code TEXT NOT NULL,
  manufacturer_name TEXT,
  model_name TEXT,
  engine_type_code TEXT,
  horsepower BIGINT CHECK (horsepower IS NULL OR horsepower >= 0),
  thrust_pounds BIGINT CHECK (thrust_pounds IS NULL OR thrust_pounds >= 0),
  PRIMARY KEY (snapshot_id, engine_code),
  CHECK (length(trim(engine_code)) > 0)
);

CREATE TABLE faa_registry_coverage (
  snapshot_id BIGINT NOT NULL REFERENCES faa_registry_snapshots(id) ON DELETE RESTRICT,
  n_number TEXT NOT NULL,
  lookup_status TEXT NOT NULL CHECK (lookup_status IN ('matched', 'absent')),
  PRIMARY KEY (snapshot_id, n_number),
  CHECK (left(n_number, 1) = 'N' AND length(n_number) BETWEEN 2 AND 6)
);

CREATE INDEX idx_faa_registry_coverage_lookup
  ON faa_registry_coverage (n_number, snapshot_id);

CREATE OR REPLACE FUNCTION validate_faa_snapshot_evidence()
RETURNS TRIGGER AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM curation_evidence_sources source
    WHERE source.id = NEW.evidence_source_id
      AND source.source_domain = 'faa.gov'
      AND source.source_tier = 'regulator_primary'
      AND source.source_url = NEW.source_url
      AND source.content_sha256 = NEW.archive_sha256
  ) THEN
    RAISE EXCEPTION 'FAA snapshot requires exact regulator evidence provenance';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER faa_registry_snapshots_require_exact_evidence
BEFORE INSERT ON faa_registry_snapshots
FOR EACH ROW EXECUTE FUNCTION validate_faa_snapshot_evidence();

CREATE OR REPLACE FUNCTION validate_faa_reference_reachability()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_TABLE_NAME = 'faa_registry_aircraft_references' AND NOT EXISTS (
    SELECT 1 FROM faa_registry_aircraft aircraft
    WHERE aircraft.snapshot_id = NEW.snapshot_id
      AND aircraft.aircraft_code = NEW.aircraft_code
  ) THEN
    RAISE EXCEPTION 'FAA aircraft reference must be reachable from a target match';
  END IF;
  IF TG_TABLE_NAME = 'faa_registry_engine_references' AND NOT EXISTS (
    SELECT 1 FROM faa_registry_aircraft aircraft
    WHERE aircraft.snapshot_id = NEW.snapshot_id
      AND aircraft.engine_code = NEW.engine_code
  ) THEN
    RAISE EXCEPTION 'FAA engine reference must be reachable from a target match';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER faa_registry_aircraft_references_reachable
BEFORE INSERT ON faa_registry_aircraft_references
FOR EACH ROW EXECUTE FUNCTION validate_faa_reference_reachability();
CREATE TRIGGER faa_registry_engine_references_reachable
BEFORE INSERT ON faa_registry_engine_references
FOR EACH ROW EXECUTE FUNCTION validate_faa_reference_reachability();

CREATE OR REPLACE FUNCTION validate_faa_coverage()
RETURNS TRIGGER AS $$
BEGIN
  IF (NEW.lookup_status = 'matched' AND NOT EXISTS (
        SELECT 1 FROM faa_registry_aircraft aircraft
        WHERE aircraft.snapshot_id = NEW.snapshot_id AND aircraft.n_number = NEW.n_number
      )) OR (NEW.lookup_status = 'absent' AND EXISTS (
        SELECT 1 FROM faa_registry_aircraft aircraft
        WHERE aircraft.snapshot_id = NEW.snapshot_id AND aircraft.n_number = NEW.n_number
      )) THEN
    RAISE EXCEPTION 'FAA coverage must agree with its target match';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER faa_registry_coverage_consistent
BEFORE INSERT ON faa_registry_coverage
FOR EACH ROW EXECUTE FUNCTION validate_faa_coverage();

CREATE OR REPLACE FUNCTION preserve_faa_registry_data()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'FAA registry snapshots and projections are immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER faa_registry_snapshots_immutable
BEFORE UPDATE OR DELETE ON faa_registry_snapshots
FOR EACH ROW EXECUTE FUNCTION preserve_faa_registry_data();
CREATE TRIGGER faa_registry_aircraft_immutable
BEFORE UPDATE OR DELETE ON faa_registry_aircraft
FOR EACH ROW EXECUTE FUNCTION preserve_faa_registry_data();
CREATE TRIGGER faa_registry_aircraft_references_immutable
BEFORE UPDATE OR DELETE ON faa_registry_aircraft_references
FOR EACH ROW EXECUTE FUNCTION preserve_faa_registry_data();
CREATE TRIGGER faa_registry_engine_references_immutable
BEFORE UPDATE OR DELETE ON faa_registry_engine_references
FOR EACH ROW EXECUTE FUNCTION preserve_faa_registry_data();
CREATE TRIGGER faa_registry_coverage_immutable
BEFORE UPDATE OR DELETE ON faa_registry_coverage
FOR EACH ROW EXECUTE FUNCTION preserve_faa_registry_data();

COMMIT;
