-- Add the durable listing pending-review handoff. The migration is additive
-- except for replacing the listing ingestion-state CHECK and is safe to
-- reapply.

BEGIN;

ALTER TABLE aircraft_sale_listings
  DROP CONSTRAINT IF EXISTS aircraft_sale_listings_ingestion_state_check;
ALTER TABLE aircraft_sale_listings
  ADD CONSTRAINT aircraft_sale_listings_ingestion_state_check
  CHECK (ingestion_state IN (
    'incomplete', 'pending_review', 'ready', 'quarantined'
  ));

CREATE TABLE IF NOT EXISTS aircraft_sale_listing_pending_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_sale_listings(id) ON DELETE CASCADE,
  plugin_submission_id BIGINT
    REFERENCES plugin_submissions(id) ON DELETE SET NULL,
  extraction_sha256 TEXT NOT NULL,
  catalog_revision_sha256 TEXT NOT NULL,
  pending_aspect_count BIGINT NOT NULL CHECK (pending_aspect_count >= 1),
  review_payload_json TEXT NOT NULL,
  review_payload_sha256 TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (extraction_sha256 ~ '^[0-9a-f]{64}$'),
  CHECK (catalog_revision_sha256 ~ '^[0-9a-f]{64}$'),
  CHECK (length(trim(review_payload_json)) > 0),
  CHECK (review_payload_sha256 ~ '^[0-9a-f]{64}$')
);

CREATE INDEX IF NOT EXISTS idx_aircraft_sale_listing_pending_reviews_submission
  ON aircraft_sale_listing_pending_reviews (plugin_submission_id);

COMMIT;
