-- Add resumable coordination for trusted-capture listing replay.

BEGIN;

CREATE TABLE IF NOT EXISTS public.schema_migration_contracts (
  migration_name TEXT PRIMARY KEY,
  contract_version INTEGER NOT NULL CHECK (contract_version > 0),
  contract_fingerprint TEXT NOT NULL CHECK (contract_fingerprint ~ '^[0-9a-f]{64}$'),
  installed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $migration_guard$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.schema_migration_contracts
    WHERE migration_name = '20260819_listing_replay_runs'
      AND (contract_version <> 1 OR contract_fingerprint <>
        '8efc70b938e9937d22ae5532ea19f93ce51cc322b2c99f5a2b52e79212c92c3c')
  ) THEN
    RAISE EXCEPTION 'installed listing replay runs migration has a different contract';
  END IF;
  IF (
    pg_catalog.to_regclass('public.listing_replay_runs') IS NOT NULL
    OR pg_catalog.to_regclass('public.listing_replay_run_items') IS NOT NULL
    OR pg_catalog.to_regclass('public.idx_listing_replay_runs_one_running') IS NOT NULL
    OR pg_catalog.to_regclass('public.idx_listing_replay_run_items_phase') IS NOT NULL
  ) AND NOT EXISTS (
    SELECT 1 FROM public.schema_migration_contracts
    WHERE migration_name = '20260819_listing_replay_runs'
      AND contract_version = 1
      AND contract_fingerprint =
        '8efc70b938e9937d22ae5532ea19f93ce51cc322b2c99f5a2b52e79212c92c3c'
  ) THEN
    RAISE EXCEPTION
      'listing replay objects exist without the exact migration contract';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.schema_migration_contracts
    WHERE migration_name = '20260819_listing_replay_runs'
      AND contract_version = 1
      AND contract_fingerprint =
        '8efc70b938e9937d22ae5532ea19f93ce51cc322b2c99f5a2b52e79212c92c3c'
  ) AND (
    pg_catalog.to_regclass('public.listing_replay_runs') IS NULL
    OR pg_catalog.to_regclass('public.listing_replay_run_items') IS NULL
    OR pg_catalog.to_regclass('public.idx_listing_replay_runs_one_running') IS NULL
    OR pg_catalog.to_regclass('public.idx_listing_replay_run_items_phase') IS NULL
  ) THEN
    RAISE EXCEPTION
      'installed listing replay migration contract has incomplete objects';
  END IF;
END
$migration_guard$;

CREATE TABLE IF NOT EXISTS public.listing_replay_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manifest_version BIGINT NOT NULL CHECK (manifest_version > 0),
  manifest_sha256 TEXT NOT NULL UNIQUE CHECK (manifest_sha256 ~ '^[0-9a-f]{64}$'),
  manifest_capture_count BIGINT NOT NULL CHECK (manifest_capture_count > 0),
  status TEXT NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'running', 'completed')),
  active_phase TEXT CHECK (active_phase IN ('extraction', 'materialization')),
  owner_token TEXT,
  heartbeat_at_epoch_seconds BIGINT,
  started_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TEXT,
  CHECK (owner_token IS NULL OR length(BTRIM(owner_token)) BETWEEN 1 AND 200),
  CHECK (
    (status = 'running' AND active_phase IS NOT NULL AND owner_token IS NOT NULL
      AND heartbeat_at_epoch_seconds IS NOT NULL AND started_at IS NOT NULL
      AND completed_at IS NULL)
    OR
    (status = 'queued' AND active_phase IS NULL AND owner_token IS NULL
      AND heartbeat_at_epoch_seconds IS NULL AND completed_at IS NULL)
    OR
    (status = 'completed' AND active_phase IS NULL AND owner_token IS NULL
      AND heartbeat_at_epoch_seconds IS NULL AND completed_at IS NOT NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_listing_replay_runs_one_running
  ON public.listing_replay_runs (status) WHERE status = 'running';

CREATE TABLE IF NOT EXISTS public.listing_replay_run_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES public.listing_replay_runs(id) ON DELETE CASCADE,
  plugin_submission_id BIGINT NOT NULL
    REFERENCES public.plugin_submissions(id) ON DELETE RESTRICT,
  position BIGINT NOT NULL CHECK (position >= 0),
  expected_rendered_html_sha256 TEXT NOT NULL
    CHECK (expected_rendered_html_sha256 ~ '^[0-9a-f]{64}$'),
  extraction_state TEXT NOT NULL DEFAULT 'queued'
    CHECK (extraction_state IN ('queued', 'running', 'succeeded', 'rejected', 'failed')),
  materialization_state TEXT NOT NULL DEFAULT 'blocked'
    CHECK (materialization_state IN ('blocked', 'queued', 'running', 'succeeded', 'rejected', 'failed')),
  resulting_listing_id BIGINT
    REFERENCES public.aircraft_sale_listings(id) ON DELETE SET NULL,
  terminal_rejection_phase TEXT
    CHECK (terminal_rejection_phase IN ('extraction', 'materialization')),
  terminal_rejection_stage TEXT CHECK (terminal_rejection_stage IN (
    'capture_admission', 'listing_extraction',
    'faa_aircraft_admission', 'listing_admission'
  )),
  terminal_rejection_reason_code TEXT CHECK (terminal_rejection_reason_code IN (
    'capture_authentication_failed', 'capture_not_found', 'capture_validation_failed',
    'extraction_rejected', 'checkpoint_missing', 'listing_admission_rejected',
    'faa_aircraft_admission_rejected', 'missing_registration', 'non_n_registration',
    'invalid_n_number', 'registry_snapshot_unavailable', 'registration_not_found',
    'registration_not_covered', 'ambiguous_registration', 'serial_conflict',
    'registry_aircraft_identity_unavailable', 'aircraft_manufacturer_mismatch',
    'aircraft_model_mismatch', 'canonical_identity_assignment_missing',
    'canonical_identity_assignment_mismatch'
  )),
  last_failure_phase TEXT CHECK (last_failure_phase IN ('extraction', 'materialization')),
  last_failure_reason_code TEXT
    CHECK (last_failure_reason_code IN ('database_error', 'operation_failed')),
  extraction_attempt_count BIGINT NOT NULL DEFAULT 0 CHECK (extraction_attempt_count >= 0),
  materialization_attempt_count BIGINT NOT NULL DEFAULT 0 CHECK (materialization_attempt_count >= 0),
  extraction_started_at TEXT,
  extraction_completed_at TEXT,
  materialization_started_at TEXT,
  materialization_completed_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (run_id, position),
  UNIQUE (run_id, plugin_submission_id),
  CHECK (
    (terminal_rejection_phase IS NULL AND terminal_rejection_stage IS NULL
      AND terminal_rejection_reason_code IS NULL)
    OR
    (terminal_rejection_phase IS NOT NULL AND terminal_rejection_stage IS NOT NULL
      AND terminal_rejection_reason_code IS NOT NULL)
  ),
  CHECK (
    (last_failure_phase IS NULL AND last_failure_reason_code IS NULL)
    OR (last_failure_phase IS NOT NULL AND last_failure_reason_code IS NOT NULL)
  ),
  CHECK (resulting_listing_id IS NULL OR materialization_state = 'succeeded'),
  CHECK (extraction_state = 'succeeded' OR materialization_state = 'blocked'),
  CHECK (extraction_state <> 'running' OR extraction_started_at IS NOT NULL),
  CHECK (materialization_state <> 'running' OR materialization_started_at IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_listing_replay_run_items_phase
  ON public.listing_replay_run_items
    (run_id, extraction_state, materialization_state, position);

INSERT INTO public.schema_migration_contracts (
  migration_name, contract_version, contract_fingerprint, installed_at
) VALUES (
  '20260819_listing_replay_runs', 1,
  '8efc70b938e9937d22ae5532ea19f93ce51cc322b2c99f5a2b52e79212c92c3c',
  CURRENT_TIMESTAMP
) ON CONFLICT (migration_name) DO UPDATE SET
  contract_version = EXCLUDED.contract_version,
  contract_fingerprint = EXCLUDED.contract_fingerprint,
  installed_at = EXCLUDED.installed_at;

COMMIT;
