BEGIN;

SET LOCAL search_path = public, pg_catalog, pg_temp;

CREATE TABLE IF NOT EXISTS public.schema_migration_contracts (
  migration_name TEXT PRIMARY KEY,
  contract_version INTEGER NOT NULL CHECK (contract_version > 0),
  contract_fingerprint TEXT NOT NULL
    CHECK (contract_fingerprint ~ '^[0-9a-f]{64}$'),
  installed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (length(trim(migration_name)) > 0)
);

LOCK TABLE ONLY public.schema_migration_contracts
IN SHARE ROW EXCLUSIVE MODE;

DO $migration_guard$
BEGIN
  IF EXISTS (
    SELECT 1 FROM ONLY public.schema_migration_contracts
    WHERE migration_name = '20260725_listing_aircraft_identity'
      AND (
        contract_version IS DISTINCT FROM 2
        OR contract_fingerprint IS DISTINCT FROM
          '63fb5b5213fc9eb2b7b4dcb2b0be3a9f22a80d4acae49f64e68ec1302c1437be'
      )
  ) THEN
    RAISE EXCEPTION
      'installed listing aircraft identity migration has a different contract';
  END IF;
END
$migration_guard$;

-- Immutable assignment versions retain every approved correction. The small
-- current-pointer table is the only mutable state.
-- N-registered listings are evaluated in the United States market. Aliases
-- scoped to other markets are not identity evidence for this pipeline.
INSERT INTO aircraft_markets (code, name, parent_market_id)
SELECT 'US', 'United States', id
FROM aircraft_markets
WHERE code = 'GLOBAL'
ON CONFLICT (code) DO NOTHING;

CREATE TABLE IF NOT EXISTS aircraft_designation_faa_bindings (
  faa_snapshot_date TEXT NOT NULL,
  faa_archive_sha256 TEXT NOT NULL,
  faa_aircraft_code TEXT NOT NULL,
  aircraft_designation_id BIGINT NOT NULL
    REFERENCES aircraft_designations(id) ON DELETE RESTRICT,
  representative_faa_registry_snapshot_id BIGINT NOT NULL,
  identity_evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (representative_faa_registry_snapshot_id, faa_aircraft_code)
    REFERENCES faa_registry_aircraft_references(snapshot_id, aircraft_code)
    ON DELETE RESTRICT,
  CHECK (faa_snapshot_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'),
  CHECK (length(faa_archive_sha256) = 64 AND faa_archive_sha256 !~ '[^0-9a-f]'),
  CHECK (length(trim(faa_aircraft_code)) > 0),
  PRIMARY KEY (faa_snapshot_date, faa_archive_sha256, faa_aircraft_code)
);

CREATE TABLE IF NOT EXISTS aircraft_sale_listing_identity_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_sale_listing_id BIGINT NOT NULL
    REFERENCES aircraft_sale_listings(id) ON DELETE CASCADE,
  supersedes_assignment_id BIGINT UNIQUE,
  aircraft_make_id BIGINT NOT NULL,
  aircraft_model_family_id BIGINT NOT NULL,
  aircraft_designation_id BIGINT NOT NULL,
  aircraft_generation_id BIGINT,
  aircraft_factory_package_id BIGINT,
  identity_decision_id BIGINT NOT NULL
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  identity_evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  faa_registry_snapshot_id BIGINT NOT NULL
    REFERENCES faa_registry_snapshots(id) ON DELETE RESTRICT,
  faa_n_number TEXT NOT NULL,
  faa_source_record_sha256 TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (id, aircraft_sale_listing_id),
  CONSTRAINT aircraft_listing_identity_assignment_supersedes_fk
    FOREIGN KEY (supersedes_assignment_id, aircraft_sale_listing_id)
    REFERENCES aircraft_sale_listing_identity_assignments(id, aircraft_sale_listing_id)
    ON DELETE CASCADE,
  FOREIGN KEY (aircraft_model_family_id, aircraft_make_id)
    REFERENCES aircraft_model_families(id, aircraft_make_id) ON DELETE RESTRICT,
  FOREIGN KEY (aircraft_designation_id, aircraft_model_family_id)
    REFERENCES aircraft_designations(id, aircraft_model_family_id) ON DELETE RESTRICT,
  FOREIGN KEY (aircraft_generation_id, aircraft_model_family_id)
    REFERENCES aircraft_generations(id, aircraft_model_family_id) ON DELETE RESTRICT,
  FOREIGN KEY (aircraft_factory_package_id, aircraft_model_family_id)
    REFERENCES aircraft_factory_packages(id, aircraft_model_family_id) ON DELETE RESTRICT,
  FOREIGN KEY (faa_registry_snapshot_id, faa_n_number)
    REFERENCES faa_registry_aircraft(snapshot_id, n_number) ON DELETE RESTRICT,
  FOREIGN KEY (faa_registry_snapshot_id, faa_source_record_sha256)
    REFERENCES faa_registry_aircraft(snapshot_id, source_record_sha256) ON DELETE RESTRICT,
  CHECK (left(faa_n_number, 1) = 'N' AND length(faa_n_number) BETWEEN 2 AND 6),
  CHECK (
    length(faa_source_record_sha256) = 64
    AND faa_source_record_sha256 !~ '[^0-9a-f]'
  )
);

-- Replace the draft v1 generated RESTRICT constraint transactionally. Resolve
-- the constraint by its catalog columns rather than PostgreSQL's truncated
-- generated name, then leave a stable explicit name for future inspection.
DO $listing_aircraft_identity_v2$
DECLARE
  existing_constraint_name TEXT;
  existing_constraint_definition TEXT;
BEGIN
  SELECT constraint_row.conname,
         pg_get_constraintdef(constraint_row.oid, true)
  INTO existing_constraint_name, existing_constraint_definition
  FROM pg_constraint constraint_row
  WHERE constraint_row.conrelid =
      'aircraft_sale_listing_identity_assignments'::regclass
    AND constraint_row.confrelid =
      'aircraft_sale_listing_identity_assignments'::regclass
    AND constraint_row.contype = 'f'
    AND (
      SELECT array_agg(attribute.attname::TEXT ORDER BY column_key.ordinality)
      FROM unnest(constraint_row.conkey)
        WITH ORDINALITY AS column_key(attnum, ordinality)
      JOIN pg_attribute attribute
        ON attribute.attrelid = constraint_row.conrelid
       AND attribute.attnum = column_key.attnum
    ) = ARRAY['supersedes_assignment_id', 'aircraft_sale_listing_id']
    AND (
      SELECT array_agg(attribute.attname::TEXT ORDER BY column_key.ordinality)
      FROM unnest(constraint_row.confkey)
        WITH ORDINALITY AS column_key(attnum, ordinality)
      JOIN pg_attribute attribute
        ON attribute.attrelid = constraint_row.confrelid
       AND attribute.attnum = column_key.attnum
    ) = ARRAY['id', 'aircraft_sale_listing_id']
  LIMIT 1;

  IF existing_constraint_name IS NULL THEN
    ALTER TABLE aircraft_sale_listing_identity_assignments
      ADD CONSTRAINT aircraft_listing_identity_assignment_supersedes_fk
      FOREIGN KEY (supersedes_assignment_id, aircraft_sale_listing_id)
      REFERENCES aircraft_sale_listing_identity_assignments(
        id, aircraft_sale_listing_id
      )
      ON DELETE CASCADE;
  ELSIF position(
      'ON DELETE CASCADE' IN upper(existing_constraint_definition)
    ) = 0 THEN
    EXECUTE format(
      'ALTER TABLE aircraft_sale_listing_identity_assignments DROP CONSTRAINT %I',
      existing_constraint_name
    );
    ALTER TABLE aircraft_sale_listing_identity_assignments
      ADD CONSTRAINT aircraft_listing_identity_assignment_supersedes_fk
      FOREIGN KEY (supersedes_assignment_id, aircraft_sale_listing_id)
      REFERENCES aircraft_sale_listing_identity_assignments(
        id, aircraft_sale_listing_id
      )
      ON DELETE CASCADE;
  ELSIF existing_constraint_name <>
      'aircraft_listing_identity_assignment_supersedes_fk' THEN
    EXECUTE format(
      'ALTER TABLE aircraft_sale_listing_identity_assignments RENAME CONSTRAINT %I TO aircraft_listing_identity_assignment_supersedes_fk',
      existing_constraint_name
    );
  END IF;
END
$listing_aircraft_identity_v2$;

CREATE TABLE IF NOT EXISTS aircraft_sale_listing_current_identity_assignments (
  aircraft_sale_listing_id BIGINT PRIMARY KEY
    REFERENCES aircraft_sale_listings(id) ON DELETE CASCADE,
  identity_assignment_id BIGINT NOT NULL UNIQUE,
  selected_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (identity_assignment_id, aircraft_sale_listing_id)
    REFERENCES aircraft_sale_listing_identity_assignments(id, aircraft_sale_listing_id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_listing_identity_assignment_designation
  ON aircraft_sale_listing_identity_assignments (
    aircraft_designation_id, aircraft_generation_id, aircraft_factory_package_id
  );

-- Alias keys are retrieval keys, not free-form evidence. Keep their stored
-- form deterministic, prevent overlapping scopes from resolving one FAA label
-- to two makes, and preserve approved aliases immutably.
CREATE OR REPLACE FUNCTION validate_aircraft_make_identity_alias()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.normalized_alias = ''
    OR NEW.normalized_alias <> trim(NEW.normalized_alias)
    OR NEW.normalized_alias <> lower(NEW.normalized_alias)
    OR NEW.normalized_alias !~ '^[a-z0-9]+( [a-z0-9]+)*$'
    OR NEW.normalized_alias <>
       trim(regexp_replace(lower(NEW.alias), '[^a-z0-9]+', ' ', 'g')) THEN
    RAISE EXCEPTION 'aircraft make alias requires its deterministic normalized retrieval key';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM aircraft_make_aliases existing_alias
    LEFT JOIN aircraft_markets existing_market
      ON existing_market.id = existing_alias.aircraft_market_id
    LEFT JOIN aircraft_markets new_market
      ON new_market.id = NEW.aircraft_market_id
    WHERE existing_alias.aircraft_make_id <> NEW.aircraft_make_id
      AND existing_alias.normalized_alias = NEW.normalized_alias
      AND (existing_alias.valid_to_model_year IS NULL
        OR NEW.valid_from_model_year IS NULL
        OR existing_alias.valid_to_model_year >= NEW.valid_from_model_year)
      AND (NEW.valid_to_model_year IS NULL
        OR existing_alias.valid_from_model_year IS NULL
        OR NEW.valid_to_model_year >= existing_alias.valid_from_model_year)
      AND (existing_alias.aircraft_market_id IS NULL
        OR NEW.aircraft_market_id IS NULL
        OR existing_alias.aircraft_market_id = NEW.aircraft_market_id
        OR existing_market.code = 'GLOBAL'
        OR new_market.code = 'GLOBAL')
  ) OR EXISTS (
    SELECT 1 FROM aircraft_makes other_make
    WHERE other_make.id <> NEW.aircraft_make_id
      AND (
        other_make.normalized_name = NEW.normalized_alias
        OR trim(regexp_replace(lower(other_make.name), '[^a-z0-9]+', ' ', 'g'))
          = NEW.normalized_alias
      )
  ) THEN
    RAISE EXCEPTION 'aircraft make alias overlaps another canonical make in market/year scope';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS aircraft_make_alias_identity_validate
  ON aircraft_make_aliases;
CREATE TRIGGER aircraft_make_alias_identity_validate
BEFORE INSERT ON aircraft_make_aliases
FOR EACH ROW EXECUTE FUNCTION validate_aircraft_make_identity_alias();

CREATE OR REPLACE FUNCTION preserve_aircraft_make_identity_alias()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'approved aircraft make aliases are immutable';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS aircraft_make_alias_identity_immutable
  ON aircraft_make_aliases;
CREATE TRIGGER aircraft_make_alias_identity_immutable
BEFORE UPDATE OR DELETE ON aircraft_make_aliases
FOR EACH ROW EXECUTE FUNCTION preserve_aircraft_make_identity_alias();

CREATE OR REPLACE FUNCTION prevent_aircraft_make_alias_collision()
RETURNS TRIGGER AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM aircraft_make_aliases alias
    WHERE alias.aircraft_make_id <> COALESCE(NEW.id, -1)
      AND trim(regexp_replace(lower(NEW.name), '[^a-z0-9]+', ' ', 'g'))
        = alias.normalized_alias
  ) THEN
    RAISE EXCEPTION 'canonical aircraft make collides with an approved alias';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS aircraft_make_identity_alias_collision
  ON aircraft_makes;
CREATE TRIGGER aircraft_make_identity_alias_collision
BEFORE INSERT OR UPDATE ON aircraft_makes
FOR EACH ROW EXECUTE FUNCTION prevent_aircraft_make_alias_collision();

-- Fail the upgrade instead of grandfathering ambiguous or mechanically
-- inconsistent aliases that could authorize the wrong FAA manufacturer.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM aircraft_make_aliases alias
    WHERE alias.normalized_alias = ''
      OR alias.normalized_alias <> trim(alias.normalized_alias)
      OR alias.normalized_alias <> lower(alias.normalized_alias)
      OR alias.normalized_alias !~ '^[a-z0-9]+( [a-z0-9]+)*$'
      OR alias.normalized_alias <>
         trim(regexp_replace(lower(alias.alias), '[^a-z0-9]+', ' ', 'g'))
  ) OR EXISTS (
    SELECT 1
    FROM aircraft_make_aliases left_alias
    JOIN aircraft_make_aliases right_alias
      ON right_alias.id > left_alias.id
     AND right_alias.aircraft_make_id <> left_alias.aircraft_make_id
     AND right_alias.normalized_alias = left_alias.normalized_alias
    LEFT JOIN aircraft_markets left_market
      ON left_market.id = left_alias.aircraft_market_id
    LEFT JOIN aircraft_markets right_market
      ON right_market.id = right_alias.aircraft_market_id
    WHERE (left_alias.valid_to_model_year IS NULL
        OR right_alias.valid_from_model_year IS NULL
        OR left_alias.valid_to_model_year >= right_alias.valid_from_model_year)
      AND (right_alias.valid_to_model_year IS NULL
        OR left_alias.valid_from_model_year IS NULL
        OR right_alias.valid_to_model_year >= left_alias.valid_from_model_year)
      AND (left_alias.aircraft_market_id IS NULL
        OR right_alias.aircraft_market_id IS NULL
        OR left_alias.aircraft_market_id = right_alias.aircraft_market_id
        OR left_market.code = 'GLOBAL'
        OR right_market.code = 'GLOBAL')
  ) OR EXISTS (
    SELECT 1
    FROM aircraft_make_aliases alias
    JOIN aircraft_makes other_make
      ON other_make.id <> alias.aircraft_make_id
    WHERE trim(regexp_replace(lower(other_make.name), '[^a-z0-9]+', ' ', 'g'))
      = alias.normalized_alias
  ) THEN
    RAISE EXCEPTION 'existing aircraft make aliases violate deterministic non-ambiguity';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION validate_aircraft_designation_faa_binding()
RETURNS TRIGGER AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM aircraft_designations designation
    JOIN aircraft_model_families family
      ON family.id = designation.aircraft_model_family_id
    JOIN aircraft_makes make
      ON make.id = family.aircraft_make_id
    JOIN aircraft_identity_decisions decision
      ON decision.id = designation.approval_decision_id
    JOIN curation_evidence_claims claim
      ON claim.id = NEW.identity_evidence_claim_id
    JOIN curation_evidence_sources source
      ON source.id = claim.evidence_source_id
    JOIN faa_registry_snapshots snapshot
      ON snapshot.id = NEW.representative_faa_registry_snapshot_id
    JOIN faa_registry_aircraft_references reference
      ON reference.snapshot_id = snapshot.id
     AND reference.aircraft_code = NEW.faa_aircraft_code
    WHERE designation.id = NEW.aircraft_designation_id
      AND decision.decision_status = 'approved'
      AND decision.decision_action = 'approve_new'
      AND decision.entity_kind = 'designation'
      AND claim.claim_kind = 'identity'
      AND claim.validation_status = 'validated'
      AND source.id = snapshot.evidence_source_id
      AND source.source_tier = 'regulator_primary'
      AND NEW.faa_snapshot_date = snapshot.snapshot_date
      AND NEW.faa_archive_sha256 = snapshot.archive_sha256
      AND lower(regexp_replace(trim(designation.normalized_official_designation), '[^a-zA-Z0-9]', '', 'g'))
        = lower(regexp_replace(trim(reference.model_name), '[^a-zA-Z0-9]', '', 'g'))
      AND (
        lower(regexp_replace(trim(make.name), '[^a-zA-Z0-9]', '', 'g'))
          = lower(regexp_replace(trim(reference.manufacturer_name), '[^a-zA-Z0-9]', '', 'g'))
        OR (
          EXISTS (
            SELECT 1 FROM faa_registry_aircraft registered_aircraft
            WHERE registered_aircraft.snapshot_id = snapshot.id
              AND registered_aircraft.aircraft_code = NEW.faa_aircraft_code
          )
          AND NOT EXISTS (
            SELECT 1
            FROM faa_registry_aircraft registered_aircraft
            WHERE registered_aircraft.snapshot_id = snapshot.id
              AND registered_aircraft.aircraft_code = NEW.faa_aircraft_code
              AND NOT EXISTS (
                SELECT 1
                FROM aircraft_make_aliases alias
                LEFT JOIN aircraft_markets market
                  ON market.id = alias.aircraft_market_id
                WHERE alias.aircraft_make_id = make.id
                  AND lower(regexp_replace(trim(alias.alias), '[^a-zA-Z0-9]', '', 'g'))
                    = lower(regexp_replace(trim(reference.manufacturer_name), '[^a-zA-Z0-9]', '', 'g'))
                  AND (alias.aircraft_market_id IS NULL OR market.code IN ('GLOBAL', 'US'))
                  AND (
                    (registered_aircraft.year_manufactured IS NULL
                      AND alias.valid_from_model_year IS NULL
                      AND alias.valid_to_model_year IS NULL)
                    OR (registered_aircraft.year_manufactured IS NOT NULL
                      AND (alias.valid_from_model_year IS NULL
                        OR alias.valid_from_model_year <= registered_aircraft.year_manufactured)
                      AND (alias.valid_to_model_year IS NULL
                        OR alias.valid_to_model_year >= registered_aircraft.year_manufactured))
                  )
              )
          )
        )
      )
  ) THEN
    RAISE EXCEPTION 'FAA aircraft code binding requires an exact approved designation, applicable manufacturer identity, and regulator evidence';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS aircraft_designation_faa_binding_validate
  ON aircraft_designation_faa_bindings;
CREATE TRIGGER aircraft_designation_faa_binding_validate
BEFORE INSERT ON aircraft_designation_faa_bindings
FOR EACH ROW EXECUTE FUNCTION validate_aircraft_designation_faa_binding();

CREATE OR REPLACE FUNCTION preserve_aircraft_designation_faa_binding()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'FAA aircraft code bindings are immutable';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS aircraft_designation_faa_binding_immutable
  ON aircraft_designation_faa_bindings;
CREATE TRIGGER aircraft_designation_faa_binding_immutable
BEFORE UPDATE OR DELETE ON aircraft_designation_faa_bindings
FOR EACH ROW EXECUTE FUNCTION preserve_aircraft_designation_faa_binding();

CREATE OR REPLACE FUNCTION validate_listing_aircraft_identity_assignment()
RETURNS TRIGGER AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM aircraft_designations designation
    JOIN aircraft_identity_decisions decision
      ON decision.id = designation.approval_decision_id
    JOIN aircraft_identity_decision_claims decision_claim
      ON decision_claim.decision_id = decision.id
    JOIN curation_evidence_claims decision_evidence
      ON decision_evidence.id = decision_claim.evidence_claim_id
    JOIN curation_evidence_sources decision_source
      ON decision_source.id = decision_evidence.evidence_source_id
    JOIN curation_evidence_claims assignment_evidence
      ON assignment_evidence.id = NEW.identity_evidence_claim_id
    JOIN curation_evidence_sources assignment_source
      ON assignment_source.id = assignment_evidence.evidence_source_id
    JOIN faa_registry_snapshots snapshot
      ON snapshot.id = NEW.faa_registry_snapshot_id
    WHERE designation.id = NEW.aircraft_designation_id
      AND decision.id = NEW.identity_decision_id
      AND decision.decision_status = 'approved'
      AND decision.decision_action = 'approve_new'
      AND decision.entity_kind = 'designation'
      AND decision_claim.evidence_role = 'identity'
      AND decision_evidence.validation_status = 'validated'
      AND decision_source.source_tier IN ('manufacturer_primary', 'regulator_primary')
      AND assignment_evidence.claim_kind = 'identity'
      AND assignment_evidence.validation_status = 'validated'
      AND assignment_source.id = snapshot.evidence_source_id
      AND assignment_source.source_tier = 'regulator_primary'
  ) THEN
    RAISE EXCEPTION 'listing aircraft assignment requires immutable designation-decision and current FAA evidence provenance';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM aircraft_sale_listings listing
    JOIN faa_registry_aircraft aircraft
      ON aircraft.snapshot_id = NEW.faa_registry_snapshot_id
     AND aircraft.n_number = NEW.faa_n_number
     AND aircraft.source_record_sha256 = NEW.faa_source_record_sha256
    JOIN faa_registry_aircraft_references reference
      ON reference.snapshot_id = aircraft.snapshot_id
     AND reference.aircraft_code = aircraft.aircraft_code
    JOIN faa_registry_snapshots registry_snapshot
      ON registry_snapshot.id = aircraft.snapshot_id
    JOIN aircraft_designations designation
      ON designation.id = NEW.aircraft_designation_id
    JOIN aircraft_designation_faa_bindings faa_binding
      ON faa_binding.faa_snapshot_date = registry_snapshot.snapshot_date
     AND faa_binding.faa_archive_sha256 = registry_snapshot.archive_sha256
     AND faa_binding.faa_aircraft_code = aircraft.aircraft_code
     AND faa_binding.aircraft_designation_id = designation.id
    JOIN aircraft_makes make
      ON make.id = NEW.aircraft_make_id
    WHERE listing.id = NEW.aircraft_sale_listing_id
      AND upper(regexp_replace(trim(listing.registration_number), '[^a-zA-Z0-9]', '', 'g'))
        = NEW.faa_n_number
      AND length(trim(reference.manufacturer_name)) > 0
      AND length(trim(reference.model_name)) > 0
      AND (
        lower(regexp_replace(trim(make.name), '[^a-zA-Z0-9]', '', 'g'))
          = lower(regexp_replace(trim(reference.manufacturer_name), '[^a-zA-Z0-9]', '', 'g'))
        OR EXISTS (
          SELECT 1
          FROM aircraft_make_aliases alias
          LEFT JOIN aircraft_markets market
            ON market.id = alias.aircraft_market_id
          WHERE alias.aircraft_make_id = make.id
            AND lower(regexp_replace(trim(alias.alias), '[^a-zA-Z0-9]', '', 'g'))
              = lower(regexp_replace(trim(reference.manufacturer_name), '[^a-zA-Z0-9]', '', 'g'))
            AND (alias.aircraft_market_id IS NULL OR market.code IN ('GLOBAL', 'US'))
            AND (alias.valid_from_model_year IS NULL
              OR alias.valid_from_model_year <= listing.model_year)
            AND (alias.valid_to_model_year IS NULL
              OR alias.valid_to_model_year >= listing.model_year)
        )
      )
      AND lower(regexp_replace(trim(designation.normalized_official_designation), '[^a-zA-Z0-9]', '', 'g'))
        = lower(regexp_replace(trim(reference.model_name), '[^a-zA-Z0-9]', '', 'g'))
  ) THEN
    RAISE EXCEPTION 'listing aircraft assignment does not match the exact FAA aircraft identity';
  END IF;

  IF (
    NEW.supersedes_assignment_id IS NULL
    AND EXISTS (
      SELECT 1
      FROM aircraft_sale_listing_identity_assignments prior
      WHERE prior.aircraft_sale_listing_id = NEW.aircraft_sale_listing_id
    )
  ) OR (
    NEW.supersedes_assignment_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1
      FROM aircraft_sale_listing_current_identity_assignments current_assignment
      WHERE current_assignment.aircraft_sale_listing_id = NEW.aircraft_sale_listing_id
        AND current_assignment.identity_assignment_id = NEW.supersedes_assignment_id
    )
  ) THEN
    RAISE EXCEPTION 'listing aircraft assignment must extend the current immutable history';
  END IF;

  IF (
    NEW.aircraft_generation_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1
      FROM aircraft_generation_designations link
      WHERE link.aircraft_generation_id = NEW.aircraft_generation_id
        AND link.aircraft_designation_id = NEW.aircraft_designation_id
    )
  ) OR (
    NEW.aircraft_factory_package_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1
      FROM aircraft_sale_listings listing
      JOIN aircraft_package_applicability applicability
        ON applicability.aircraft_factory_package_id = NEW.aircraft_factory_package_id
       AND applicability.aircraft_designation_id = NEW.aircraft_designation_id
      WHERE listing.id = NEW.aircraft_sale_listing_id
        AND (
          (NEW.aircraft_generation_id IS NULL
            AND applicability.aircraft_generation_id IS NULL)
          OR applicability.aircraft_generation_id IS NULL
          OR applicability.aircraft_generation_id = NEW.aircraft_generation_id
        )
        AND (applicability.valid_from_model_year IS NULL
          OR applicability.valid_from_model_year <= listing.model_year)
        AND (applicability.valid_to_model_year IS NULL
          OR applicability.valid_to_model_year >= listing.model_year)
    )
  ) OR (
    NEW.aircraft_generation_id IS NULL
    AND EXISTS (
      SELECT 1
      FROM aircraft_generation_designations link
      WHERE link.aircraft_designation_id = NEW.aircraft_designation_id
    )
  ) OR (
    NEW.aircraft_factory_package_id IS NULL
    AND EXISTS (
      SELECT 1
      FROM aircraft_sale_listings listing
      JOIN aircraft_package_applicability applicability
        ON applicability.aircraft_designation_id = NEW.aircraft_designation_id
      JOIN aircraft_factory_packages package
        ON package.id = applicability.aircraft_factory_package_id
      WHERE listing.id = NEW.aircraft_sale_listing_id
        AND package.package_kind = 'trim_tier'
        AND (applicability.aircraft_generation_id IS NULL
          OR applicability.aircraft_generation_id = NEW.aircraft_generation_id)
        AND (applicability.valid_from_model_year IS NULL
          OR applicability.valid_from_model_year <= listing.model_year)
        AND (applicability.valid_to_model_year IS NULL
          OR applicability.valid_to_model_year >= listing.model_year)
    )
  ) THEN
    RAISE EXCEPTION 'listing aircraft assignment generation/package is not applicable to the designation and model year';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS listing_identity_assignment_validate
  ON aircraft_sale_listing_identity_assignments;
CREATE TRIGGER listing_identity_assignment_validate
BEFORE INSERT ON aircraft_sale_listing_identity_assignments
FOR EACH ROW EXECUTE FUNCTION validate_listing_aircraft_identity_assignment();

CREATE OR REPLACE FUNCTION preserve_listing_aircraft_identity_assignment()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'DELETE' AND NOT EXISTS (
    SELECT 1 FROM aircraft_sale_listings listing
    WHERE listing.id = OLD.aircraft_sale_listing_id
  ) THEN
    RETURN OLD;
  END IF;
  RAISE EXCEPTION 'listing aircraft identity assignment versions are immutable';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS listing_identity_assignment_immutable
  ON aircraft_sale_listing_identity_assignments;
CREATE TRIGGER listing_identity_assignment_immutable
BEFORE UPDATE OR DELETE ON aircraft_sale_listing_identity_assignments
FOR EACH ROW EXECUTE FUNCTION preserve_listing_aircraft_identity_assignment();

CREATE OR REPLACE FUNCTION validate_listing_current_identity_assignment()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NOT EXISTS (
      SELECT 1
      FROM aircraft_sale_listing_identity_assignments assignment
      WHERE assignment.id = NEW.identity_assignment_id
        AND assignment.aircraft_sale_listing_id = NEW.aircraft_sale_listing_id
        AND assignment.supersedes_assignment_id IS NULL
    ) THEN
      RAISE EXCEPTION 'initial current aircraft identity must select the listing root assignment';
    END IF;
  ELSIF NEW.aircraft_sale_listing_id <> OLD.aircraft_sale_listing_id
    OR NEW.selected_at <= OLD.selected_at
    OR NOT EXISTS (
      SELECT 1
      FROM aircraft_sale_listing_identity_assignments assignment
      WHERE assignment.id = NEW.identity_assignment_id
        AND assignment.aircraft_sale_listing_id = NEW.aircraft_sale_listing_id
        AND assignment.supersedes_assignment_id = OLD.identity_assignment_id
    ) THEN
    RAISE EXCEPTION 'current aircraft identity may advance only to its direct immutable successor';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS listing_current_identity_validate_insert
  ON aircraft_sale_listing_current_identity_assignments;
CREATE TRIGGER listing_current_identity_validate_insert
BEFORE INSERT ON aircraft_sale_listing_current_identity_assignments
FOR EACH ROW EXECUTE FUNCTION validate_listing_current_identity_assignment();

DROP TRIGGER IF EXISTS listing_current_identity_validate_update
  ON aircraft_sale_listing_current_identity_assignments;
CREATE TRIGGER listing_current_identity_validate_update
BEFORE UPDATE
ON aircraft_sale_listing_current_identity_assignments
FOR EACH ROW EXECUTE FUNCTION validate_listing_current_identity_assignment();

CREATE OR REPLACE FUNCTION preserve_listing_current_identity_assignment()
RETURNS TRIGGER AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM aircraft_sale_listings listing
    WHERE listing.id = OLD.aircraft_sale_listing_id
  ) THEN
    RETURN OLD;
  END IF;
  RAISE EXCEPTION 'current aircraft identity may be deleted only with its parent listing';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS listing_current_identity_immutable_delete
  ON aircraft_sale_listing_current_identity_assignments;
CREATE TRIGGER listing_current_identity_immutable_delete
BEFORE DELETE ON aircraft_sale_listing_current_identity_assignments
FOR EACH ROW EXECUTE FUNCTION preserve_listing_current_identity_assignment();

CREATE OR REPLACE FUNCTION preserve_assigned_aircraft_entity()
RETURNS TRIGGER AS $$
DECLARE
  assignment_exists BOOLEAN;
BEGIN
  EXECUTE format(
    'SELECT EXISTS (SELECT 1 FROM aircraft_sale_listing_identity_assignments WHERE %I = $1)',
    TG_ARGV[0]
  ) INTO assignment_exists USING OLD.id;
  IF assignment_exists THEN
    RAISE EXCEPTION 'assigned canonical aircraft hierarchy rows are immutable';
  END IF;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS assigned_aircraft_make_immutable ON aircraft_makes;
CREATE TRIGGER assigned_aircraft_make_immutable
BEFORE UPDATE OR DELETE ON aircraft_makes
FOR EACH ROW EXECUTE FUNCTION preserve_assigned_aircraft_entity('aircraft_make_id');
DROP TRIGGER IF EXISTS assigned_aircraft_family_immutable ON aircraft_model_families;
CREATE TRIGGER assigned_aircraft_family_immutable
BEFORE UPDATE OR DELETE ON aircraft_model_families
FOR EACH ROW EXECUTE FUNCTION preserve_assigned_aircraft_entity('aircraft_model_family_id');
DROP TRIGGER IF EXISTS assigned_aircraft_designation_immutable ON aircraft_designations;
CREATE TRIGGER assigned_aircraft_designation_immutable
BEFORE UPDATE OR DELETE ON aircraft_designations
FOR EACH ROW EXECUTE FUNCTION preserve_assigned_aircraft_entity('aircraft_designation_id');
DROP TRIGGER IF EXISTS assigned_aircraft_generation_immutable ON aircraft_generations;
CREATE TRIGGER assigned_aircraft_generation_immutable
BEFORE UPDATE OR DELETE ON aircraft_generations
FOR EACH ROW EXECUTE FUNCTION preserve_assigned_aircraft_entity('aircraft_generation_id');
DROP TRIGGER IF EXISTS assigned_aircraft_package_immutable ON aircraft_factory_packages;
CREATE TRIGGER assigned_aircraft_package_immutable
BEFORE UPDATE OR DELETE ON aircraft_factory_packages
FOR EACH ROW EXECUTE FUNCTION preserve_assigned_aircraft_entity('aircraft_factory_package_id');

CREATE OR REPLACE FUNCTION preserve_assigned_aircraft_applicability()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_TABLE_NAME = 'aircraft_generation_designations' AND EXISTS (
    SELECT 1 FROM aircraft_sale_listing_identity_assignments assignment
    WHERE assignment.aircraft_generation_id = OLD.aircraft_generation_id
      AND assignment.aircraft_designation_id = OLD.aircraft_designation_id
  ) THEN
    RAISE EXCEPTION 'assigned generation/designation applicability is immutable';
  END IF;
  IF TG_TABLE_NAME = 'aircraft_package_applicability' AND EXISTS (
    SELECT 1 FROM aircraft_sale_listing_identity_assignments assignment
    WHERE assignment.aircraft_factory_package_id = OLD.aircraft_factory_package_id
      AND assignment.aircraft_designation_id = OLD.aircraft_designation_id
      AND (OLD.aircraft_generation_id IS NULL
        OR assignment.aircraft_generation_id = OLD.aircraft_generation_id)
  ) THEN
    RAISE EXCEPTION 'assigned package applicability is immutable';
  END IF;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS assigned_generation_designation_immutable
  ON aircraft_generation_designations;
CREATE TRIGGER assigned_generation_designation_immutable
BEFORE UPDATE OR DELETE ON aircraft_generation_designations
FOR EACH ROW EXECUTE FUNCTION preserve_assigned_aircraft_applicability();
DROP TRIGGER IF EXISTS assigned_package_applicability_immutable
  ON aircraft_package_applicability;
CREATE TRIGGER assigned_package_applicability_immutable
BEFORE UPDATE OR DELETE ON aircraft_package_applicability
FOR EACH ROW EXECUTE FUNCTION preserve_assigned_aircraft_applicability();

CREATE OR REPLACE FUNCTION prevent_new_unresolved_aircraft_dimension()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_TABLE_NAME = 'aircraft_generation_designations' AND EXISTS (
    SELECT 1
    FROM aircraft_sale_listing_current_identity_assignments current_assignment
    JOIN aircraft_sale_listing_identity_assignments assignment
      ON assignment.id = current_assignment.identity_assignment_id
     AND assignment.aircraft_sale_listing_id = current_assignment.aircraft_sale_listing_id
    JOIN aircraft_sale_listings listing
      ON listing.id = current_assignment.aircraft_sale_listing_id
    WHERE listing.ingestion_state = 'ready'
      AND assignment.aircraft_designation_id = NEW.aircraft_designation_id
      AND assignment.aircraft_generation_id IS NULL
  ) THEN
    RAISE EXCEPTION 'adding a generation dimension requires resolving affected ready listing assignments first';
  END IF;
  IF TG_TABLE_NAME = 'aircraft_package_applicability' AND EXISTS (
    SELECT 1
    FROM aircraft_factory_packages package
    CROSS JOIN aircraft_sale_listing_current_identity_assignments current_assignment
    JOIN aircraft_sale_listing_identity_assignments assignment
      ON assignment.id = current_assignment.identity_assignment_id
     AND assignment.aircraft_sale_listing_id = current_assignment.aircraft_sale_listing_id
    JOIN aircraft_sale_listings listing
      ON listing.id = current_assignment.aircraft_sale_listing_id
    WHERE package.id = NEW.aircraft_factory_package_id
      AND package.package_kind = 'trim_tier'
      AND listing.ingestion_state = 'ready'
      AND assignment.aircraft_designation_id = NEW.aircraft_designation_id
      AND assignment.aircraft_factory_package_id IS NULL
      AND (NEW.aircraft_generation_id IS NULL
        OR assignment.aircraft_generation_id = NEW.aircraft_generation_id)
      AND (NEW.valid_from_model_year IS NULL
        OR NEW.valid_from_model_year <= listing.model_year)
      AND (NEW.valid_to_model_year IS NULL
        OR NEW.valid_to_model_year >= listing.model_year)
  ) THEN
    RAISE EXCEPTION 'adding a trim-tier dimension requires resolving affected ready listing assignments first';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS assigned_generation_dimension_requires_resolution
  ON aircraft_generation_designations;
CREATE TRIGGER assigned_generation_dimension_requires_resolution
BEFORE INSERT ON aircraft_generation_designations
FOR EACH ROW EXECUTE FUNCTION prevent_new_unresolved_aircraft_dimension();
DROP TRIGGER IF EXISTS assigned_trim_tier_dimension_requires_resolution
  ON aircraft_package_applicability;
CREATE TRIGGER assigned_trim_tier_dimension_requires_resolution
BEFORE INSERT ON aircraft_package_applicability
FOR EACH ROW EXECUTE FUNCTION prevent_new_unresolved_aircraft_dimension();

-- Existing published rows predate this trust boundary. They cannot remain
-- grandfathered without a current evidence-backed assignment.
UPDATE aircraft_sale_listings
SET ingestion_state = 'quarantined',
    ingestion_error = 'canonical aircraft identity migration: ready listing has no current FAA-backed curated assignment',
    ingestion_completed_at = NULL,
    is_verified = FALSE,
    updated_at = CURRENT_TIMESTAMP
WHERE ingestion_state = 'ready'
  AND NOT EXISTS (
    SELECT 1
    FROM aircraft_sale_listing_current_identity_assignments current_assignment
    WHERE current_assignment.aircraft_sale_listing_id = aircraft_sale_listings.id
  );

CREATE OR REPLACE FUNCTION validate_ready_listing_aircraft_identity()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.ingestion_state = 'ready' AND TG_OP = 'INSERT' THEN
    RAISE EXCEPTION 'listing cannot be inserted ready before canonical aircraft assignment';
  END IF;

  IF NEW.ingestion_state = 'ready' AND NOT EXISTS (
    SELECT 1
    FROM aircraft_sale_listing_current_identity_assignments current_assignment
    JOIN aircraft_sale_listing_identity_assignments assignment
      ON assignment.id = current_assignment.identity_assignment_id
     AND assignment.aircraft_sale_listing_id = NEW.id
    JOIN aircraft_makes canonical_make ON canonical_make.id = assignment.aircraft_make_id
    JOIN aircraft_designations canonical_designation
      ON canonical_designation.id = assignment.aircraft_designation_id
    JOIN faa_registry_snapshots snapshot ON snapshot.id = assignment.faa_registry_snapshot_id
    JOIN faa_registry_aircraft aircraft
      ON aircraft.snapshot_id = snapshot.id
     AND aircraft.n_number = assignment.faa_n_number
     AND aircraft.source_record_sha256 = assignment.faa_source_record_sha256
    JOIN faa_registry_aircraft_references reference
      ON reference.snapshot_id = aircraft.snapshot_id
     AND reference.aircraft_code = aircraft.aircraft_code
    JOIN aircraft_designation_faa_bindings faa_binding
      ON faa_binding.faa_snapshot_date = snapshot.snapshot_date
     AND faa_binding.faa_archive_sha256 = snapshot.archive_sha256
     AND faa_binding.faa_aircraft_code = aircraft.aircraft_code
     AND faa_binding.aircraft_designation_id = assignment.aircraft_designation_id
    WHERE current_assignment.aircraft_sale_listing_id = NEW.id
      AND EXISTS (
        SELECT 1
        FROM faa_registry_snapshots latest_release
        WHERE latest_release.id = (
          SELECT id FROM faa_registry_snapshots
          ORDER BY snapshot_date DESC, id DESC LIMIT 1
        )
          AND latest_release.snapshot_date = snapshot.snapshot_date
          AND latest_release.archive_sha256 = snapshot.archive_sha256
      )
      AND upper(regexp_replace(trim(NEW.registration_number), '[^a-zA-Z0-9]', '', 'g'))
        = assignment.faa_n_number
      AND (
        NEW.serial_number IS NULL
        OR trim(NEW.serial_number) = ''
        OR aircraft.manufacturer_serial_raw IS NULL
        OR upper(regexp_replace(trim(NEW.serial_number), '[^a-zA-Z0-9]', '', 'g'))
          = upper(regexp_replace(trim(aircraft.manufacturer_serial_raw), '[^a-zA-Z0-9]', '', 'g'))
      )
      AND lower(regexp_replace(trim(canonical_designation.normalized_official_designation), '[^a-zA-Z0-9]', '', 'g'))
        = lower(regexp_replace(trim(reference.model_name), '[^a-zA-Z0-9]', '', 'g'))
      AND (
        lower(regexp_replace(trim(canonical_make.name), '[^a-zA-Z0-9]', '', 'g'))
          = lower(regexp_replace(trim(reference.manufacturer_name), '[^a-zA-Z0-9]', '', 'g'))
        OR EXISTS (
          SELECT 1
          FROM aircraft_make_aliases alias
          LEFT JOIN aircraft_markets market
            ON market.id = alias.aircraft_market_id
          WHERE alias.aircraft_make_id = canonical_make.id
            AND lower(regexp_replace(trim(alias.alias), '[^a-zA-Z0-9]', '', 'g'))
              = lower(regexp_replace(trim(reference.manufacturer_name), '[^a-zA-Z0-9]', '', 'g'))
            AND (alias.aircraft_market_id IS NULL OR market.code IN ('GLOBAL', 'US'))
            AND (alias.valid_from_model_year IS NULL
              OR alias.valid_from_model_year <= NEW.model_year)
            AND (alias.valid_to_model_year IS NULL
              OR alias.valid_to_model_year >= NEW.model_year)
          )
      )
      AND (
        (assignment.aircraft_generation_id IS NULL AND NOT EXISTS (
          SELECT 1 FROM aircraft_generation_designations generation_link
          WHERE generation_link.aircraft_designation_id = assignment.aircraft_designation_id
        ))
        OR (assignment.aircraft_generation_id IS NOT NULL AND EXISTS (
          SELECT 1 FROM aircraft_generation_designations generation_link
          WHERE generation_link.aircraft_generation_id = assignment.aircraft_generation_id
            AND generation_link.aircraft_designation_id = assignment.aircraft_designation_id
        ))
      )
      AND (
        (assignment.aircraft_factory_package_id IS NULL AND NOT EXISTS (
          SELECT 1
          FROM aircraft_package_applicability applicability
          JOIN aircraft_factory_packages package
            ON package.id = applicability.aircraft_factory_package_id
          WHERE applicability.aircraft_designation_id = assignment.aircraft_designation_id
            AND package.package_kind = 'trim_tier'
            AND (applicability.aircraft_generation_id IS NULL
              OR applicability.aircraft_generation_id = assignment.aircraft_generation_id)
            AND (applicability.valid_from_model_year IS NULL
              OR applicability.valid_from_model_year <= NEW.model_year)
            AND (applicability.valid_to_model_year IS NULL
              OR applicability.valid_to_model_year >= NEW.model_year)
        ))
        OR (assignment.aircraft_factory_package_id IS NOT NULL AND EXISTS (
          SELECT 1
          FROM aircraft_package_applicability applicability
          WHERE applicability.aircraft_factory_package_id = assignment.aircraft_factory_package_id
            AND applicability.aircraft_designation_id = assignment.aircraft_designation_id
            AND (applicability.aircraft_generation_id IS NULL
              OR applicability.aircraft_generation_id = assignment.aircraft_generation_id)
            AND (applicability.valid_from_model_year IS NULL
              OR applicability.valid_from_model_year <= NEW.model_year)
            AND (applicability.valid_to_model_year IS NULL
              OR applicability.valid_to_model_year >= NEW.model_year)
        ))
      )
  ) THEN
    RAISE EXCEPTION 'ready listing requires a current canonical aircraft assignment matching current FAA identity';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS listing_ready_requires_canonical_aircraft_insert
  ON aircraft_sale_listings;
CREATE TRIGGER listing_ready_requires_canonical_aircraft_insert
BEFORE INSERT ON aircraft_sale_listings
FOR EACH ROW EXECUTE FUNCTION validate_ready_listing_aircraft_identity();

DROP TRIGGER IF EXISTS listing_ready_requires_canonical_aircraft_update
  ON aircraft_sale_listings;
CREATE TRIGGER listing_ready_requires_canonical_aircraft_update
BEFORE UPDATE OF ingestion_state, aircraft_model_variant_id, model_year, registration_number, serial_number
ON aircraft_sale_listings
FOR EACH ROW EXECUTE FUNCTION validate_ready_listing_aircraft_identity();

INSERT INTO public.schema_migration_contracts (
  migration_name, contract_version, contract_fingerprint, installed_at
) VALUES (
  '20260725_listing_aircraft_identity',
  2,
  '63fb5b5213fc9eb2b7b4dcb2b0be3a9f22a80d4acae49f64e68ec1302c1437be',
  CURRENT_TIMESTAMP
)
ON CONFLICT (migration_name) DO NOTHING;

COMMIT;
