-- Add the durable operational queue for automatic listing verification.
-- Only scheduling state and sanitized verifier outcomes are retained.

BEGIN;

CREATE TABLE IF NOT EXISTS schema_migration_contracts (
  migration_name TEXT PRIMARY KEY,
  contract_version INTEGER NOT NULL CHECK (contract_version > 0),
  contract_fingerprint TEXT NOT NULL
    CHECK (contract_fingerprint ~ '^[0-9a-f]{64}$'),
  installed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (length(BTRIM(migration_name)) > 0)
);

DO $migration_guard$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM schema_migration_contracts
    WHERE migration_name = '20260809_listing_verification_runs'
      AND (
        contract_version <> 1
        OR contract_fingerprint <>
          'a8beda24d71517ba07e4a81b2802b2fef97296ae6b2256a7ff493d6af5235232'
      )
  ) THEN
    RAISE EXCEPTION
      'installed listing verification runs migration has a different contract';
  END IF;
END
$migration_guard$;

CREATE TABLE IF NOT EXISTS listing_verification_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  idempotency_key TEXT NOT NULL,
  request_fingerprint TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'running', 'cancelling', 'completed', 'cancelled')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TEXT,
  UNIQUE (owner_user_id, idempotency_key),
  CHECK (length(BTRIM(idempotency_key)) BETWEEN 1 AND 200),
  CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
  CHECK (
    (status IN ('completed', 'cancelled') AND completed_at IS NOT NULL)
    OR
    (status IN ('queued', 'running', 'cancelling') AND completed_at IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_listing_verification_runs_owner
  ON listing_verification_runs (owner_user_id, id);

CREATE TABLE IF NOT EXISTS listing_verification_run_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL
    REFERENCES listing_verification_runs(id) ON DELETE CASCADE,
  listing_id BIGINT NOT NULL
    REFERENCES aircraft_sale_listings(id) ON DELETE CASCADE,
  position BIGINT NOT NULL CHECK (position >= 0),
  status TEXT NOT NULL DEFAULT 'queued'
    CHECK (status IN (
      'queued', 'running', 'verified', 'pending_review',
      'pending_reference', 'blocked', 'failed', 'cancelled'
    )),
  attempt_count BIGINT NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  lease_token TEXT,
  lease_expires_at_epoch_seconds BIGINT,
  outcome_json TEXT,
  reason_code TEXT,
  reason TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at TEXT,
  completed_at TEXT,
  UNIQUE (run_id, position),
  UNIQUE (run_id, listing_id),
  CHECK (lease_token IS NULL OR length(BTRIM(lease_token)) BETWEEN 1 AND 200),
  CHECK (
    (status = 'running'
      AND lease_token IS NOT NULL
      AND lease_expires_at_epoch_seconds IS NOT NULL
      AND started_at IS NOT NULL
      AND completed_at IS NULL)
    OR
    (status <> 'running'
      AND lease_token IS NULL
      AND lease_expires_at_epoch_seconds IS NULL)
  ),
  CHECK (
    (status IN ('queued', 'running') AND completed_at IS NULL)
    OR
    (status IN (
      'verified', 'pending_review', 'pending_reference',
      'blocked', 'failed', 'cancelled'
    ) AND completed_at IS NOT NULL)
  ),
  CHECK (
    outcome_json IS NULL
    OR (
      length(outcome_json) BETWEEN 2 AND 65536
      AND jsonb_typeof(outcome_json::jsonb) = 'object'
    )
  ),
  CHECK (
    status NOT IN (
      'verified', 'pending_review', 'pending_reference', 'blocked'
    )
    OR outcome_json IS NOT NULL
  ),
  CHECK (reason_code IS NULL OR length(BTRIM(reason_code)) BETWEEN 1 AND 100),
  CHECK (reason IS NULL OR length(BTRIM(reason)) BETWEEN 1 AND 2000)
);

CREATE UNIQUE INDEX IF NOT EXISTS
  idx_listing_verification_run_items_one_active_listing
  ON listing_verification_run_items (listing_id)
  WHERE status IN ('queued', 'running');

CREATE UNIQUE INDEX IF NOT EXISTS
  idx_listing_verification_run_items_one_running_per_run
  ON listing_verification_run_items (run_id)
  WHERE status = 'running';

CREATE INDEX IF NOT EXISTS idx_listing_verification_run_items_claim
  ON listing_verification_run_items (run_id, status, position, id);

INSERT INTO schema_migration_contracts (
  migration_name,
  contract_version,
  contract_fingerprint,
  installed_at
) VALUES (
  '20260809_listing_verification_runs',
  1,
  'a8beda24d71517ba07e4a81b2802b2fef97296ae6b2256a7ff493d6af5235232',
  CURRENT_TIMESTAMP
)
ON CONFLICT (migration_name) DO NOTHING;

COMMIT;
