-- Exact, evidence-backed web origins for avionics authority.
--
-- A manufacturer identity authorizes only the exact HTTPS origins recorded
-- here. Subdomains, parent domains, and sibling domains are never inferred.
-- Manufacturer aliases inherit origins only through the approved effective
-- identity graph. The regulator subject is reserved for reviewed regulator
-- origins without conflating them with a manufacturer namespace.

BEGIN;

SET LOCAL search_path = public, pg_catalog;

CREATE TABLE IF NOT EXISTS schema_migration_contracts (
  migration_name TEXT PRIMARY KEY,
  contract_version INTEGER NOT NULL CHECK (contract_version > 0),
  contract_fingerprint TEXT NOT NULL
    CHECK (contract_fingerprint ~ '^[0-9a-f]{64}$'),
  installed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (length(trim(migration_name)) > 0)
);

LOCK TABLE public.schema_migration_contracts
IN SHARE ROW EXCLUSIVE MODE;

DO $migration_guard$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM schema_migration_contracts
    WHERE migration_name = '20260801_avionics_authoritative_source_origins'
      AND (
        contract_version IS DISTINCT FROM 2
        OR contract_fingerprint IS DISTINCT FROM
          'f78087f6354d93d78dc8cebc895f285e38a91ca6f72dc2351acaaa88b49f9620'
      )
  ) THEN
    RAISE EXCEPTION
      'installed avionics authoritative source-origin migration has a different contract';
  END IF;
END
$migration_guard$;

CREATE TABLE IF NOT EXISTS avionics_authoritative_source_origins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  authority_kind TEXT NOT NULL CHECK (authority_kind IN (
    'manufacturer_primary', 'regulator_primary'
  )),
  avionics_manufacturer_identity_id BIGINT
    REFERENCES avionics_manufacturer_identities(id) ON DELETE RESTRICT,
  regulator_key TEXT,
  https_origin TEXT NOT NULL,
  evidence_source_url TEXT NOT NULL,
  evidence_source_title TEXT NOT NULL,
  evidence_text TEXT NOT NULL,
  approval_basis TEXT NOT NULL CHECK (approval_basis IN (
    'curated_bootstrap', 'human_review'
  )),
  approved_by_user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
  approval_reason TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (
    (
      authority_kind = 'manufacturer_primary'
      AND avionics_manufacturer_identity_id IS NOT NULL
      AND regulator_key IS NULL
    )
    OR (
      authority_kind = 'regulator_primary'
      AND avionics_manufacturer_identity_id IS NULL
      AND regulator_key ~ '^[a-z0-9_]+$'
    )
  ),
  CHECK (https_origin = LOWER(BTRIM(https_origin))),
  CHECK (https_origin ~ '^https://[a-z0-9][a-z0-9.-]*[a-z0-9]$'),
  CHECK (POSITION('.' IN SUBSTRING(https_origin FROM 9)) > 1),
  CHECK (POSITION('..' IN SUBSTRING(https_origin FROM 9)) = 0),
  CHECK (POSITION('.-' IN SUBSTRING(https_origin FROM 9)) = 0),
  CHECK (POSITION('-.' IN SUBSTRING(https_origin FROM 9)) = 0),
  CHECK (
    evidence_source_url = https_origin
    OR (
      LEFT(evidence_source_url, LENGTH(https_origin)) = https_origin
      AND SUBSTRING(
        evidence_source_url FROM LENGTH(https_origin) + 1 FOR 1
      ) = '/'
    )
  ),
  CHECK (length(BTRIM(evidence_source_title)) >= 4),
  CHECK (length(BTRIM(evidence_text)) >= 20),
  CHECK (
    (approval_basis = 'curated_bootstrap' AND approved_by_user_id IS NULL)
    OR (approval_basis = 'human_review' AND approved_by_user_id IS NOT NULL)
  ),
  CHECK (length(BTRIM(approval_reason)) >= 10)
);

CREATE UNIQUE INDEX IF NOT EXISTS
  idx_avionics_authoritative_origin_manufacturer
ON avionics_authoritative_source_origins (
  avionics_manufacturer_identity_id, https_origin
)
WHERE authority_kind = 'manufacturer_primary';

CREATE UNIQUE INDEX IF NOT EXISTS
  idx_avionics_authoritative_origin_regulator
ON avionics_authoritative_source_origins (regulator_key, https_origin)
WHERE authority_kind = 'regulator_primary';

CREATE INDEX IF NOT EXISTS idx_avionics_authoritative_origin_lookup
  ON avionics_authoritative_source_origins (
    authority_kind, https_origin, avionics_manufacturer_identity_id
  );

CREATE OR REPLACE FUNCTION preserve_avionics_authoritative_source_origin()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
BEGIN
  RAISE EXCEPTION 'avionics authoritative source origins are immutable and permanent';
  RETURN NULL;
END;
$function$;

DROP TRIGGER IF EXISTS avionics_authoritative_source_origins_immutable
  ON avionics_authoritative_source_origins;
CREATE TRIGGER avionics_authoritative_source_origins_immutable
BEFORE UPDATE OR DELETE ON avionics_authoritative_source_origins
FOR EACH ROW EXECUTE FUNCTION preserve_avionics_authoritative_source_origin();

CREATE TABLE IF NOT EXISTS avionics_authoritative_source_origin_revocations (
  avionics_authoritative_source_origin_id BIGINT PRIMARY KEY
    REFERENCES avionics_authoritative_source_origins(id) ON DELETE RESTRICT,
  revoked_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  reason TEXT NOT NULL CHECK (length(BTRIM(reason)) >= 10),
  revoked_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION preserve_avionics_authoritative_source_origin_revocation()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
BEGIN
  RAISE EXCEPTION 'avionics authoritative source-origin revocations are immutable and permanent';
  RETURN NULL;
END;
$function$;

DROP TRIGGER IF EXISTS
  avionics_authoritative_source_origin_revocations_immutable
  ON avionics_authoritative_source_origin_revocations;
CREATE TRIGGER avionics_authoritative_source_origin_revocations_immutable
BEFORE UPDATE OR DELETE ON avionics_authoritative_source_origin_revocations
FOR EACH ROW
EXECUTE FUNCTION preserve_avionics_authoritative_source_origin_revocation();

CREATE OR REPLACE VIEW avionics_active_authoritative_source_origins AS
SELECT source_origin.*
FROM avionics_authoritative_source_origins source_origin
WHERE NOT EXISTS (
  SELECT 1
  FROM avionics_authoritative_source_origin_revocations revocation
  WHERE revocation.avionics_authoritative_source_origin_id = source_origin.id
);

-- Fresh databases have no curated manufacturer identities while the schema is
-- first installed. When the one reviewed Garmin identity is later inserted,
-- provision only these two fixed origins. This is a Garmin-specific bootstrap,
-- never a rule that derives authority from arbitrary identity evidence URLs.
CREATE OR REPLACE FUNCTION bootstrap_garmin_authoritative_source_origins()
RETURNS TRIGGER LANGUAGE plpgsql AS $function$
BEGIN
  IF NEW.normalized_identity_key = 'garmin'
     AND LOWER(BTRIM(NEW.canonical_name)) = 'garmin'
     AND NEW.identity_evidence_kind = 'authoritative_reference'
     AND NEW.identity_confidence = 'very_high'
     AND LEFT(NEW.identity_source_url, 23) = 'https://www.garmin.com/'
  THEN
    INSERT INTO avionics_authoritative_source_origins (
      authority_kind,
      avionics_manufacturer_identity_id,
      regulator_key,
      https_origin,
      evidence_source_url,
      evidence_source_title,
      evidence_text,
      approval_basis,
      approved_by_user_id,
      approval_reason
    ) VALUES
      (
        'manufacturer_primary',
        NEW.id,
        NULL,
        'https://www.garmin.com',
        'https://www.garmin.com/en-US/p/588901/',
        'Garmin G1000 NXi | Integrated Flight Deck',
        'The Garmin G1000 NXi is an advanced integrated flight deck family designed and manufactured by Garmin',
        'curated_bootstrap',
        NULL,
        'Reviewed first-party Garmin origin bootstrap installed by the 20260801 migration'
      ),
      (
        'manufacturer_primary',
        NEW.id,
        NULL,
        'https://static.garmin.com',
        'https://static.garmin.com/pumac/GIA63_GIA63W_InstallationManual.pdf',
        'Garmin GIA 63/GIA 63W Installation Manual',
        'GIA 63W Unit Only, (011-01105-00) 010-00386-00',
        'curated_bootstrap',
        NULL,
        'Reviewed first-party Garmin origin bootstrap installed by the 20260801 migration'
      )
    ON CONFLICT DO NOTHING;
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS
  avionics_garmin_authoritative_source_origins_bootstrap
  ON avionics_manufacturer_identities;
CREATE TRIGGER avionics_garmin_authoritative_source_origins_bootstrap
AFTER INSERT ON avionics_manufacturer_identities
FOR EACH ROW EXECUTE FUNCTION bootstrap_garmin_authoritative_source_origins();

-- Curated bootstrap. The www and static hosts are independent exact origins;
-- neither row authorizes any other garmin.com subdomain.
INSERT INTO avionics_authoritative_source_origins (
  authority_kind,
  avionics_manufacturer_identity_id,
  regulator_key,
  https_origin,
  evidence_source_url,
  evidence_source_title,
  evidence_text,
  approval_basis,
  approved_by_user_id,
  approval_reason
)
SELECT
  'manufacturer_primary',
  identity.id,
  NULL,
  seed.https_origin,
  seed.evidence_source_url,
  seed.evidence_source_title,
  seed.evidence_text,
  'curated_bootstrap',
  NULL,
  'Reviewed first-party Garmin origin bootstrap installed by the 20260801 migration'
FROM avionics_manufacturer_identities identity
CROSS JOIN (
  VALUES
    (
      'https://www.garmin.com',
      'https://www.garmin.com/en-US/p/588901/',
      'Garmin G1000 NXi | Integrated Flight Deck',
      'The Garmin G1000 NXi is an advanced integrated flight deck family designed and manufactured by Garmin'
    ),
    (
      'https://static.garmin.com',
      'https://static.garmin.com/pumac/GIA63_GIA63W_InstallationManual.pdf',
      'Garmin GIA 63/GIA 63W Installation Manual',
      'GIA 63W Unit Only, (011-01105-00) 010-00386-00'
    )
) seed(
  https_origin, evidence_source_url, evidence_source_title, evidence_text
)
WHERE identity.normalized_identity_key = 'garmin'
  AND LOWER(BTRIM(identity.canonical_name)) = 'garmin'
  AND LEFT(identity.identity_source_url, 23) = 'https://www.garmin.com/'
ON CONFLICT DO NOTHING;

DO $garmin_seed_guard$
BEGIN
  IF EXISTS (
    SELECT 1 FROM avionics_manufacturer_identities
    WHERE normalized_identity_key = 'garmin'
  )
  AND NOT (
    (
      SELECT count(*)
      FROM avionics_manufacturer_identities identity
      WHERE identity.normalized_identity_key = 'garmin'
        AND LOWER(BTRIM(identity.canonical_name)) = 'garmin'
        AND LEFT(identity.identity_source_url, 23) =
          'https://www.garmin.com/'
    ) = 1
    AND (
      SELECT count(*)
      FROM avionics_authoritative_source_origins source_origin
      JOIN avionics_manufacturer_identities identity
        ON identity.id = source_origin.avionics_manufacturer_identity_id
      WHERE identity.normalized_identity_key = 'garmin'
        AND source_origin.authority_kind = 'manufacturer_primary'
        AND source_origin.approval_basis = 'curated_bootstrap'
        AND source_origin.approved_by_user_id IS NULL
        AND source_origin.approval_reason =
          'Reviewed first-party Garmin origin bootstrap installed by the 20260801 migration'
        AND (
          (
            source_origin.https_origin = 'https://www.garmin.com'
            AND source_origin.evidence_source_url =
              'https://www.garmin.com/en-US/p/588901/'
            AND source_origin.evidence_source_title =
              'Garmin G1000 NXi | Integrated Flight Deck'
            AND source_origin.evidence_text =
              'The Garmin G1000 NXi is an advanced integrated flight deck family designed and manufactured by Garmin'
          )
          OR (
            source_origin.https_origin = 'https://static.garmin.com'
            AND source_origin.evidence_source_url =
              'https://static.garmin.com/pumac/GIA63_GIA63W_InstallationManual.pdf'
            AND source_origin.evidence_source_title =
              'Garmin GIA 63/GIA 63W Installation Manual'
            AND source_origin.evidence_text =
              'GIA 63W Unit Only, (011-01105-00) 010-00386-00'
          )
        )
    ) = 2
  ) THEN
    RAISE EXCEPTION
      'Garmin authoritative origins require the reviewed official Garmin identity and exact bootstrap evidence';
  END IF;
END
$garmin_seed_guard$;

INSERT INTO schema_migration_contracts (
  migration_name, contract_version, contract_fingerprint, installed_at
) VALUES (
  '20260801_avionics_authoritative_source_origins',
  2,
  'f78087f6354d93d78dc8cebc895f285e38a91ca6f72dc2351acaaa88b49f9620',
  CURRENT_TIMESTAMP
)
ON CONFLICT (migration_name) DO NOTHING;

COMMIT;
