-- FAA/TCDS-scoped legal-make lineage. A registry manufacturer label is not a
-- global catalog alias: every binding is limited to one exact FAA release,
-- aircraft code, certified model, TCDS document, and safe serial interval.

BEGIN;

SET LOCAL search_path = public, pg_catalog, pg_temp;

CREATE TABLE IF NOT EXISTS schema_migration_contracts (
  migration_name TEXT PRIMARY KEY,
  contract_version INTEGER NOT NULL CHECK (contract_version > 0),
  contract_fingerprint TEXT NOT NULL
    CHECK (contract_fingerprint ~ '^[0-9a-f]{64}$'),
  installed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (length(trim(migration_name)) > 0)
);

LOCK TABLE public.schema_migration_contracts
IN SHARE ROW EXCLUSIVE MODE;

DO $migration_guard$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM schema_migration_contracts
    WHERE migration_name = '20260730_aircraft_tcds_make_lineage'
      AND (
        contract_version IS DISTINCT FROM 1
        OR contract_fingerprint IS DISTINCT FROM
          '566485027d3df81bb5a90abcc0ce2b707e565bcbdc92ae3f007f527832fae735'
      )
  ) THEN
    RAISE EXCEPTION
      'installed FAA/TCDS make-lineage migration has a different contract';
  END IF;
END
$migration_guard$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_faa_registry_aircraft_lineage_record
  ON faa_registry_aircraft (
    snapshot_id,
    n_number,
    source_record_sha256,
    manufacturer_serial_key,
    aircraft_code
  );

CREATE TABLE IF NOT EXISTS aircraft_tcds_make_lineage_bindings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faa_snapshot_date TEXT NOT NULL,
  faa_archive_sha256 TEXT NOT NULL,
  faa_aircraft_code TEXT NOT NULL,
  representative_faa_registry_snapshot_id BIGINT NOT NULL,
  representative_faa_n_number TEXT NOT NULL,
  representative_faa_source_record_sha256 TEXT NOT NULL,
  representative_faa_manufacturer_serial_key TEXT NOT NULL,
  faa_manufacturer_name TEXT NOT NULL,
  faa_model TEXT NOT NULL,
  aircraft_make_id BIGINT NOT NULL
    REFERENCES aircraft_makes(id) ON DELETE RESTRICT,
  aircraft_designation_id BIGINT NOT NULL
    REFERENCES aircraft_designations(id) ON DELETE RESTRICT,
  tcds_number TEXT NOT NULL,
  tcds_document_guid TEXT NOT NULL,
  tcds_pdf_sha256 TEXT NOT NULL,
  tcds_former_holder_name TEXT NOT NULL,
  tcds_current_holder_name TEXT NOT NULL,
  tcds_manufacturer_name TEXT,
  tcds_selection_basis TEXT NOT NULL CHECK (
    tcds_selection_basis IN (
      'registry_reference',
      'drs_unique_current_exact_model',
      'operator_validated_exact_model_serial'
    )
  ),
  serial_scope_kind TEXT NOT NULL
    CHECK (serial_scope_kind IN ('tcds_model', 'manufacturer')),
  serial_prefix TEXT NOT NULL,
  serial_digits_width BIGINT NOT NULL,
  first_serial_number BIGINT NOT NULL,
  last_serial_number BIGINT,
  approval_decision_id BIGINT NOT NULL UNIQUE
    REFERENCES aircraft_identity_decisions(id) ON DELETE RESTRICT,
  faa_make_evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  tcds_model_identity_evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  tcds_serial_applicability_evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  tcds_holder_transfer_evidence_claim_id BIGINT NOT NULL
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  tcds_manufacturer_range_evidence_claim_id BIGINT
    REFERENCES curation_evidence_claims(id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (representative_faa_registry_snapshot_id, faa_aircraft_code)
    REFERENCES faa_registry_aircraft_references(snapshot_id, aircraft_code)
    ON DELETE RESTRICT,
  FOREIGN KEY (
    representative_faa_registry_snapshot_id,
    representative_faa_n_number,
    representative_faa_source_record_sha256,
    representative_faa_manufacturer_serial_key,
    faa_aircraft_code
  ) REFERENCES faa_registry_aircraft (
    snapshot_id,
    n_number,
    source_record_sha256,
    manufacturer_serial_key,
    aircraft_code
  ) ON DELETE RESTRICT,
  CHECK (faa_snapshot_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'),
  CHECK (faa_archive_sha256 ~ '^[0-9a-f]{64}$'),
  CHECK (length(trim(faa_aircraft_code)) > 0),
  CHECK (
    left(representative_faa_n_number, 1) = 'N'
    AND length(representative_faa_n_number) BETWEEN 2 AND 6
  ),
  CHECK (representative_faa_source_record_sha256 ~ '^[0-9a-f]{64}$'),
  CHECK (
    length(representative_faa_manufacturer_serial_key) > 0
    AND representative_faa_manufacturer_serial_key =
      upper(representative_faa_manufacturer_serial_key)
  ),
  CHECK (
    length(trim(faa_manufacturer_name)) > 0
    AND faa_manufacturer_name = trim(faa_manufacturer_name)
  ),
  CHECK (length(trim(faa_model)) > 0 AND faa_model = trim(faa_model)),
  CHECK (length(trim(tcds_number)) > 0 AND tcds_number = trim(tcds_number)),
  CHECK (
    tcds_document_guid ~
      '^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$'
  ),
  CHECK (tcds_pdf_sha256 ~ '^[0-9a-f]{64}$'),
  CHECK (
    length(trim(tcds_former_holder_name)) > 0
    AND tcds_former_holder_name = trim(tcds_former_holder_name)
    AND length(trim(tcds_current_holder_name)) > 0
    AND tcds_current_holder_name = trim(tcds_current_holder_name)
    AND tcds_former_holder_name <> tcds_current_holder_name
  ),
  CHECK (
    tcds_manufacturer_name IS NULL
    OR (
      length(trim(tcds_manufacturer_name)) > 0
      AND tcds_manufacturer_name = trim(tcds_manufacturer_name)
    )
  ),
  CHECK (serial_prefix ~ '^[A-Z]{0,16}$'),
  CHECK (serial_digits_width BETWEEN 1 AND 18),
  CHECK (first_serial_number >= 0),
  CHECK (
    last_serial_number IS NULL
    OR last_serial_number >= first_serial_number
  ),
  CHECK (
    faa_make_evidence_claim_id <> tcds_model_identity_evidence_claim_id
    AND faa_make_evidence_claim_id <>
      tcds_serial_applicability_evidence_claim_id
    AND faa_make_evidence_claim_id <>
      tcds_holder_transfer_evidence_claim_id
    AND tcds_model_identity_evidence_claim_id <>
      tcds_serial_applicability_evidence_claim_id
    AND tcds_model_identity_evidence_claim_id <>
      tcds_holder_transfer_evidence_claim_id
    AND tcds_serial_applicability_evidence_claim_id <>
      tcds_holder_transfer_evidence_claim_id
    AND (
      tcds_manufacturer_range_evidence_claim_id IS NULL
      OR (
        tcds_manufacturer_range_evidence_claim_id <>
          faa_make_evidence_claim_id
        AND tcds_manufacturer_range_evidence_claim_id <>
          tcds_model_identity_evidence_claim_id
        AND tcds_manufacturer_range_evidence_claim_id <>
          tcds_serial_applicability_evidence_claim_id
        AND tcds_manufacturer_range_evidence_claim_id <>
          tcds_holder_transfer_evidence_claim_id
      )
    )
  ),
  CHECK (
    (
      serial_scope_kind = 'tcds_model'
      AND tcds_manufacturer_name IS NULL
      AND tcds_manufacturer_range_evidence_claim_id IS NULL
    )
    OR (
      serial_scope_kind = 'manufacturer'
      AND tcds_manufacturer_name IS NOT NULL
      AND tcds_manufacturer_range_evidence_claim_id IS NOT NULL
    )
  )
);

DROP INDEX IF EXISTS idx_aircraft_tcds_make_lineage_scope;
CREATE UNIQUE INDEX idx_aircraft_tcds_make_lineage_scope
  ON aircraft_tcds_make_lineage_bindings (
    faa_snapshot_date,
    faa_archive_sha256,
    faa_aircraft_code,
    faa_manufacturer_name,
    faa_model,
    serial_prefix,
    serial_digits_width,
    first_serial_number,
    coalesce(last_serial_number, -1)
  );

CREATE INDEX IF NOT EXISTS idx_aircraft_tcds_make_lineage_lookup
  ON aircraft_tcds_make_lineage_bindings (
    faa_snapshot_date,
    faa_archive_sha256,
    faa_aircraft_code,
    aircraft_designation_id,
    faa_manufacturer_name,
    faa_model,
    serial_prefix,
    serial_digits_width,
    first_serial_number,
    last_serial_number
  );

CREATE OR REPLACE FUNCTION validate_aircraft_tcds_make_lineage()
RETURNS TRIGGER AS $function$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM aircraft_tcds_make_lineage_bindings existing
    WHERE existing.faa_snapshot_date = NEW.faa_snapshot_date
      AND existing.faa_archive_sha256 = NEW.faa_archive_sha256
      AND existing.faa_aircraft_code = NEW.faa_aircraft_code
      AND existing.faa_manufacturer_name = NEW.faa_manufacturer_name
      AND existing.faa_model = NEW.faa_model
      AND existing.serial_prefix = NEW.serial_prefix
      AND existing.serial_digits_width = NEW.serial_digits_width
      AND (
        existing.last_serial_number IS NULL
        OR existing.last_serial_number >= NEW.first_serial_number
      )
      AND (
        NEW.last_serial_number IS NULL
        OR NEW.last_serial_number >= existing.first_serial_number
      )
  ) THEN
    RAISE EXCEPTION
      'FAA/TCDS make-lineage serial ranges cannot overlap';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM aircraft_makes other_make
    WHERE other_make.id <> NEW.aircraft_make_id
      AND translate(
        lower(trim(other_make.name)),
        ' -./_,&' || chr(39) || '()',
        ''
      ) = translate(
        lower(trim(NEW.faa_manufacturer_name)),
        ' -./_,&' || chr(39) || '()',
        ''
      )
  ) OR EXISTS (
    SELECT 1
    FROM aircraft_make_aliases alias
    WHERE alias.aircraft_make_id <> NEW.aircraft_make_id
      AND translate(
        lower(trim(alias.alias)),
        ' -./_,&' || chr(39) || '()',
        ''
      ) = translate(
        lower(trim(NEW.faa_manufacturer_name)),
        ' -./_,&' || chr(39) || '()',
        ''
      )
  ) THEN
    RAISE EXCEPTION
      'FAA/TCDS make lineage collides with another canonical make or alias';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM aircraft_identity_decisions decision
    JOIN aircraft_identity_decision_claims faa_link
      ON faa_link.decision_id = decision.id
     AND faa_link.evidence_claim_id = NEW.faa_make_evidence_claim_id
     AND faa_link.evidence_role = 'identity'
    JOIN aircraft_identity_decision_claims model_link
      ON model_link.decision_id = decision.id
     AND model_link.evidence_claim_id =
       NEW.tcds_model_identity_evidence_claim_id
     AND model_link.evidence_role = 'identity'
    JOIN aircraft_identity_decision_claims serial_link
      ON serial_link.decision_id = decision.id
     AND serial_link.evidence_claim_id =
       NEW.tcds_serial_applicability_evidence_claim_id
     AND serial_link.evidence_role = 'applicability'
    JOIN aircraft_identity_decision_claims holder_link
      ON holder_link.decision_id = decision.id
     AND holder_link.evidence_claim_id =
       NEW.tcds_holder_transfer_evidence_claim_id
     AND holder_link.evidence_role = 'identity'
    JOIN curation_evidence_claims faa_claim
      ON faa_claim.id = NEW.faa_make_evidence_claim_id
    JOIN curation_evidence_sources faa_source
      ON faa_source.id = faa_claim.evidence_source_id
    JOIN curation_evidence_claims model_claim
      ON model_claim.id = NEW.tcds_model_identity_evidence_claim_id
    JOIN curation_evidence_sources model_source
      ON model_source.id = model_claim.evidence_source_id
    JOIN curation_evidence_claims serial_claim
      ON serial_claim.id =
        NEW.tcds_serial_applicability_evidence_claim_id
    JOIN curation_evidence_sources serial_source
      ON serial_source.id = serial_claim.evidence_source_id
    JOIN curation_evidence_claims holder_claim
      ON holder_claim.id = NEW.tcds_holder_transfer_evidence_claim_id
    JOIN curation_evidence_sources holder_source
      ON holder_source.id = holder_claim.evidence_source_id
    JOIN faa_registry_snapshots snapshot
      ON snapshot.id = NEW.representative_faa_registry_snapshot_id
    JOIN faa_registry_aircraft_references reference
      ON reference.snapshot_id = snapshot.id
     AND reference.aircraft_code = NEW.faa_aircraft_code
    JOIN aircraft_designations designation
      ON designation.id = NEW.aircraft_designation_id
    JOIN aircraft_model_families family
      ON family.id = designation.aircraft_model_family_id
     AND family.aircraft_make_id = NEW.aircraft_make_id
    JOIN aircraft_makes canonical_make
      ON canonical_make.id = family.aircraft_make_id
    WHERE decision.id = NEW.approval_decision_id
      AND decision.entity_kind = 'make'
      AND decision.decision_action = 'match_existing'
      AND decision.decision_status = 'approved'
      AND decision.deterministic_validation_passed = TRUE
      AND decision.selected_entity_id = NEW.aircraft_make_id
      AND faa_claim.claim_kind = 'identity'
      AND faa_claim.validation_status = 'validated'
      AND faa_source.id = snapshot.evidence_source_id
      AND faa_source.source_tier = 'regulator_primary'
      AND model_claim.claim_kind = 'identity'
      AND model_claim.validation_status = 'validated'
      AND model_source.source_tier = 'regulator_primary'
      AND model_source.content_sha256 = NEW.tcds_pdf_sha256
      AND serial_claim.claim_kind = 'applicability'
      AND serial_claim.validation_status = 'validated'
      AND serial_source.id = model_source.id
      AND holder_claim.claim_kind = 'identity'
      AND holder_claim.validation_status = 'validated'
      AND holder_source.id = model_source.id
      AND model_source.source_url =
        'https://drs.faa.gov/api/drs/data-pull/download/'
        || NEW.tcds_document_guid
      AND NEW.faa_snapshot_date = snapshot.snapshot_date
      AND NEW.faa_archive_sha256 = snapshot.archive_sha256
      AND NEW.faa_manufacturer_name = reference.manufacturer_name
      AND NEW.faa_model = reference.model_name
      AND lower(regexp_replace(
        designation.normalized_official_designation,
        '[^a-zA-Z0-9]', '', 'g'
      )) = lower(regexp_replace(
        reference.model_name, '[^a-zA-Z0-9]', '', 'g'
      ))
      AND (
        (
          NEW.tcds_selection_basis = 'registry_reference'
          AND length(trim(coalesce(
            reference.type_certificate_data_sheet, ''
          ))) > 0
          AND NEW.tcds_number =
            trim(reference.type_certificate_data_sheet)
        )
        OR (
          NEW.tcds_selection_basis IN (
            'drs_unique_current_exact_model',
            'operator_validated_exact_model_serial'
          )
          AND length(trim(coalesce(
            reference.type_certificate_data_sheet, ''
          ))) = 0
        )
      )
      AND (
        lower(rtrim(btrim(canonical_make.name), '.')) =
          lower(rtrim(btrim(NEW.tcds_former_holder_name), '.'))
        OR lower(rtrim(btrim(canonical_make.name), '.')) =
          lower(rtrim(btrim(NEW.tcds_current_holder_name), '.'))
      )
      AND (
        NEW.tcds_manufacturer_name IS NULL
        OR lower(rtrim(btrim(NEW.tcds_manufacturer_name), '.')) =
          lower(rtrim(btrim(NEW.tcds_former_holder_name), '.'))
        OR lower(rtrim(btrim(NEW.tcds_manufacturer_name), '.')) =
          lower(rtrim(btrim(NEW.tcds_current_holder_name), '.'))
      )
      AND (
        NEW.tcds_manufacturer_range_evidence_claim_id IS NULL
        OR EXISTS (
          SELECT 1
          FROM aircraft_identity_decision_claims manufacturer_link
          JOIN curation_evidence_claims manufacturer_claim
            ON manufacturer_claim.id =
              manufacturer_link.evidence_claim_id
          WHERE manufacturer_link.decision_id = decision.id
            AND manufacturer_link.evidence_claim_id =
              NEW.tcds_manufacturer_range_evidence_claim_id
            AND manufacturer_link.evidence_role = 'applicability'
            AND manufacturer_claim.claim_kind = 'applicability'
            AND manufacturer_claim.validation_status = 'validated'
            AND manufacturer_claim.evidence_source_id = model_source.id
        )
      )
      AND EXISTS (
        SELECT 1
        FROM faa_registry_aircraft aircraft
        WHERE aircraft.snapshot_id = snapshot.id
          AND aircraft.n_number = NEW.representative_faa_n_number
          AND aircraft.source_record_sha256 =
            NEW.representative_faa_source_record_sha256
          AND aircraft.manufacturer_serial_key =
            NEW.representative_faa_manufacturer_serial_key
          AND aircraft.aircraft_code = NEW.faa_aircraft_code
          AND aircraft.manufacturer_serial_key IS NOT NULL
          AND length(aircraft.manufacturer_serial_key) =
            length(NEW.serial_prefix) + NEW.serial_digits_width
          AND left(
            aircraft.manufacturer_serial_key, length(NEW.serial_prefix)
          ) = NEW.serial_prefix
          AND substring(
            aircraft.manufacturer_serial_key
            FROM length(NEW.serial_prefix) + 1
          ) ~ '^[0-9]+$'
          AND CAST(substring(
            aircraft.manufacturer_serial_key
            FROM length(NEW.serial_prefix) + 1
          ) AS BIGINT) >= NEW.first_serial_number
          AND (
            NEW.last_serial_number IS NULL
            OR CAST(substring(
              aircraft.manufacturer_serial_key
              FROM length(NEW.serial_prefix) + 1
            ) AS BIGINT) <= NEW.last_serial_number
          )
      )
  ) THEN
    RAISE EXCEPTION
      'FAA/TCDS make lineage requires distinct FAA make, TCDS model, serial-applicability, and holder-transfer evidence';
  END IF;
  RETURN NEW;
END;
$function$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS aircraft_tcds_make_lineage_validate
  ON aircraft_tcds_make_lineage_bindings;
CREATE TRIGGER aircraft_tcds_make_lineage_validate
BEFORE INSERT ON aircraft_tcds_make_lineage_bindings
FOR EACH ROW EXECUTE FUNCTION validate_aircraft_tcds_make_lineage();

CREATE OR REPLACE FUNCTION preserve_aircraft_tcds_make_lineage()
RETURNS TRIGGER AS $function$
BEGIN
  RAISE EXCEPTION
    'approved FAA/TCDS make-lineage bindings are immutable';
END;
$function$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS aircraft_tcds_make_lineage_immutable
  ON aircraft_tcds_make_lineage_bindings;
CREATE TRIGGER aircraft_tcds_make_lineage_immutable
BEFORE UPDATE OR DELETE ON aircraft_tcds_make_lineage_bindings
FOR EACH ROW EXECUTE FUNCTION preserve_aircraft_tcds_make_lineage();

CREATE OR REPLACE FUNCTION aircraft_tcds_make_lineage_matches(
  wanted_snapshot_date TEXT,
  wanted_archive_sha256 TEXT,
  wanted_aircraft_code TEXT,
  wanted_make_id BIGINT,
  wanted_designation_id BIGINT,
  wanted_faa_make TEXT,
  wanted_faa_model TEXT,
  wanted_serial_key TEXT
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $function$
  SELECT count(*) = 1
  FROM aircraft_tcds_make_lineage_bindings binding
  WHERE binding.faa_snapshot_date = wanted_snapshot_date
    AND binding.faa_archive_sha256 = wanted_archive_sha256
    AND binding.faa_aircraft_code = wanted_aircraft_code
    AND binding.aircraft_make_id = wanted_make_id
    AND binding.aircraft_designation_id = wanted_designation_id
    AND binding.faa_manufacturer_name = wanted_faa_make
    AND binding.faa_model = wanted_faa_model
    AND length(wanted_serial_key) =
      length(binding.serial_prefix) + binding.serial_digits_width
    AND left(wanted_serial_key, length(binding.serial_prefix)) =
      binding.serial_prefix
    AND substring(
      wanted_serial_key FROM length(binding.serial_prefix) + 1
    ) ~ '^[0-9]+$'
    AND CAST(substring(
      wanted_serial_key FROM length(binding.serial_prefix) + 1
    ) AS BIGINT) >= binding.first_serial_number
    AND (
      binding.last_serial_number IS NULL
      OR CAST(substring(
        wanted_serial_key FROM length(binding.serial_prefix) + 1
      ) AS BIGINT) <= binding.last_serial_number
    );
$function$;

CREATE OR REPLACE FUNCTION prevent_aircraft_make_lineage_label_collision()
RETURNS TRIGGER AS $function$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM aircraft_tcds_make_lineage_bindings binding
    WHERE binding.aircraft_make_id <> coalesce(NEW.id, -1)
      AND translate(
        lower(trim(NEW.name)),
        ' -./_,&' || chr(39) || '()',
        ''
      ) = translate(
        lower(trim(binding.faa_manufacturer_name)),
        ' -./_,&' || chr(39) || '()',
        ''
      )
  ) THEN
    RAISE EXCEPTION
      'canonical aircraft make collides with an approved FAA/TCDS lineage label';
  END IF;
  RETURN NEW;
END;
$function$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS aircraft_make_tcds_lineage_collision
  ON aircraft_makes;
CREATE TRIGGER aircraft_make_tcds_lineage_collision
BEFORE INSERT OR UPDATE OF name, normalized_name ON aircraft_makes
FOR EACH ROW EXECUTE FUNCTION prevent_aircraft_make_lineage_label_collision();

CREATE OR REPLACE FUNCTION prevent_aircraft_make_alias_lineage_collision()
RETURNS TRIGGER AS $function$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM aircraft_tcds_make_lineage_bindings binding
    WHERE binding.aircraft_make_id <> NEW.aircraft_make_id
      AND translate(
        lower(trim(NEW.alias)),
        ' -./_,&' || chr(39) || '()',
        ''
      ) = translate(
        lower(trim(binding.faa_manufacturer_name)),
        ' -./_,&' || chr(39) || '()',
        ''
      )
  ) THEN
    RAISE EXCEPTION
      'aircraft make alias collides with an approved FAA/TCDS lineage label';
  END IF;
  RETURN NEW;
END;
$function$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS aircraft_make_alias_tcds_lineage_collision
  ON aircraft_make_aliases;
CREATE TRIGGER aircraft_make_alias_tcds_lineage_collision
BEFORE INSERT OR UPDATE OF aircraft_make_id, alias, normalized_alias
ON aircraft_make_aliases
FOR EACH ROW
EXECUTE FUNCTION prevent_aircraft_make_alias_lineage_collision();

CREATE OR REPLACE FUNCTION validate_aircraft_designation_faa_binding()
RETURNS TRIGGER AS $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM aircraft_designations designation
    JOIN aircraft_model_families family
      ON family.id = designation.aircraft_model_family_id
    JOIN aircraft_makes make
      ON make.id = family.aircraft_make_id
    JOIN aircraft_identity_decisions decision
      ON decision.id = designation.approval_decision_id
    JOIN curation_evidence_claims claim
      ON claim.id = NEW.identity_evidence_claim_id
    JOIN curation_evidence_sources source
      ON source.id = claim.evidence_source_id
    JOIN faa_registry_snapshots snapshot
      ON snapshot.id = NEW.representative_faa_registry_snapshot_id
    JOIN faa_registry_aircraft_references reference
      ON reference.snapshot_id = snapshot.id
     AND reference.aircraft_code = NEW.faa_aircraft_code
    WHERE designation.id = NEW.aircraft_designation_id
      AND decision.decision_status = 'approved'
      AND decision.decision_action = 'approve_new'
      AND decision.entity_kind = 'designation'
      AND claim.claim_kind = 'identity'
      AND claim.validation_status = 'validated'
      AND source.id = snapshot.evidence_source_id
      AND source.source_tier = 'regulator_primary'
      AND NEW.faa_snapshot_date = snapshot.snapshot_date
      AND NEW.faa_archive_sha256 = snapshot.archive_sha256
      AND lower(regexp_replace(
        trim(designation.normalized_official_designation),
        '[^a-zA-Z0-9]', '', 'g'
      )) = lower(regexp_replace(
        trim(reference.model_name), '[^a-zA-Z0-9]', '', 'g'
      ))
      AND (
        lower(regexp_replace(
          trim(make.name), '[^a-zA-Z0-9]', '', 'g'
        )) = lower(regexp_replace(
          trim(reference.manufacturer_name), '[^a-zA-Z0-9]', '', 'g'
        ))
        OR (
          EXISTS (
            SELECT 1
            FROM faa_registry_aircraft registered_aircraft
            WHERE registered_aircraft.snapshot_id = snapshot.id
              AND registered_aircraft.aircraft_code =
                NEW.faa_aircraft_code
          )
          AND NOT EXISTS (
            SELECT 1
            FROM faa_registry_aircraft registered_aircraft
            WHERE registered_aircraft.snapshot_id = snapshot.id
              AND registered_aircraft.aircraft_code =
                NEW.faa_aircraft_code
              AND NOT EXISTS (
                SELECT 1
                FROM aircraft_make_aliases alias
                LEFT JOIN aircraft_markets market
                  ON market.id = alias.aircraft_market_id
                WHERE alias.aircraft_make_id = make.id
                  AND lower(regexp_replace(
                    trim(alias.alias), '[^a-zA-Z0-9]', '', 'g'
                  )) = lower(regexp_replace(
                    trim(reference.manufacturer_name),
                    '[^a-zA-Z0-9]', '', 'g'
                  ))
                  AND (
                    alias.aircraft_market_id IS NULL
                    OR market.code IN ('GLOBAL', 'US')
                  )
                  AND (
                    (
                      registered_aircraft.year_manufactured IS NULL
                      AND alias.valid_from_model_year IS NULL
                      AND alias.valid_to_model_year IS NULL
                    )
                    OR (
                      registered_aircraft.year_manufactured IS NOT NULL
                      AND (
                        alias.valid_from_model_year IS NULL
                        OR alias.valid_from_model_year <=
                          registered_aircraft.year_manufactured
                      )
                      AND (
                        alias.valid_to_model_year IS NULL
                        OR alias.valid_to_model_year >=
                          registered_aircraft.year_manufactured
                      )
                    )
                  )
              )
          )
        )
        OR EXISTS (
          SELECT 1
          FROM faa_registry_aircraft registered_aircraft
          WHERE registered_aircraft.snapshot_id = snapshot.id
            AND registered_aircraft.aircraft_code =
              NEW.faa_aircraft_code
            AND registered_aircraft.manufacturer_serial_key IS NOT NULL
            AND aircraft_tcds_make_lineage_matches(
              snapshot.snapshot_date,
              snapshot.archive_sha256,
              registered_aircraft.aircraft_code,
              make.id,
              designation.id,
              reference.manufacturer_name,
              reference.model_name,
              registered_aircraft.manufacturer_serial_key
            )
        )
      )
  ) THEN
    RAISE EXCEPTION
      'FAA aircraft code binding requires an exact approved designation, applicable manufacturer identity, and regulator evidence';
  END IF;
  RETURN NEW;
END;
$function$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS aircraft_designation_faa_binding_validate
  ON aircraft_designation_faa_bindings;
CREATE TRIGGER aircraft_designation_faa_binding_validate
BEFORE INSERT ON aircraft_designation_faa_bindings
FOR EACH ROW EXECUTE FUNCTION validate_aircraft_designation_faa_binding();

CREATE OR REPLACE FUNCTION validate_listing_aircraft_identity_assignment()
RETURNS TRIGGER AS $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM aircraft_designations designation
    JOIN aircraft_identity_decisions decision
      ON decision.id = designation.approval_decision_id
    JOIN aircraft_identity_decision_claims decision_claim
      ON decision_claim.decision_id = decision.id
    JOIN curation_evidence_claims decision_evidence
      ON decision_evidence.id = decision_claim.evidence_claim_id
    JOIN curation_evidence_sources decision_source
      ON decision_source.id = decision_evidence.evidence_source_id
    JOIN curation_evidence_claims assignment_evidence
      ON assignment_evidence.id = NEW.identity_evidence_claim_id
    JOIN curation_evidence_sources assignment_source
      ON assignment_source.id = assignment_evidence.evidence_source_id
    JOIN faa_registry_snapshots snapshot
      ON snapshot.id = NEW.faa_registry_snapshot_id
    WHERE designation.id = NEW.aircraft_designation_id
      AND decision.id = NEW.identity_decision_id
      AND decision.decision_status = 'approved'
      AND decision.decision_action = 'approve_new'
      AND decision.entity_kind = 'designation'
      AND decision_claim.evidence_role = 'identity'
      AND decision_evidence.validation_status = 'validated'
      AND decision_source.source_tier IN (
        'manufacturer_primary', 'regulator_primary'
      )
      AND assignment_evidence.claim_kind = 'identity'
      AND assignment_evidence.validation_status = 'validated'
      AND assignment_source.id = snapshot.evidence_source_id
      AND assignment_source.source_tier = 'regulator_primary'
  ) THEN
    RAISE EXCEPTION
      'listing aircraft assignment requires immutable designation-decision and current FAA evidence provenance';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM aircraft_sale_listings listing
    JOIN faa_registry_aircraft aircraft
      ON aircraft.snapshot_id = NEW.faa_registry_snapshot_id
     AND aircraft.n_number = NEW.faa_n_number
     AND aircraft.source_record_sha256 =
       NEW.faa_source_record_sha256
    JOIN faa_registry_aircraft_references reference
      ON reference.snapshot_id = aircraft.snapshot_id
     AND reference.aircraft_code = aircraft.aircraft_code
    JOIN faa_registry_snapshots registry_snapshot
      ON registry_snapshot.id = aircraft.snapshot_id
    JOIN aircraft_designations designation
      ON designation.id = NEW.aircraft_designation_id
    JOIN aircraft_designation_faa_bindings faa_binding
      ON faa_binding.faa_snapshot_date =
        registry_snapshot.snapshot_date
     AND faa_binding.faa_archive_sha256 =
       registry_snapshot.archive_sha256
     AND faa_binding.faa_aircraft_code = aircraft.aircraft_code
     AND faa_binding.aircraft_designation_id = designation.id
    JOIN aircraft_makes make
      ON make.id = NEW.aircraft_make_id
    WHERE listing.id = NEW.aircraft_sale_listing_id
      AND upper(regexp_replace(
        trim(listing.registration_number), '[^a-zA-Z0-9]', '', 'g'
      )) = NEW.faa_n_number
      AND length(trim(reference.manufacturer_name)) > 0
      AND length(trim(reference.model_name)) > 0
      AND (
        lower(regexp_replace(
          trim(make.name), '[^a-zA-Z0-9]', '', 'g'
        )) = lower(regexp_replace(
          trim(reference.manufacturer_name), '[^a-zA-Z0-9]', '', 'g'
        ))
        OR EXISTS (
          SELECT 1
          FROM aircraft_make_aliases alias
          LEFT JOIN aircraft_markets market
            ON market.id = alias.aircraft_market_id
          WHERE alias.aircraft_make_id = make.id
            AND lower(regexp_replace(
              trim(alias.alias), '[^a-zA-Z0-9]', '', 'g'
            )) = lower(regexp_replace(
              trim(reference.manufacturer_name),
              '[^a-zA-Z0-9]', '', 'g'
            ))
            AND (
              alias.aircraft_market_id IS NULL
              OR market.code IN ('GLOBAL', 'US')
            )
            AND (
              alias.valid_from_model_year IS NULL
              OR alias.valid_from_model_year <= listing.model_year
            )
            AND (
              alias.valid_to_model_year IS NULL
              OR alias.valid_to_model_year >= listing.model_year
            )
        )
        OR (
          aircraft.manufacturer_serial_key IS NOT NULL
          AND aircraft_tcds_make_lineage_matches(
            registry_snapshot.snapshot_date,
            registry_snapshot.archive_sha256,
            aircraft.aircraft_code,
            make.id,
            designation.id,
            reference.manufacturer_name,
            reference.model_name,
            aircraft.manufacturer_serial_key
          )
        )
      )
      AND lower(regexp_replace(
        trim(designation.normalized_official_designation),
        '[^a-zA-Z0-9]', '', 'g'
      )) = lower(regexp_replace(
        trim(reference.model_name), '[^a-zA-Z0-9]', '', 'g'
      ))
  ) THEN
    RAISE EXCEPTION
      'listing aircraft assignment does not match the exact FAA aircraft identity';
  END IF;

  IF (
    NEW.supersedes_assignment_id IS NULL
    AND EXISTS (
      SELECT 1
      FROM aircraft_sale_listing_identity_assignments prior
      WHERE prior.aircraft_sale_listing_id =
        NEW.aircraft_sale_listing_id
    )
  ) OR (
    NEW.supersedes_assignment_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1
      FROM aircraft_sale_listing_current_identity_assignments current_assignment
      WHERE current_assignment.aircraft_sale_listing_id =
        NEW.aircraft_sale_listing_id
        AND current_assignment.identity_assignment_id =
          NEW.supersedes_assignment_id
    )
  ) THEN
    RAISE EXCEPTION
      'listing aircraft assignment must extend the current immutable history';
  END IF;

  IF (
    NEW.aircraft_generation_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1
      FROM aircraft_generation_designations link
      WHERE link.aircraft_generation_id =
        NEW.aircraft_generation_id
        AND link.aircraft_designation_id =
          NEW.aircraft_designation_id
    )
  ) OR (
    NEW.aircraft_factory_package_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1
      FROM aircraft_sale_listings listing
      JOIN aircraft_package_applicability applicability
        ON applicability.aircraft_factory_package_id =
          NEW.aircraft_factory_package_id
       AND applicability.aircraft_designation_id =
         NEW.aircraft_designation_id
      WHERE listing.id = NEW.aircraft_sale_listing_id
        AND (
          (
            NEW.aircraft_generation_id IS NULL
            AND applicability.aircraft_generation_id IS NULL
          )
          OR applicability.aircraft_generation_id IS NULL
          OR applicability.aircraft_generation_id =
            NEW.aircraft_generation_id
        )
        AND (
          applicability.valid_from_model_year IS NULL
          OR applicability.valid_from_model_year <= listing.model_year
        )
        AND (
          applicability.valid_to_model_year IS NULL
          OR applicability.valid_to_model_year >= listing.model_year
        )
    )
  ) OR (
    NEW.aircraft_generation_id IS NULL
    AND EXISTS (
      SELECT 1
      FROM aircraft_generation_designations link
      WHERE link.aircraft_designation_id =
        NEW.aircraft_designation_id
    )
  ) OR (
    NEW.aircraft_factory_package_id IS NULL
    AND EXISTS (
      SELECT 1
      FROM aircraft_sale_listings listing
      JOIN aircraft_package_applicability applicability
        ON applicability.aircraft_designation_id =
          NEW.aircraft_designation_id
      JOIN aircraft_factory_packages package
        ON package.id = applicability.aircraft_factory_package_id
      WHERE listing.id = NEW.aircraft_sale_listing_id
        AND package.package_kind = 'trim_tier'
        AND (
          applicability.aircraft_generation_id IS NULL
          OR applicability.aircraft_generation_id =
            NEW.aircraft_generation_id
        )
        AND (
          applicability.valid_from_model_year IS NULL
          OR applicability.valid_from_model_year <= listing.model_year
        )
        AND (
          applicability.valid_to_model_year IS NULL
          OR applicability.valid_to_model_year >= listing.model_year
        )
    )
  ) THEN
    RAISE EXCEPTION
      'listing aircraft assignment generation/package is not applicable to the designation and model year';
  END IF;

  RETURN NEW;
END;
$function$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS listing_identity_assignment_validate
  ON aircraft_sale_listing_identity_assignments;
CREATE TRIGGER listing_identity_assignment_validate
BEFORE INSERT ON aircraft_sale_listing_identity_assignments
FOR EACH ROW
EXECUTE FUNCTION validate_listing_aircraft_identity_assignment();

CREATE OR REPLACE FUNCTION validate_ready_listing_aircraft_identity()
RETURNS TRIGGER AS $function$
BEGIN
  IF NEW.ingestion_state = 'ready' AND TG_OP = 'INSERT' THEN
    RAISE EXCEPTION
      'listing cannot be inserted ready before canonical aircraft assignment';
  END IF;

  IF NEW.ingestion_state = 'ready' AND NOT EXISTS (
    SELECT 1
    FROM aircraft_sale_listing_current_identity_assignments current_assignment
    JOIN aircraft_sale_listing_identity_assignments assignment
      ON assignment.id = current_assignment.identity_assignment_id
     AND assignment.aircraft_sale_listing_id = NEW.id
    JOIN aircraft_makes canonical_make
      ON canonical_make.id = assignment.aircraft_make_id
    JOIN aircraft_designations canonical_designation
      ON canonical_designation.id = assignment.aircraft_designation_id
    JOIN faa_registry_snapshots snapshot
      ON snapshot.id = assignment.faa_registry_snapshot_id
    JOIN faa_registry_aircraft aircraft
      ON aircraft.snapshot_id = snapshot.id
     AND aircraft.n_number = assignment.faa_n_number
     AND aircraft.source_record_sha256 =
       assignment.faa_source_record_sha256
    JOIN faa_registry_aircraft_references reference
      ON reference.snapshot_id = aircraft.snapshot_id
     AND reference.aircraft_code = aircraft.aircraft_code
    JOIN aircraft_designation_faa_bindings faa_binding
      ON faa_binding.faa_snapshot_date = snapshot.snapshot_date
     AND faa_binding.faa_archive_sha256 = snapshot.archive_sha256
     AND faa_binding.faa_aircraft_code = aircraft.aircraft_code
     AND faa_binding.aircraft_designation_id =
       assignment.aircraft_designation_id
    WHERE current_assignment.aircraft_sale_listing_id = NEW.id
      AND EXISTS (
        SELECT 1
        FROM faa_registry_snapshots latest_release
        WHERE latest_release.id = (
          SELECT id
          FROM faa_registry_snapshots
          ORDER BY snapshot_date DESC, id DESC
          LIMIT 1
        )
          AND latest_release.snapshot_date = snapshot.snapshot_date
          AND latest_release.archive_sha256 = snapshot.archive_sha256
      )
      AND upper(regexp_replace(
        trim(NEW.registration_number), '[^a-zA-Z0-9]', '', 'g'
      )) = assignment.faa_n_number
      AND (
        NEW.serial_number IS NULL
        OR trim(NEW.serial_number) = ''
        OR aircraft.manufacturer_serial_raw IS NULL
        OR upper(regexp_replace(
          trim(NEW.serial_number), '[^a-zA-Z0-9]', '', 'g'
        )) = upper(regexp_replace(
          trim(aircraft.manufacturer_serial_raw),
          '[^a-zA-Z0-9]', '', 'g'
        ))
      )
      AND lower(regexp_replace(
        trim(canonical_designation.normalized_official_designation),
        '[^a-zA-Z0-9]', '', 'g'
      )) = lower(regexp_replace(
        trim(reference.model_name), '[^a-zA-Z0-9]', '', 'g'
      ))
      AND (
        lower(regexp_replace(
          trim(canonical_make.name), '[^a-zA-Z0-9]', '', 'g'
        )) = lower(regexp_replace(
          trim(reference.manufacturer_name), '[^a-zA-Z0-9]', '', 'g'
        ))
        OR EXISTS (
          SELECT 1
          FROM aircraft_make_aliases alias
          LEFT JOIN aircraft_markets market
            ON market.id = alias.aircraft_market_id
          WHERE alias.aircraft_make_id = canonical_make.id
            AND lower(regexp_replace(
              trim(alias.alias), '[^a-zA-Z0-9]', '', 'g'
            )) = lower(regexp_replace(
              trim(reference.manufacturer_name),
              '[^a-zA-Z0-9]', '', 'g'
            ))
            AND (
              alias.aircraft_market_id IS NULL
              OR market.code IN ('GLOBAL', 'US')
            )
            AND (
              alias.valid_from_model_year IS NULL
              OR alias.valid_from_model_year <= NEW.model_year
            )
            AND (
              alias.valid_to_model_year IS NULL
              OR alias.valid_to_model_year >= NEW.model_year
            )
        )
        OR (
          aircraft.manufacturer_serial_key IS NOT NULL
          AND aircraft_tcds_make_lineage_matches(
            snapshot.snapshot_date,
            snapshot.archive_sha256,
            aircraft.aircraft_code,
            canonical_make.id,
            canonical_designation.id,
            reference.manufacturer_name,
            reference.model_name,
            aircraft.manufacturer_serial_key
          )
        )
      )
      AND (
        (
          assignment.aircraft_generation_id IS NULL
          AND NOT EXISTS (
            SELECT 1
            FROM aircraft_generation_designations generation_link
            WHERE generation_link.aircraft_designation_id =
              assignment.aircraft_designation_id
          )
        )
        OR (
          assignment.aircraft_generation_id IS NOT NULL
          AND EXISTS (
            SELECT 1
            FROM aircraft_generation_designations generation_link
            WHERE generation_link.aircraft_generation_id =
              assignment.aircraft_generation_id
              AND generation_link.aircraft_designation_id =
                assignment.aircraft_designation_id
          )
        )
      )
      AND (
        (
          assignment.aircraft_factory_package_id IS NULL
          AND NOT EXISTS (
            SELECT 1
            FROM aircraft_package_applicability applicability
            JOIN aircraft_factory_packages package
              ON package.id =
                applicability.aircraft_factory_package_id
            WHERE applicability.aircraft_designation_id =
              assignment.aircraft_designation_id
              AND package.package_kind = 'trim_tier'
              AND (
                applicability.aircraft_generation_id IS NULL
                OR applicability.aircraft_generation_id =
                  assignment.aircraft_generation_id
              )
              AND (
                applicability.valid_from_model_year IS NULL
                OR applicability.valid_from_model_year <= NEW.model_year
              )
              AND (
                applicability.valid_to_model_year IS NULL
                OR applicability.valid_to_model_year >= NEW.model_year
              )
          )
        )
        OR (
          assignment.aircraft_factory_package_id IS NOT NULL
          AND EXISTS (
            SELECT 1
            FROM aircraft_package_applicability applicability
            WHERE applicability.aircraft_factory_package_id =
              assignment.aircraft_factory_package_id
              AND applicability.aircraft_designation_id =
                assignment.aircraft_designation_id
              AND (
                applicability.aircraft_generation_id IS NULL
                OR applicability.aircraft_generation_id =
                  assignment.aircraft_generation_id
              )
              AND (
                applicability.valid_from_model_year IS NULL
                OR applicability.valid_from_model_year <= NEW.model_year
              )
              AND (
                applicability.valid_to_model_year IS NULL
                OR applicability.valid_to_model_year >= NEW.model_year
              )
          )
        )
      )
  ) THEN
    RAISE EXCEPTION
      'ready listing requires a current canonical aircraft assignment matching current FAA identity';
  END IF;

  RETURN NEW;
END;
$function$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS listing_ready_requires_canonical_aircraft_insert
  ON aircraft_sale_listings;
CREATE TRIGGER listing_ready_requires_canonical_aircraft_insert
BEFORE INSERT ON aircraft_sale_listings
FOR EACH ROW EXECUTE FUNCTION validate_ready_listing_aircraft_identity();

DROP TRIGGER IF EXISTS listing_ready_requires_canonical_aircraft_update
  ON aircraft_sale_listings;
CREATE TRIGGER listing_ready_requires_canonical_aircraft_update
BEFORE UPDATE OF
  ingestion_state,
  aircraft_model_variant_id,
  model_year,
  registration_number,
  serial_number
ON aircraft_sale_listings
FOR EACH ROW EXECUTE FUNCTION validate_ready_listing_aircraft_identity();

INSERT INTO schema_migration_contracts (
  migration_name, contract_version, contract_fingerprint, installed_at
) VALUES (
  '20260730_aircraft_tcds_make_lineage',
  1,
  '566485027d3df81bb5a90abcc0ce2b707e565bcbdc92ae3f007f527832fae735',
  CURRENT_TIMESTAMP
)
ON CONFLICT (migration_name) DO NOTHING;

COMMIT;
