-- Move legacy factory-default claims whose avionics product is not approved
-- into a pending-only table. Pending claims are never valuation inputs.
-- Rejection deletes the pending row. Explicit admission inserts the exact claim
-- into the canonical table after product approval; the admission trigger then
-- removes the pending row in the same transaction.

BEGIN;

CREATE TABLE IF NOT EXISTS schema_migration_contracts (
  migration_name TEXT PRIMARY KEY,
  contract_version INTEGER NOT NULL CHECK (contract_version > 0),
  contract_fingerprint TEXT NOT NULL
    CHECK (contract_fingerprint ~ '^[0-9a-f]{64}$'),
  installed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (length(trim(migration_name)) > 0)
);

DO $migration_guard$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM schema_migration_contracts
    WHERE migration_name = '20260802_default_avionics_candidate_quarantine'
      AND NOT (
        (
          contract_version = 1
          AND contract_fingerprint =
            'b50683c27b244cadf3cf88b226665f79051f678df9b30e0d01d0ca261464581f'
        )
        OR (
          contract_version = 2
          AND contract_fingerprint =
            'b8a6ecd15acc0ce14f67bf37ff4387c0ded4d1c6669d2fc4698b6c0a6c209ba4'
        )
      )
  ) THEN
    RAISE EXCEPTION
      'installed default avionics candidate quarantine has a different contract';
  END IF;
END
$migration_guard$;

CREATE TABLE IF NOT EXISTS aircraft_model_variant_default_avionics_candidates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quarantined_default_avionics_id BIGINT UNIQUE,
  aircraft_model_variant_id BIGINT NOT NULL
    REFERENCES aircraft_model_variants(id) ON DELETE RESTRICT,
  model_year BIGINT NOT NULL,
  avionics_model_id BIGINT NOT NULL
    REFERENCES avionics_models(id) ON DELETE RESTRICT,
  quantity BIGINT NOT NULL,
  source_url TEXT NOT NULL,
  source_title TEXT NOT NULL,
  source_notes TEXT NOT NULL,
  source_confidence TEXT NOT NULL,
  pending_reason TEXT NOT NULL DEFAULT 'factory_default_claim_unverified',
  quarantined_created_at TEXT,
  quarantined_updated_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_model_variant_id, model_year, avionics_model_id),
  CHECK (pending_reason IN (
    'catalog_product_unverified', 'factory_default_claim_unverified'
  )),
  CHECK (
    (
      quarantined_default_avionics_id IS NULL
      AND quarantined_created_at IS NULL
      AND quarantined_updated_at IS NULL
    )
    OR (
      quarantined_default_avionics_id > 0
      AND quarantined_created_at IS NOT NULL
      AND quarantined_updated_at IS NOT NULL
    )
  )
);

CREATE INDEX IF NOT EXISTS idx_aircraft_default_avionics_candidates_product
  ON aircraft_model_variant_default_avionics_candidates (
    avionics_model_id, aircraft_model_variant_id, model_year, id
  );

-- This is the shared catalog-mutation lock order. It makes product approval,
-- the canonical snapshot, and pending insertion one linearized operation.
LOCK TABLE avionics_models, aircraft_model_variant_default_avionics,
  aircraft_model_variant_default_avionics_candidates
  IN SHARE ROW EXCLUSIVE MODE;

-- Version 1 could copy an unapproved canonical row, then observe a concurrent
-- product approval during deletion. Repair only that exact race signature:
-- the approved canonical row and its legacy-provenance candidate must match
-- byte-for-byte. Any other overlap is corruption and fails the postcondition.
DELETE FROM aircraft_model_variant_default_avionics_candidates candidate
USING aircraft_model_variant_default_avionics active,
      avionics_models model
WHERE model.id = active.avionics_model_id
  AND model.catalog_status = 'approved'
  AND candidate.quarantined_default_avionics_id = active.id
  AND candidate.aircraft_model_variant_id = active.aircraft_model_variant_id
  AND candidate.model_year = active.model_year
  AND candidate.avionics_model_id = active.avionics_model_id
  AND candidate.quantity = active.quantity
  AND candidate.source_url = active.source_url
  AND candidate.source_title = active.source_title
  AND candidate.source_notes = active.source_notes
  AND candidate.source_confidence = active.source_confidence
  AND candidate.pending_reason = 'catalog_product_unverified'
  AND candidate.quarantined_created_at = active.created_at
  AND candidate.quarantined_updated_at = active.updated_at;

INSERT INTO aircraft_model_variant_default_avionics_candidates (
  quarantined_default_avionics_id,
  aircraft_model_variant_id,
  model_year,
  avionics_model_id,
  quantity,
  source_url,
  source_title,
  source_notes,
  source_confidence,
  pending_reason,
  quarantined_created_at,
  quarantined_updated_at,
  created_at
)
SELECT
  default_avionics.id,
  default_avionics.aircraft_model_variant_id,
  default_avionics.model_year,
  default_avionics.avionics_model_id,
  default_avionics.quantity,
  default_avionics.source_url,
  default_avionics.source_title,
  default_avionics.source_notes,
  default_avionics.source_confidence,
  'catalog_product_unverified',
  default_avionics.created_at,
  default_avionics.updated_at,
  CURRENT_TIMESTAMP
FROM aircraft_model_variant_default_avionics default_avionics
JOIN avionics_models model
  ON model.id = default_avionics.avionics_model_id
WHERE model.catalog_status <> 'approved'
ON CONFLICT (quarantined_default_avionics_id) DO NOTHING;

DELETE FROM aircraft_model_variant_default_avionics default_avionics
USING avionics_models model,
      aircraft_model_variant_default_avionics_candidates candidate
WHERE model.id = default_avionics.avionics_model_id
  AND model.catalog_status <> 'approved'
  AND candidate.quarantined_default_avionics_id = default_avionics.id
  AND candidate.aircraft_model_variant_id =
      default_avionics.aircraft_model_variant_id
  AND candidate.model_year = default_avionics.model_year
  AND candidate.avionics_model_id = default_avionics.avionics_model_id
  AND candidate.quantity = default_avionics.quantity
  AND candidate.source_url = default_avionics.source_url
  AND candidate.source_title = default_avionics.source_title
  AND candidate.source_notes = default_avionics.source_notes
  AND candidate.source_confidence = default_avionics.source_confidence
  AND candidate.quarantined_created_at = default_avionics.created_at
  AND candidate.quarantined_updated_at = default_avionics.updated_at;

CREATE OR REPLACE FUNCTION reject_active_default_avionics_candidate()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  -- Serialize both sides of the cross-table uniqueness check on the semantic
  -- claim key. PostgreSQL table-level locks acquired from opposite INSERT
  -- triggers can deadlock; this transaction-scoped advisory lock gives both
  -- paths the same lock without reducing concurrency between unrelated claims.
  PERFORM pg_advisory_xact_lock(
    hashtextextended(
      concat_ws(
        ':',
        'aircraft_model_variant_default_avionics',
        NEW.aircraft_model_variant_id::text,
        NEW.model_year::text,
        NEW.avionics_model_id::text
      ),
      0
    )
  );

  IF EXISTS (
    SELECT 1
    FROM aircraft_model_variant_default_avionics active
    WHERE active.aircraft_model_variant_id = NEW.aircraft_model_variant_id
      AND active.model_year = NEW.model_year
      AND active.avionics_model_id = NEW.avionics_model_id
  ) THEN
    RAISE EXCEPTION
      'default avionics claim already exists in the canonical table';
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS aircraft_default_avionics_candidate_active_conflict_insert
  ON aircraft_model_variant_default_avionics_candidates;
CREATE TRIGGER aircraft_default_avionics_candidate_active_conflict_insert
BEFORE INSERT ON aircraft_model_variant_default_avionics_candidates
FOR EACH ROW EXECUTE FUNCTION reject_active_default_avionics_candidate();

CREATE OR REPLACE FUNCTION preserve_pending_default_avionics_claim()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  RAISE EXCEPTION
    'pending default avionics claims must be replaced, admitted, or rejected explicitly';
END;
$function$;

DROP TRIGGER IF EXISTS aircraft_default_avionics_candidate_claim_immutable
  ON aircraft_model_variant_default_avionics_candidates;
CREATE TRIGGER aircraft_default_avionics_candidate_claim_immutable
BEFORE UPDATE ON aircraft_model_variant_default_avionics_candidates
FOR EACH ROW EXECUTE FUNCTION preserve_pending_default_avionics_claim();

CREATE OR REPLACE FUNCTION require_exact_pending_default_avionics_admission()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  -- Use the same semantic transaction lock as candidate insertion so
  -- concurrent canonical/candidate writes cannot both pass their checks.
  PERFORM pg_advisory_xact_lock(
    hashtextextended(
      concat_ws(
        ':',
        'aircraft_model_variant_default_avionics',
        NEW.aircraft_model_variant_id::text,
        NEW.model_year::text,
        NEW.avionics_model_id::text
      ),
      0
    )
  );

  IF EXISTS (
    SELECT 1
    FROM aircraft_model_variant_default_avionics_candidates candidate
    WHERE candidate.aircraft_model_variant_id = NEW.aircraft_model_variant_id
      AND candidate.model_year = NEW.model_year
      AND candidate.avionics_model_id = NEW.avionics_model_id
  ) AND NOT EXISTS (
    SELECT 1
    FROM aircraft_model_variant_default_avionics_candidates candidate
    WHERE candidate.aircraft_model_variant_id = NEW.aircraft_model_variant_id
      AND candidate.model_year = NEW.model_year
      AND candidate.avionics_model_id = NEW.avionics_model_id
      AND candidate.quantity = NEW.quantity
      AND candidate.source_url = NEW.source_url
      AND candidate.source_title = NEW.source_title
      AND candidate.source_notes = NEW.source_notes
      AND candidate.source_confidence = NEW.source_confidence
  ) THEN
    RAISE EXCEPTION
      'canonical default admission must exactly match its pending claim';
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS aircraft_default_avionics_candidate_admission_guard
  ON aircraft_model_variant_default_avionics;
CREATE TRIGGER aircraft_default_avionics_candidate_admission_guard
BEFORE INSERT ON aircraft_model_variant_default_avionics
FOR EACH ROW EXECUTE FUNCTION require_exact_pending_default_avionics_admission();

CREATE OR REPLACE FUNCTION move_admitted_default_avionics_candidate()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  DELETE FROM aircraft_model_variant_default_avionics_candidates
  WHERE aircraft_model_variant_id = NEW.aircraft_model_variant_id
    AND model_year = NEW.model_year
    AND avionics_model_id = NEW.avionics_model_id
    AND quantity = NEW.quantity
    AND source_url = NEW.source_url
    AND source_title = NEW.source_title
    AND source_notes = NEW.source_notes
    AND source_confidence = NEW.source_confidence;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS aircraft_default_avionics_candidate_admission_move
  ON aircraft_model_variant_default_avionics;
CREATE TRIGGER aircraft_default_avionics_candidate_admission_move
AFTER INSERT ON aircraft_model_variant_default_avionics
FOR EACH ROW EXECUTE FUNCTION move_admitted_default_avionics_candidate();

DO $postcondition_guard$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM aircraft_model_variant_default_avionics default_avionics
    JOIN avionics_models model ON model.id = default_avionics.avionics_model_id
    WHERE model.catalog_status <> 'approved'
  ) THEN
    RAISE EXCEPTION
      'unapproved avionics products remain in canonical factory defaults';
  END IF;
  IF EXISTS (
    SELECT 1
    FROM aircraft_model_variant_default_avionics active
    JOIN aircraft_model_variant_default_avionics_candidates candidate
      ON candidate.aircraft_model_variant_id =
         active.aircraft_model_variant_id
     AND candidate.model_year = active.model_year
     AND candidate.avionics_model_id = active.avionics_model_id
  ) THEN
    RAISE EXCEPTION
      'default avionics claim exists in both canonical and pending tables';
  END IF;
END
$postcondition_guard$;

INSERT INTO schema_migration_contracts (
  migration_name, contract_version, contract_fingerprint, installed_at
) VALUES (
  '20260802_default_avionics_candidate_quarantine',
  2,
  'b8a6ecd15acc0ce14f67bf37ff4387c0ded4d1c6669d2fc4698b6c0a6c209ba4',
  CURRENT_TIMESTAMP
)
ON CONFLICT (migration_name) DO UPDATE SET
  contract_version = EXCLUDED.contract_version,
  contract_fingerprint = EXCLUDED.contract_fingerprint,
  installed_at = EXCLUDED.installed_at
WHERE schema_migration_contracts.contract_version = 1
  AND schema_migration_contracts.contract_fingerprint =
      'b50683c27b244cadf3cf88b226665f79051f678df9b30e0d01d0ca261464581f';

COMMIT;
