-- Replace the overloaded `not_an_entity` action with a clean operational
-- `no_supported_selection` outcome for newly validated optional dimensions.
-- Historical negative decisions are conservatively retained as generic
-- rejections: they predate the server-owned token, catalog-relation, and
-- applicability predicates and therefore cannot be upgraded to approval.
--
-- Canonical legacy rows are translated. Any legacy use outside the two
-- optional dimensions aborts the transaction before constraints or data are
-- changed. Dropping constraints by definition makes the migration safe across
-- both historical autogenerated names and reruns with the canonical names.

BEGIN;

SET LOCAL search_path = public, pg_catalog;

LOCK TABLE public.schema_migration_contracts
IN SHARE ROW EXCLUSIVE MODE;

DO $migration_contract_guard$
BEGIN
  IF EXISTS (
    SELECT 1 FROM schema_migration_contracts
    WHERE migration_name = '20260728_aircraft_identity_no_supported_selection'
      AND (
        contract_version IS DISTINCT FROM 2
        OR contract_fingerprint IS DISTINCT FROM
          '2c61547aae5158dd0a5393ca49218f0f3aada7d9b87caf950fa27fe2953d7dee'
      )
  ) THEN
    RAISE EXCEPTION
      'installed aircraft no-supported-selection migration has a different contract';
  END IF;
END
$migration_contract_guard$;

DO $migration$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM aircraft_identity_decisions
    WHERE decision_action = 'not_an_entity'
      AND NOT (
        entity_kind IN ('generation', 'package')
        AND decision_status = 'rejected'
        AND selected_entity_id IS NULL
      )
  ) THEN
    RAISE EXCEPTION
      'malformed legacy not_an_entity aircraft identity decision';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM aircraft_identity_decisions decision
    WHERE decision.decision_action = 'no_supported_selection'
      AND (
        NOT (
          decision.entity_kind IN ('generation', 'package')
          AND decision.decision_status = 'approved'
          AND decision.selected_entity_id IS NULL
          AND decision.deterministic_validation_passed
        )
        OR EXISTS (
          SELECT 1
          FROM aircraft_identity_decision_claims claim
          WHERE claim.decision_id = decision.id
        )
      )
  ) THEN
    RAISE EXCEPTION
      'malformed no_supported_selection aircraft identity decision';
  END IF;
END
$migration$;

DO $migration$
DECLARE
  constraint_row RECORD;
BEGIN
  FOR constraint_row IN
    SELECT constraint_definition.conname
    FROM pg_constraint constraint_definition
    WHERE constraint_definition.conrelid =
        'aircraft_identity_decisions'::regclass
      AND constraint_definition.contype = 'c'
      AND pg_get_constraintdef(constraint_definition.oid)
          LIKE '%decision_action%'
  LOOP
    EXECUTE format(
      'ALTER TABLE aircraft_identity_decisions DROP CONSTRAINT %I',
      constraint_row.conname
    );
  END LOOP;
END
$migration$;

UPDATE aircraft_identity_decisions
SET decision_action = 'reject'
WHERE decision_action = 'not_an_entity';

ALTER TABLE aircraft_identity_decisions
  ADD CONSTRAINT aircraft_identity_decisions_action_values_check
  CHECK (decision_action IN (
    'match_existing', 'approve_new', 'no_supported_selection', 'ambiguous',
    'reject'
  )),
  ADD CONSTRAINT aircraft_identity_decisions_status_action_check
  CHECK (
    (decision_status = 'approved'
      AND decision_action IN (
        'match_existing', 'approve_new', 'no_supported_selection'
      )
      AND deterministic_validation_passed)
    OR (decision_status = 'rejected' AND decision_action = 'reject')
    OR (decision_status = 'ambiguous' AND decision_action = 'ambiguous')
  ),
  ADD CONSTRAINT aircraft_identity_decisions_selected_entity_check
  CHECK (
    (decision_action = 'match_existing' AND selected_entity_id IS NOT NULL)
    OR (decision_action <> 'match_existing' AND selected_entity_id IS NULL)
  ),
  ADD CONSTRAINT aircraft_identity_decisions_no_supported_selection_check
  CHECK (
    decision_action <> 'no_supported_selection'
    OR entity_kind IN ('generation', 'package')
  );

CREATE OR REPLACE FUNCTION reject_no_supported_selection_claim()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM aircraft_identity_decisions decision
    WHERE decision.id = NEW.decision_id
      AND decision.decision_action = 'no_supported_selection'
  ) THEN
    RAISE EXCEPTION
      'no-supported-selection decision cannot have evidence claims';
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS aircraft_identity_no_supported_selection_claim_insert
  ON aircraft_identity_decision_claims;
CREATE TRIGGER aircraft_identity_no_supported_selection_claim_insert
BEFORE INSERT ON aircraft_identity_decision_claims
FOR EACH ROW EXECUTE FUNCTION reject_no_supported_selection_claim();

DROP TRIGGER IF EXISTS aircraft_identity_no_supported_selection_claim_update
  ON aircraft_identity_decision_claims;
CREATE TRIGGER aircraft_identity_no_supported_selection_claim_update
BEFORE UPDATE OF decision_id ON aircraft_identity_decision_claims
FOR EACH ROW EXECUTE FUNCTION reject_no_supported_selection_claim();

CREATE OR REPLACE FUNCTION reject_claimed_no_supported_selection_decision()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.decision_action = 'no_supported_selection'
    AND EXISTS (
      SELECT 1
      FROM aircraft_identity_decision_claims claim
      WHERE claim.decision_id = OLD.id
    )
  THEN
    RAISE EXCEPTION
      'decision with evidence claims cannot become no-supported-selection';
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS aircraft_identity_no_supported_selection_decision_update
  ON aircraft_identity_decisions;
CREATE TRIGGER aircraft_identity_no_supported_selection_decision_update
BEFORE UPDATE OF decision_action ON aircraft_identity_decisions
FOR EACH ROW
EXECUTE FUNCTION reject_claimed_no_supported_selection_decision();

INSERT INTO schema_migration_contracts (
  migration_name, contract_version, contract_fingerprint, installed_at
) VALUES (
  '20260728_aircraft_identity_no_supported_selection',
  2,
  '2c61547aae5158dd0a5393ca49218f0f3aada7d9b87caf950fa27fe2953d7dee',
  CURRENT_TIMESTAMP
)
ON CONFLICT (migration_name) DO NOTHING;

COMMIT;
