BEGIN;

CREATE TABLE IF NOT EXISTS public.schema_migration_contracts (
  migration_name TEXT PRIMARY KEY,
  contract_version INTEGER NOT NULL CHECK (contract_version > 0),
  contract_fingerprint TEXT NOT NULL
    CHECK (contract_fingerprint ~ '^[0-9a-f]{64}$'),
  installed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (length(BTRIM(migration_name)) > 0)
);

DO $migration_guard$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.schema_migration_contracts
    WHERE migration_name = '20260819_aircraft_listing_identity_corrections'
      AND (
        contract_version IS DISTINCT FROM 1
        OR contract_fingerprint IS DISTINCT FROM
          '589a0716726d2ffd34bf84c08583198383c003228b769c88f094ac6bd9f677b8'
      )
  ) THEN
    RAISE EXCEPTION
      'installed aircraft listing identity corrections migration has a different contract';
  END IF;
  IF pg_catalog.to_regclass(
       'public.aircraft_listing_identity_correction_decisions'
     ) IS NOT NULL
     AND NOT EXISTS (
       SELECT 1 FROM public.schema_migration_contracts
       WHERE migration_name = '20260819_aircraft_listing_identity_corrections'
     ) THEN
    RAISE EXCEPTION
      'preexisting aircraft listing identity correction table has no verified contract';
  END IF;
END
$migration_guard$;

DROP INDEX IF EXISTS public.uq_plugin_submissions_signed_capture;
CREATE UNIQUE INDEX uq_plugin_submissions_signed_capture
  ON public.plugin_submissions (
    user_id, plugin_install_id, source_url, rendered_html_sha256
  );

CREATE TABLE IF NOT EXISTS public.aircraft_listing_identity_correction_decisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_sale_listing_id BIGINT NOT NULL
    REFERENCES public.aircraft_sale_listings(id) ON DELETE RESTRICT,
  observation_id BIGINT NOT NULL
    REFERENCES public.aircraft_identity_observations(id) ON DELETE RESTRICT,
  evidence_claim_id BIGINT NOT NULL
    REFERENCES public.curation_evidence_claims(id) ON DELETE RESTRICT,
  correction_kind TEXT NOT NULL CHECK (correction_kind IN (
    'visual_identifier', 'faa_serial', 'publisher_hierarchy'
  )),
  expected_state_sha256 TEXT NOT NULL CHECK (expected_state_sha256 ~ '^[0-9a-f]{64}$'),
  plugin_submission_id BIGINT NOT NULL
    REFERENCES public.plugin_submissions(id) ON DELETE RESTRICT,
  rendered_html_sha256 TEXT NOT NULL CHECK (rendered_html_sha256 ~ '^[0-9a-f]{64}$'),
  prior_registration_number TEXT,
  prior_serial_number TEXT,
  corrected_registration_number TEXT,
  corrected_serial_number TEXT,
  faa_registry_snapshot_id BIGINT
    REFERENCES public.faa_registry_snapshots(id) ON DELETE RESTRICT,
  faa_source_record_sha256 TEXT,
  visual_resolution_json TEXT,
  decision_payload_json TEXT NOT NULL,
  decided_by_user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  decided_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (
    (correction_kind = 'visual_identifier'
      AND corrected_registration_number IS NOT NULL
      AND faa_registry_snapshot_id IS NOT NULL
      AND faa_source_record_sha256 IS NOT NULL
      AND visual_resolution_json IS NOT NULL)
    OR
    (correction_kind = 'faa_serial'
      AND corrected_registration_number IS NOT NULL
      AND corrected_serial_number IS NOT NULL
      AND faa_registry_snapshot_id IS NOT NULL
      AND faa_source_record_sha256 IS NOT NULL
      AND visual_resolution_json IS NULL)
    OR
    (correction_kind = 'publisher_hierarchy'
      AND faa_registry_snapshot_id IS NULL
      AND faa_source_record_sha256 IS NULL
      AND visual_resolution_json IS NULL
      AND corrected_registration_number IS NOT DISTINCT FROM prior_registration_number
      AND corrected_serial_number IS NOT DISTINCT FROM prior_serial_number)
  )
);

DROP INDEX IF EXISTS public.idx_aircraft_listing_identity_corrections_listing;
CREATE INDEX idx_aircraft_listing_identity_corrections_listing
  ON public.aircraft_listing_identity_correction_decisions (
    aircraft_sale_listing_id, correction_kind, id
  );
DROP INDEX IF EXISTS public.uq_aircraft_listing_identity_correction_receipt;
CREATE UNIQUE INDEX uq_aircraft_listing_identity_correction_receipt
  ON public.aircraft_listing_identity_correction_decisions (
    plugin_submission_id, correction_kind
  );

CREATE OR REPLACE FUNCTION public.preserve_aircraft_listing_identity_correction()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'aircraft listing identity correction decisions are immutable';
END;
$$ LANGUAGE plpgsql
SET search_path = pg_catalog;

DROP TRIGGER IF EXISTS aircraft_listing_identity_corrections_immutable
ON public.aircraft_listing_identity_correction_decisions;
CREATE TRIGGER aircraft_listing_identity_corrections_immutable
BEFORE UPDATE OR DELETE ON public.aircraft_listing_identity_correction_decisions
FOR EACH ROW EXECUTE FUNCTION public.preserve_aircraft_listing_identity_correction();

CREATE OR REPLACE FUNCTION public.preserve_correction_identity_observation()
RETURNS TRIGGER AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.aircraft_listing_identity_correction_decisions decision
    WHERE decision.observation_id = OLD.id
  ) THEN
    RAISE EXCEPTION 'aircraft identity observations referenced by correction decisions are immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql
SET search_path = pg_catalog;

DROP TRIGGER IF EXISTS aircraft_identity_correction_observation_immutable
ON public.aircraft_identity_observations;
CREATE TRIGGER aircraft_identity_correction_observation_immutable
BEFORE UPDATE OR DELETE ON public.aircraft_identity_observations
FOR EACH ROW EXECUTE FUNCTION public.preserve_correction_identity_observation();

CREATE OR REPLACE FUNCTION public.require_source_identity_correction_receipt()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.ingestion_error = 'source_identity_correction_receipt_pending'
     AND (
       NEW.ingestion_error IS DISTINCT FROM OLD.ingestion_error
       OR NEW.ingestion_state IS DISTINCT FROM OLD.ingestion_state
       OR NEW.is_verified IS DISTINCT FROM OLD.is_verified
     )
     AND NOT EXISTS (
       SELECT 1
       FROM public.aircraft_listing_identity_correction_decisions decision
       JOIN public.plugin_submissions submission
         ON submission.id = decision.plugin_submission_id
       WHERE decision.aircraft_sale_listing_id = OLD.id
         AND decision.correction_kind = 'faa_serial'
         AND decision.rendered_html_sha256 = submission.rendered_html_sha256
         AND submission.user_id = OLD.created_by_user_id
         AND submission.canonical_listing_id = OLD.id
         AND submission.extraction_error IS NULL
         AND NEW.registration_number IS NOT DISTINCT FROM decision.corrected_registration_number
         AND NEW.serial_number IS NOT DISTINCT FROM decision.corrected_serial_number
     ) THEN
    RAISE EXCEPTION 'source identity correction receipt is required before leaving the receipt gate';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql
SET search_path = pg_catalog;

DROP TRIGGER IF EXISTS aircraft_source_identity_receipt_gate
ON public.aircraft_sale_listings;
CREATE TRIGGER aircraft_source_identity_receipt_gate
BEFORE UPDATE OF ingestion_state, ingestion_error, is_verified
ON public.aircraft_sale_listings
FOR EACH ROW EXECUTE FUNCTION public.require_source_identity_correction_receipt();

INSERT INTO public.schema_migration_contracts AS installed_contract (
  migration_name, contract_version, contract_fingerprint, installed_at
) VALUES (
  '20260819_aircraft_listing_identity_corrections',
  1,
  '589a0716726d2ffd34bf84c08583198383c003228b769c88f094ac6bd9f677b8',
  CURRENT_TIMESTAMP
)
ON CONFLICT (migration_name) DO NOTHING;

COMMIT;
