CREATE TABLE IF NOT EXISTS aircraft_sale_listing_avionics_dispositions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_sale_listing_id BIGINT NOT NULL
    REFERENCES aircraft_sale_listings(id) ON DELETE CASCADE,
  plugin_submission_id BIGINT NOT NULL
    REFERENCES plugin_submissions(id) ON DELETE RESTRICT,
  extraction_sha256 TEXT NOT NULL CHECK (extraction_sha256 ~ '^[0-9a-f]{64}$'),
  occurrence_index BIGINT NOT NULL CHECK (occurrence_index >= 0),
  occurrence_role TEXT NOT NULL CHECK (occurrence_role IN ('primary', 'replacement')),
  occurrence_fingerprint TEXT NOT NULL CHECK (occurrence_fingerprint ~ '^[0-9a-f]{64}$'),
  outcome TEXT NOT NULL CHECK (outcome IN ('linked', 'discarded')),
  avionics_model_id BIGINT REFERENCES avionics_models(id) ON DELETE RESTRICT,
  reason_code TEXT NOT NULL CHECK (length(BTRIM(reason_code)) BETWEEN 1 AND 100),
  decision_reason TEXT NOT NULL CHECK (length(BTRIM(decision_reason)) BETWEEN 1 AND 500),
  decision_source TEXT NOT NULL CHECK (decision_source IN ('automatic', 'manual')),
  actor_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  policy_version TEXT NOT NULL CHECK (length(BTRIM(policy_version)) BETWEEN 1 AND 100),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (plugin_submission_id, extraction_sha256, occurrence_index, occurrence_role),
  CHECK (
    (outcome = 'linked' AND avionics_model_id IS NOT NULL)
    OR (outcome = 'discarded' AND avionics_model_id IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_listing_avionics_dispositions_listing
  ON aircraft_sale_listing_avionics_dispositions (aircraft_sale_listing_id, occurrence_index);

CREATE OR REPLACE FUNCTION reject_listing_avionics_disposition_update()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'avionics occurrence dispositions are immutable';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_listing_avionics_dispositions_immutable
ON aircraft_sale_listing_avionics_dispositions;
CREATE TRIGGER trg_listing_avionics_dispositions_immutable
BEFORE UPDATE ON aircraft_sale_listing_avionics_dispositions
FOR EACH ROW EXECUTE FUNCTION reject_listing_avionics_disposition_update();
