CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  auth_provider TEXT NOT NULL DEFAULT 'local',
  auth_subject TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS depreciation_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  age_decay_rate DOUBLE PRECISION NOT NULL,
  long_run_residual_fraction DOUBLE PRECISION NOT NULL,
  new_to_used_discount_fraction DOUBLE PRECISION NOT NULL,
  new_to_used_discount_years DOUBLE PRECISION NOT NULL,
  airframe_doubling_discount DOUBLE PRECISION NOT NULL,
  max_airframe_premium DOUBLE PRECISION NOT NULL,
  max_airframe_discount DOUBLE PRECISION NOT NULL,
  replacement_floor_fraction DOUBLE PRECISION NOT NULL DEFAULT 0,
  minimum_value_fraction DOUBLE PRECISION NOT NULL,
  high_time_threshold_hours DOUBLE PRECISION,
  high_time_discount_at_double_threshold DOUBLE PRECISION NOT NULL,
  is_system_profile BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS depreciation_profile_fit_metadata (
  depreciation_profile_id BIGINT PRIMARY KEY
    REFERENCES depreciation_profiles(id) ON DELETE CASCADE,
  fit_scope TEXT NOT NULL CHECK (fit_scope IN ('global', 'category', 'model')),
  fit_scope_key TEXT NOT NULL,
  fit_category TEXT NOT NULL,
  sample_count BIGINT NOT NULL,
  rmse_usd DOUBLE PRECISION NOT NULL,
  mae_fraction DOUBLE PRECISION NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (fit_scope, fit_scope_key)
);

CREATE INDEX IF NOT EXISTS idx_depreciation_profile_fit_metadata_category
  ON depreciation_profile_fit_metadata (fit_category);

CREATE TABLE IF NOT EXISTS component_depreciation_profiles (
  component_type TEXT PRIMARY KEY
    CHECK (component_type IN ('engine', 'propeller', 'avionics')),
  age_decay_rate DOUBLE PRECISION,
  long_run_residual_fraction DOUBLE PRECISION,
  baseline_life_fraction DOUBLE PRECISION,
  sample_count BIGINT NOT NULL DEFAULT 0,
  rmse_usd DOUBLE PRECISION,
  mae_fraction DOUBLE PRECISION,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS engine_manufacturers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS engine_models (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  engine_manufacturer_id BIGINT NOT NULL REFERENCES engine_manufacturers(id),
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  tbo_hours DOUBLE PRECISION,
  overhaul_cost_usd DOUBLE PRECISION,
  value_reference_year BIGINT,
  source_url TEXT,
  source_title TEXT,
  source_confidence TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (engine_manufacturer_id, normalized_name)
);

CREATE INDEX IF NOT EXISTS idx_engine_models_manufacturer
  ON engine_models (engine_manufacturer_id);

CREATE TABLE IF NOT EXISTS propeller_manufacturers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS propeller_models (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  propeller_manufacturer_id BIGINT NOT NULL REFERENCES propeller_manufacturers(id),
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  tbo_hours DOUBLE PRECISION,
  overhaul_cost_usd DOUBLE PRECISION,
  value_reference_year BIGINT,
  source_url TEXT,
  source_title TEXT,
  source_confidence TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (propeller_manufacturer_id, normalized_name)
);

CREATE INDEX IF NOT EXISTS idx_propeller_models_manufacturer
  ON propeller_models (propeller_manufacturer_id);

CREATE TABLE IF NOT EXISTS aircraft_manufacturers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS aircraft_models (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_manufacturer_id BIGINT NOT NULL REFERENCES aircraft_manufacturers(id),
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_manufacturer_id, normalized_name)
);

CREATE TABLE IF NOT EXISTS aircraft_model_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_model_id BIGINT NOT NULL REFERENCES aircraft_models(id),
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_model_id, normalized_name)
);

CREATE INDEX IF NOT EXISTS idx_aircraft_model_variants_model
  ON aircraft_model_variants (aircraft_model_id);

CREATE TABLE IF NOT EXISTS aircraft_model_spec_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_model_id BIGINT NOT NULL REFERENCES aircraft_models(id),
  aircraft_model_variant_id BIGINT NOT NULL REFERENCES aircraft_model_variants(id),
  effective_from TEXT NOT NULL,
  effective_to TEXT,
  depreciation_profile_id BIGINT REFERENCES depreciation_profiles(id),
  average_inflation_rate DOUBLE PRECISION NOT NULL DEFAULT 0.025,
  fuel_burn_gph DOUBLE PRECISION,
  oil_quarts_per_hour DOUBLE PRECISION,
  oil_price_per_quart_usd DOUBLE PRECISION,
  engine_model_id BIGINT REFERENCES engine_models(id),
  engine_count BIGINT NOT NULL DEFAULT 1,
  engine_tbo_hours DOUBLE PRECISION,
  engine_overhaul_cost_usd DOUBLE PRECISION,
  engine_value_baseline_life_fraction DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  propeller_model_id BIGINT REFERENCES propeller_models(id),
  propeller_count BIGINT NOT NULL DEFAULT 1,
  propeller_tbo_hours DOUBLE PRECISION,
  propeller_overhaul_cost_usd DOUBLE PRECISION,
  propeller_value_baseline_life_fraction DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  annual_inspection_usd DOUBLE PRECISION,
  other_maintenance_per_hour DOUBLE PRECISION,
  source_url TEXT,
  created_by_user_id BIGINT REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (effective_to IS NULL OR effective_to > effective_from)
);

CREATE INDEX IF NOT EXISTS idx_aircraft_model_spec_versions_model
  ON aircraft_model_spec_versions (
    aircraft_model_id,
    aircraft_model_variant_id,
    effective_from
  );

CREATE TABLE IF NOT EXISTS aircraft_model_variant_price_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_model_variant_id BIGINT NOT NULL REFERENCES aircraft_model_variants(id),
  model_year BIGINT NOT NULL,
  purchase_price_new_usd DOUBLE PRECISION NOT NULL,
  purchase_price_reference_year BIGINT NOT NULL,
  source_url TEXT NOT NULL,
  source_title TEXT NOT NULL,
  source_notes TEXT NOT NULL,
  source_confidence TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_model_variant_id, model_year)
);

CREATE INDEX IF NOT EXISTS idx_aircraft_model_variant_price_points_lookup
  ON aircraft_model_variant_price_points (aircraft_model_variant_id, model_year);

CREATE TABLE IF NOT EXISTS avionics_manufacturers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS avionics_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS avionics_models (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  avionics_manufacturer_id BIGINT NOT NULL REFERENCES avionics_manufacturers(id),
  avionics_type_id BIGINT NOT NULL REFERENCES avionics_types(id),
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  introduced_year BIGINT,
  discontinued_year BIGINT,
  estimated_unit_value_usd DOUBLE PRECISION,
  value_reference_year BIGINT,
  value_source TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (avionics_manufacturer_id, avionics_type_id, normalized_name)
);

CREATE TABLE IF NOT EXISTS aircraft_model_variant_default_avionics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_model_variant_id BIGINT NOT NULL REFERENCES aircraft_model_variants(id),
  model_year BIGINT NOT NULL,
  avionics_model_id BIGINT NOT NULL REFERENCES avionics_models(id),
  quantity BIGINT NOT NULL DEFAULT 1,
  source_url TEXT NOT NULL,
  source_title TEXT NOT NULL,
  source_notes TEXT NOT NULL,
  source_confidence TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_model_variant_id, model_year, avionics_model_id)
);

CREATE INDEX IF NOT EXISTS idx_aircraft_model_variant_default_avionics_lookup
  ON aircraft_model_variant_default_avionics (aircraft_model_variant_id, model_year);

CREATE TABLE IF NOT EXISTS aircraft_sale_listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_model_variant_id BIGINT NOT NULL REFERENCES aircraft_model_variants(id),
  created_by_user_id BIGINT NOT NULL REFERENCES users(id),
  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  source_url TEXT,
  model_year BIGINT NOT NULL,
  asking_price_usd DOUBLE PRECISION NOT NULL,
  currency TEXT NOT NULL DEFAULT 'USD',
  added_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status TEXT NOT NULL DEFAULT 'active',
  registration_number TEXT,
  serial_number TEXT,
  airframe_hours DOUBLE PRECISION NOT NULL,
  engine_hours DOUBLE PRECISION NOT NULL,
  propeller_hours DOUBLE PRECISION NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (source_url IS NOT NULL OR is_verified = FALSE)
);

CREATE INDEX IF NOT EXISTS idx_aircraft_sale_listings_variant
  ON aircraft_sale_listings (aircraft_model_variant_id, is_verified, added_at);

CREATE INDEX IF NOT EXISTS idx_aircraft_sale_listings_user
  ON aircraft_sale_listings (created_by_user_id);

CREATE TABLE IF NOT EXISTS plugin_installs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  public_key_base64 TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_plugin_installs_user
  ON plugin_installs (user_id, revoked_at);

CREATE TABLE IF NOT EXISTS plugin_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  plugin_install_id BIGINT NOT NULL REFERENCES plugin_installs(id),
  source_url TEXT NOT NULL,
  submitted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  rendered_html TEXT NOT NULL,
  rendered_html_sha256 TEXT NOT NULL,
  signature_base64 TEXT NOT NULL,
  extracted_listing_json TEXT,
  extraction_error TEXT,
  canonical_listing_id BIGINT REFERENCES aircraft_sale_listings(id)
);

CREATE INDEX IF NOT EXISTS idx_plugin_submissions_user
  ON plugin_submissions (user_id, submitted_at);

CREATE INDEX IF NOT EXISTS idx_plugin_submissions_listing
  ON plugin_submissions (canonical_listing_id);

CREATE TABLE IF NOT EXISTS aircraft_sale_listing_avionics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aircraft_sale_listing_id BIGINT NOT NULL
    REFERENCES aircraft_sale_listings(id) ON DELETE CASCADE,
  avionics_model_id BIGINT NOT NULL REFERENCES avionics_models(id),
  quantity BIGINT NOT NULL DEFAULT 1,
  source TEXT NOT NULL DEFAULT 'listing',
  source_notes TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (aircraft_sale_listing_id, avionics_model_id)
);

CREATE TABLE IF NOT EXISTS valuation_snapshots (
  id BIGSERIAL PRIMARY KEY,
  capture_time TEXT NOT NULL,
  input_sha256 TEXT NOT NULL UNIQUE,
  selection_policy_json TEXT NOT NULL,
  feature_schema_version INTEGER NOT NULL,
  included_count BIGINT NOT NULL,
  excluded_count BIGINT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS valuation_snapshot_rows (
  id BIGSERIAL PRIMARY KEY,
  snapshot_id BIGINT NOT NULL REFERENCES valuation_snapshots(id) ON DELETE CASCADE,
  source_listing_id BIGINT NOT NULL,
  duplicate_group_key TEXT NOT NULL,
  inclusion_flag BOOLEAN NOT NULL,
  exclusion_reason TEXT,
  feature_json TEXT NOT NULL,
  target_price_usd DOUBLE PRECISION,
  row_sha256 TEXT NOT NULL,
  UNIQUE (snapshot_id, source_listing_id)
);

CREATE INDEX IF NOT EXISTS idx_valuation_snapshot_rows_snapshot_inclusion
  ON valuation_snapshot_rows (snapshot_id, inclusion_flag, source_listing_id);

CREATE TABLE IF NOT EXISTS valuation_model_versions (
  id BIGSERIAL PRIMARY KEY,
  snapshot_id BIGINT NOT NULL REFERENCES valuation_snapshots(id),
  model_kind TEXT NOT NULL CHECK (model_kind IN ('structural', 'dnn')),
  artifact_format_version INTEGER NOT NULL,
  state TEXT NOT NULL CHECK (state IN ('candidate', 'active', 'retired')),
  metrics_json TEXT NOT NULL,
  configuration_json TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_valuation_model_versions_one_active_kind
  ON valuation_model_versions (model_kind) WHERE state = 'active';

CREATE TABLE IF NOT EXISTS valuation_model_artifacts (
  model_version_id BIGINT NOT NULL
    REFERENCES valuation_model_versions(id) ON DELETE CASCADE,
  artifact_name TEXT NOT NULL,
  artifact_bytes BYTEA NOT NULL,
  sha256 TEXT NOT NULL,
  media_type TEXT NOT NULL,
  PRIMARY KEY (model_version_id, artifact_name)
);

CREATE TABLE IF NOT EXISTS valuation_fold_predictions (
  id BIGSERIAL PRIMARY KEY,
  model_version_id BIGINT NOT NULL
    REFERENCES valuation_model_versions(id) ON DELETE CASCADE,
  fold_id TEXT NOT NULL,
  duplicate_group_key TEXT NOT NULL,
  source_listing_id BIGINT NOT NULL,
  actual_price_usd DOUBLE PRECISION NOT NULL,
  predicted_price_usd DOUBLE PRECISION NOT NULL,
  log_error DOUBLE PRECISION NOT NULL,
  absolute_percentage_error DOUBLE PRECISION NOT NULL,
  support_grade TEXT NOT NULL CHECK (support_grade IN ('low', 'medium', 'high'))
);

CREATE INDEX IF NOT EXISTS idx_valuation_fold_predictions_model
  ON valuation_fold_predictions (model_version_id, fold_id);

CREATE TABLE IF NOT EXISTS valuation_refresh_state (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  listings_changed_at TEXT NOT NULL,
  reason TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS rental_clubs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by_user_id BIGINT NOT NULL REFERENCES users(id),
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  location TEXT NOT NULL,
  airport_code TEXT,
  website_url TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (normalized_name, location)
);

CREATE TABLE IF NOT EXISTS rental_club_cost_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rental_club_id BIGINT NOT NULL REFERENCES rental_clubs(id),
  effective_from TEXT NOT NULL,
  effective_to TEXT,
  insurance_annual_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
  club_monthly_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
  club_annual_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
  initiation_fee_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
  source_url TEXT,
  created_by_user_id BIGINT NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (effective_to IS NULL OR effective_to > effective_from)
);

CREATE TABLE IF NOT EXISTS rental_aircraft_offerings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rental_club_id BIGINT NOT NULL REFERENCES rental_clubs(id),
  aircraft_model_variant_id BIGINT NOT NULL REFERENCES aircraft_model_variants(id),
  created_by_user_id BIGINT NOT NULL REFERENCES users(id),
  display_name TEXT NOT NULL,
  tail_number TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rental_rate_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rental_aircraft_offering_id BIGINT NOT NULL REFERENCES rental_aircraft_offerings(id),
  effective_from TEXT NOT NULL,
  effective_to TEXT,
  rental_rate_per_hour_usd DOUBLE PRECISION NOT NULL,
  rate_type TEXT NOT NULL DEFAULT 'wet',
  billing_meter TEXT NOT NULL DEFAULT 'hobbs',
  source_url TEXT,
  created_by_user_id BIGINT NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (effective_to IS NULL OR effective_to > effective_from)
);
